### ISSUE TITLE
Edition of a CustomAction within a SharedAction doubles backslache(s)

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#100]
Into a shared action, if we create  a custom action that contains "\\" those backslashes will be duplicated at each refresh of project

**Comment by nathalie-lammelin** [comment]
Not reproduced at r7487157.
- which version do you use ?
- could you paste a sample and give steps to reproduce ?

**Comment by CharlesGrimont** [comment]
* The version is 7.6.0-beta from dev studio at latest of develop (commit 748715726fb3994f91289f8524cf26d373f84f9d)

* The following file contains the shared action to reproduce. you just have to paste the content on your project. [shared_action_bug_backslash.txt](https://github.com/convertigo/convertigo/files/3057794/shared_action_bug_backslash.txt)

**Comment by nathalie-lammelin** [comment]
Special case of a CustomAction within a SharedAction, but not referenced by an InvokeAction.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
