### ISSUE TITLE
DND a FullSync View in a Mobile Builder action creates the getView component

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#106]

**Comment by nicolas-albert** [comment]
Fixed by 0e948de0e52bb2b606f5bfe5b02aade44576922c **Ctrl+DND a FS View under a MB Event create a FS View action**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
