### ISSUE TITLE
High loading time when moving/editing beans within a SharedAction

### ISSUE THREAD

**Issue by lexinor** [convertigo/convertigo#107]
There is a high loading time when moving beans within a Shared Action.
I'm in my Shared Action when I want to move a bean to a lower or higher level it takes around 10 to 20 seconds or so to actually move the bean. 

Here is an example : 

* My Shared Action 
![iss1](https://user-images.githubusercontent.com/28725795/57528047-8ac0e580-7331-11e9-812c-def61db2a77b.PNG)

* Here I want to move my last "Toast" to a higher level. When I do so my Studio freezes and is not responding
![iss2](https://user-images.githubusercontent.com/28725795/57528189-f1de9a00-7331-11e9-9ada-6ce24d8128fa.PNG)

* After around 20 seconds or so the bean has been moved and everything is back to normal
![iss3](https://user-images.githubusercontent.com/28725795/57528211-0fabff00-7332-11e9-979d-3c188a5d07ae.PNG)

**This is not happening when moving beans which are not within a Shared Action.**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
