### ISSUE TITLE
Add support of App Shared Components

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#111]

**Comment by nathalie-lammelin** [comment]
First version commited (without shared parameters/properties).
Before closing, need to update the **documentation**. Also, wait for some feed backs & tests.

Here are the 3 projects I used to implement the feature ( please rename` .zip` to `.car` ) :
`Feature111` **use** `Red111` and `Olive111`
[Red111.zip](https://github.com/convertigo/convertigo/files/3217146/Red111.zip)
[Olive111.zip](https://github.com/convertigo/convertigo/files/3217147/Olive111.zip)
[Feature111.zip](https://github.com/convertigo/convertigo/files/3217148/Feature111.zip)

**Comment by opicciotto** [comment]
STill in progress.. Som documentation to be done ..

**Comment by nathalie-lammelin** [comment]
Another sample project with `CustomAction` in `Shared` beans:
[buttons111.zip](https://github.com/convertigo/convertigo/files/3265894/buttons111.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**

Note: At first, thought buttons 2 and 4 (with customAction components) were not working. It took me time to realize the logs were in debug level and my Devices logger was to default level (INFO). Changing in the customAction the level to warn made the trick...
