### ISSUE TITLE
Convertigo git Menu doesn't reload project after git pull

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#112]
When we use Team menu on a convertigo project, project is not reload after a git action...

This can be very confusing for user that expect that its version be the same than the loaded one..

May be we can auto refresh the project ?

**Comment by nicolas-albert** [comment]
I don't know if we can hook Team actions, this isn't not our code at all.
We just allow the Git plugin to contribute our menu.
And if we success to hook, we should warn the user is its project isn't saved.

**Comment by CharlesGrimont** [comment]
Maybe we can add hooks to git repository itself ? 

for example "post-merge hook" and calling any studio functions from external bash ?

Don't know if its possible ...

https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

**Comment by CharlesGrimont** [comment]
Or maybe in the future built our own "git menu"

**Comment by nicolas-albert** [comment]
I found a *onWorkingTreeModified* and I already reload projects affected (one of yaml modified or removed).
But now, the user cannot contest this.
Maybe I have to add a dialog with *reload* (lose local changes) and *save* (replace working tree) buttons.

**Comment by nicolas-albert** [comment]
Tested with **convertigo-04303-hotfix-7.6.2-7.6.2-beta**
