### ISSUE TITLE
Administration: Certificate Mappings configuration is buggy

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#114]
Everything works well while adding new mappings.
But, when we change an existing mapping and click the `update` button at the end of line, all mappings disappear. The entire `stores.properties` file is overwritten and emptied : all mappings are lost !

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03592-develop-7.6.0-beta)**
