### ISSUE TITLE
Add an 'Export light' command for MB project

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#115]
For lighter project exchange (to be used in Studio), we'd like to export without below folders :
- `\_private\ionic\node_modules`
- `\DisplayObjects\mobile\build`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 04565-develop-7.7.0-beta)**

**Comment by nathalie-lammelin** [comment]
`DisplayObjects\mobile\assets` are deleted and should not.

Case export of a build project with
- TestCases : `unchecked`
- MobileBuilder build files: `unchecked`
- Mobile Plaform assets: `checked`

Didn't see any `Stubs` option ?

**Comment by nicolas-albert** [comment]
Will see monday !

**Comment by nicolas-albert** [comment]
Stubs option is visible if the project contains almost a stub.
I reproduce your case with missing assets if checked.

**Comment by gregory-vorbe** [comment]
Test in **Convertigo EMS Studio 7.7.0_beta (build 04926-develop-7.7.0-beta)**
Maybe we could also have an option to export or not **dataset**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05102-develop-7.7.0-beta)**
