### ISSUE TITLE
May we have a bean "Pause" ?

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#117]
Sometimes we need to make a pause between two bean/actions, but this can't be done without writing Javascript's setimout that need some skills...

May we introduce a simple Action bean that performs easily a  

setTimeout(()=>{
resolve();
}, time);

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06082-develop-7.7.0-beta)**
- Icon is done.
