### ISSUE TITLE
Bean close modal, closes any page on where its called

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#118]
CloseModal bean, must close Last modal opened, instead of closing the page where its called.

**Comment by nathalie-lammelin** [comment]
A sample project for test:
[issue118.zip](https://github.com/convertigo/convertigo/files/3257230/issue118.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
