### ISSUE TITLE
Mobile picker should display data when the Application Object is selected, and all SetGlobal actions

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#121]
When you work on app events and want to use the MobilePicker, no data is displayed in it. To display data you have to select a Page or a Menu.

Also, SetGlobal action placed in AppEvents are not listed in the Mobile Picker

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
