### ISSUE TITLE
MB: Unhandled exceptions breaking App sources generation

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#122]
Not easily reproducible.

Within a `SharedAction `(referenced by an `Invoke `action)
- Move a component which need some `imports `to be added to work
- Delete a component (and its childs)

**Comment by nathalie-lammelin** [comment]
Waiting for some feedbacks...

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03862-release-7.6.0-7.6.0)**
 * Followed described steps and did not reproduce issue.
