### ISSUE TITLE
CloseLoading is not chaining to next action

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#123]
Missing `resolve() or reject() ` if `page.global["_c8o_loaders"]` **is** undefined

**Comment by CharlesGrimont** [comment]
edit: PREVIOUS COMMIT WAS NOT RELATED to this ticket but to #126

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**
