### ISSUE TITLE
Ctrl+DND a SharedAction on an event or action creates the InvokeAction

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#124]

**Comment by gregory-vorbe** [comment]
KO in **Convertigo EMS Studio 7.6.0_beta (build 03645-develop-7.6.0-beta)**

Got following pop-up alert:
![image](https://user-images.githubusercontent.com/1685373/59913818-3c673200-9419-11e9-95ba-1bab1987707f.png)

I can DND "Invoke SharedAction" component from Mobile Palette to the Event component

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**

 * It would be great if variables were also automatically imported from the target sharedAction.
