### ISSUE TITLE
Ctrl+DND a SharedComponent on a component creates the UseShared component

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#125]

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03645-develop-7.6.0-beta)**

**Comment by gregory-vorbe** [comment]
Can not Ctrl+Dnd a shareComponent directly under a Page : 
![DnD_SharedComponentPage](https://user-images.githubusercontent.com/1685373/76945843-69426a00-6903-11ea-9fd2-95ffd4040930.gif)

Sometimes, I successfully manage to Drag and Drop the ShareComponent on the Page.
I can drop the sharedComponent to the Content component then move it directly under the Page : 
![DnD_SharedComponentPage_workaround](https://user-images.githubusercontent.com/1685373/76946220-feddf980-6903-11ea-9bfa-45499b60f32f.gif)

**Comment by gregory-vorbe** [comment]
[testMB771_07153.zip](https://github.com/convertigo/convertigo/files/4349119/testMB771_07153.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07225-hotfix-7.7.1-7.7.1-beta)**
