### ISSUE TITLE
Some builds prod failed because of "heap out of memory"

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#126]
We must change the command to start build prod....

**Comment by CharlesGrimont** [comment]
see https://github.com/convertigo/convertigo/commit/74c5c08d3213efc473cafe9a00a2f061a7746148

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
