### ISSUE TITLE
Create a ClosePopover action

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#127]
To close a page create with `PopoverAction`

**Comment by nathalie-lammelin** [comment]
A sample project (with to pages) for tests:
[issue127.zip](https://github.com/convertigo/convertigo/files/3257927/issue127.zip)

**Comment by nathalie-lammelin** [comment]
ref #127 - In a0bc61b : Fixed event property of PopoverAction

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**
