### ISSUE TITLE
MB Actions: transpilation of empty value in TS mode failed at runtime

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#128]
`[warn] [MB] ATS1559742367575: For message:, Unexpected token )`

**Comment by nathalie-lammelin** [comment]
A sample project for test:
[issue128.zip](https://github.com/convertigo/convertigo/files/3257535/issue128.zip)

**Comment by nicolas-albert** [comment]
Ok with the build **convertigo-03345-develop-7.6.0-beta**, thx for the testing project !
