### ISSUE TITLE
Mobile builder does not rebuilds 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#129]
Use case:

We have a SharedAction that is invoked itself from a SharedComponent.
This shared component is "used from a page"
So indirectly, shared action is invoked.

But sometimes, when we edit/modify/save a Custom action within this shared action, project do not rebuilds ...

**Comment by nathalie-lammelin** [comment]
You can not 'edit' a shared action. Need clarifications.

**Comment by gregory-vorbe** [comment]
Ok in **Convertigo EMS Studio 7.6.0 (build 03862-release-7.6.0-7.6.0)**
 * Followed steps and did not reproduce issue.
