### ISSUE TITLE
Http response always in UTF-8 even if the Requestable defines an another Charset

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#130]
Easy to reproduce.
Make a Sequence with an Element and a value containing a "é" for exemple.
Change the Sequence charset to ISO-8859-1.
Take a bash and call the Sequence with curl :
```
$ curl -sv "http://localhost:18080/convertigo/projects/Ok/.pxml?__sequence=Charset"
<?xml version="1.0" encoding="ISO-8859-1"?><document connector="" context="studio_Ok:S:Charset" contextId="studio_Ok:S:Charset" fromStub="false" fromcache="false" generated="Thu Jun 06 15:48:28 CEST 2019" project="Ok" sequence="Charset" signature="1559828908946" transaction="" version="7.6.0_beta">
    <element>é</element>
</document>
...
< Content-Type: text/xml;charset=UTF-8
```
The header Content-Type must be `text/xml;charset=ISO-8859-1` and the content encoded respecting this charset.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03645-develop-7.6.0-beta)**

**Comment by nicolas-albert** [comment]
FOR JMX : test a requestable with the property to another charset than UTF8 (like ISO8859-1) and check this is true with special chars (like é à etc...).
