### ISSUE TITLE
Improve MB ForEach bean

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#133]
Add new `item` and `index` properties for use in actions
Fix `directive expression` : check for alphanumeric character at begining

**Comment by nathalie-lammelin** [comment]
A sample project for tests : 
[issue133.zip](https://github.com/convertigo/convertigo/files/3310969/issue133.zip)

**Comment by nathalie-lammelin** [comment]
Updated sample for tests (added nested loop in page3) :
[issue133.zip](https://github.com/convertigo/convertigo/files/3313792/issue133.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**

**Comment by gregory-vorbe** [comment]
Bean documentation needs to be updated.

**Comment by gregory-vorbe** [comment]
Added documentation on how to access ForEach item and ForEach index values : 8cfe2a27cf5817757f78be7ea22c2aa974e41a25

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
