### ISSUE TITLE
Add a new IfElseAction working with a ElseHandler

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#137]
To work with the `IfAction` (only)

**Comment by nathalie-lammelin** [comment]
A sample project for tests:
[issue137.zip](https://github.com/convertigo/convertigo/files/3325858/issue137.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03826-release-7.6.0-7.6.0)**
