### ISSUE TITLE
Add the lib_AmazonLEX in the new project wizard.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#141]
We need this lib in the new project=wizard

**Comment by nicolas-albert** [comment]
What do I put to the Wizard ?
Amazon LEX or Amazon Alexa ?
Which logo ? This one ?

![logo](https://stelligent.com/wp-content/uploads/2017/11/AI_AmazonLex_LARGE-1.png)

**Comment by opicciotto** [comment]
Amazon LEX and yes, this logo.

**Comment by gregory-vorbe** [comment]
KO in **Convertigo EMS Studio 7.6.0 (build 03826-release-7.6.0-7.6.0)**

Got an information pop-up when importing project:
![image](https://user-images.githubusercontent.com/1685373/60250749-80e64800-98c7-11e9-8a23-f89b003823f6.png)

Studio sets automatically the default connector and project is in 'changed' state and has to be saved.
Project can be closed then re-opened correctly.

**Comment by nicolas-albert** [comment]
Ah ! my fault, I'll fix that :)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03862-release-7.6.0-7.6.0)**

 * tested with demo project : https://bitbucket.org/c8opocs/converti__go/src/master/
