### ISSUE TITLE
Mobile Builder : need a Switch action bean

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#143]

**Comment by nathalie-lammelin** [comment]
A sample project (v8.0.0) with 4 pages: [issue143Ngx.zip](https://github.com/convertigo/convertigo/files/6003051/issue143Ngx.zip)

**Comment by gregory-vorbe** [comment]
Is the proposed sample project working correctly? Page4 uses a sharedComponent to display a button with dynamic text but button does not display. Maybe I don't know how to use this project.

**Comment by nathalie-lammelin** [comment]
> Is the proposed sample project working correctly? Page4 uses a sharedComponent to display a button with dynamic text but button does not display. Maybe I don't know how to use this project.

The project is old and should have been migrated again...
I put a new version of the project: [issue143Ngx.zip](https://github.com/convertigo/convertigo/files/8118559/issue143Ngx.zip)

**Comment by gregory-vorbe** [comment]
in **Convertigo EMS Studio 8.0.0_beta (build 12517-develop-8.0.0-beta)**
I would have invert **SwitchCase Handler** and **SwitchAction** icons
![image](https://user-images.githubusercontent.com/1685373/155350632-cf12144f-2fd9-4951-93b0-cef7ad6c0e05.png)
If I have understood well the documentation, **SwitchAction** is the global parent that contains **SwitchCase Handler** that is a specific execution branch of the Switch component.
