### ISSUE TITLE
Importing & lauching an old MB project may fail with compilation errors in action.ts

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#144]
Case of old 7.5.x project using page.call() with 4 arguments but since 7.6.0 it uses 5 arguments.

Maybe we could use the `function.prototype.apply()` with array of arguments, knowing the `_tpl version`.

**Comment by nathalie-lammelin** [comment]
Tested with a `7.5.7` project and `sample_HelloWorld` project

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.1_beta (build 04014-hotfix-7.6.1-7.6.1-beta)**

**Comment by gregory-vorbe** [comment]
Reopen/Close issue because of a bug on labels
