### ISSUE TITLE
Camera action does not work anymore in App Viewer

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#145]
Reported by @gregory-vorbe: Ok in Browser.

**Comment by nathalie-lammelin** [comment]
Need precisions, because camera action is working well.
Tested OK in browser (chrome) and android phone (OnePlus 5t) with following 7.6.1 project: 
[issue145.zip](https://github.com/convertigo/convertigo/files/3372145/issue145.zip)

**Comment by nathalie-lammelin** [comment]
Ok. Not working in AppViewer...

**Comment by nicolas-albert** [comment]
I'll try with JxBrowser 7.x to see.

**Comment by nathalie-lammelin** [comment]
Does not work in AppViewer if `sourceType` property is set to `CAMERA`.
When property is set to `PHOTOLIBRARY` or `SAVEDPHOTOALBUM`, all is OK.

**Comment by nicolas-albert** [comment]
I have something working with JxBrowser 7 and I found the good API to enable it for JxBrowser 6.
I can activate it for Convertigo 7.6.1 !

**Comment by gregory-vorbe** [comment]
Convertigo EMS Studio 7.6.1_beta (build 04033-hotfix-7.6.1-7.6.1-beta)

![image](https://user-images.githubusercontent.com/1685373/61208311-6a2d5700-a6f7-11e9-85aa-7f68d9ee12cc.png)

**Comment by nathalie-lammelin** [comment]
Please rename your page to something else than Camera

**Comment by gregory-vorbe** [comment]
You are right, that was the problem!

OK in **Convertigo EMS Studio 7.6.1_beta (build 04033-hotfix-7.6.1-7.6.1-beta)**
