### ISSUE TITLE
Add support of PageEvent & SubscribeHandler for SharedComponent

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#147]

**Comment by nathalie-lammelin** [comment]
The `lib_AmazonLEX` (7.7.0.1) project reviewed with a **ChatBot** shared component : 
[lib_AmazonLEX.zip](https://github.com/convertigo/convertigo/files/3349960/lib_AmazonLEX.zip)

**Comment by nathalie-lammelin** [comment]
For test of `AppEvent`: can use `ShatBot` shared component of `lib_AmazonLEX` project

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06122-develop-7.7.0-beta)**

**Comment by gregory-vorbe** [comment]
Issue when disabling the the sharedComponent containg a subscribe handler and/or when disabling a subscribe handler in the page event.
![image](https://user-images.githubusercontent.com/1685373/70164331-42985480-16c1-11ea-90b7-2fb71c507272.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06138-develop-7.7.0-beta)**
