### ISSUE TITLE
Using SourcePicker may freeze the Studio

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#149]
When
- schema(s) for project are not already generated
- project has a reference on another project which has reference on it

**Comment by nathalie-lammelin** [comment]
Tested with a customer project.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.1_beta (build 04042-hotfix-7.6.1-7.6.1-beta)**
