### ISSUE TITLE
Evaluate and use Tomcat 8.5 or 9 for Studio and Docker

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#155]
We use Tomcat 7 that is still supported but Docker supported arch is only amd64.
Maybe we can take advantages of new features and improvements of Tomcat 8.5 or 9.

**Comment by gregory-vorbe** [comment]
- Studio Tomcat version is 9.0.22
 - Server Tomcat version is 9.0.24

**Comment by nicolas-albert** [comment]
@gregory-vorbe minor versions while change again. Docker use the latest automatically and I have to change manually for the studio.
