### ISSUE TITLE
Some Mobile Builder demos does not build correctly

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#157]
sample_HelloWorld project does not build correctly in Convertigo EMS Studio 7.6.1_beta (build 03948-hotfix-7.6.1-7.6.1-beta). It uses the mobilebuilder_tpl_7_5_2 Template project.
Error is:
![image](https://user-images.githubusercontent.com/1685373/60735610-6a3d9200-9f54-11e9-9101-13bb42aac4fe.png)

An hotfix is needed to support previous TPL versions.
Updating the Application to TPL 7.6.0 is a workaround but should be avoided as a definitive solution for users trying to test their 7.5.X projects in 7.6.0

But for 7.6.0 samples, we can add a task to update them to TPL 7.6.0.

Thx!

**Comment by nathalie-lammelin** [comment]
Related with #144

**Comment by nicolas-albert** [comment]
OffChat don't build with the 7.6.0.

All samples should be tested and released with the latest TPL available.

**Comment by nathalie-lammelin** [comment]
since #144 has been fixed, all projects are building using `convertigo-03976-hotfix-7.6.1-7.6.1-beta` (no matter of _tpl version used)

**Comment by gregory-vorbe** [comment]
Duplicate of #144

**Comment by gregory-vorbe** [comment]
Just for testing github bug on label remove filter syntax
