### ISSUE TITLE
Update Browser component to the latest version (7.7)

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#158]

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05102-develop-7.7.0-beta)**

- jxbrowser-7.2.jar included in distribution

**Comment by nicolas-albert** [comment]
JxBrowser 7.6 is released but without the SWT support.
But we can use the 7.7 beta build until the release.

**Comment by nicolas-albert** [comment]
Installed studio use the 7.12.2 version.
Ok for convertigo-10002-develop-7.9.0-beta
