### ISSUE TITLE
Projects not visible on admin page

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#16]
With version Convertigo version 7.6.0_beta (build 00886-feature-3-UrlMapper_v2-7.6.0-beta).
When we deploy a project, the project is not visible on the projects admin page, but the projects are correctly deployed and can be used.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
