### ISSUE TITLE
AnimateAction is broken and doesn't work inside a Shared Component

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#163]
For an `AnimateAction` with other child actions : 
`Typescript Error Expected 2 arguments, but got 1.` or `[MB] AnimateAction: Animatable is not defined`
For an `AnimateAction` with no child actions : **ok**
For an `AnimateAction` inside a shared component: **ko**

**Comment by nathalie-lammelin** [comment]
7.6.1 projects for tests:
[issue163.zip](https://github.com/convertigo/convertigo/files/3398043/issue163.zip)
[issue163_lib.zip](https://github.com/convertigo/convertigo/files/3398045/issue163_lib.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.1_beta (build 04088-hotfix-7.6.1-7.6.1-beta)**
