### ISSUE TITLE
"Sliding Tabs" component not working any more

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#164]
Using a "**Sliding Tabs**" component in **TPL 7.6.0** generates following error:

> Runtime Error
> Uncaught (in promise): TypeError: __WEBPACK_IMPORTED_MODULE_2_rxjs_Observable__.Observable.fromEvent is not a function TypeError: __WEBPACK_IMPORTED_MODULE_2_rxjs_Observable__.Observable.fromEvent is not a function at new SuperTabs (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/ionic2-super-tabs/dist/components/super-tabs.js:115:73) at createClass (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:12712:20) at createDirectiveInstance (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:12547:37) at createViewNodes (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:14005:53) at callViewAction (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:14439:13) at execComponentViewsAction (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:14348:13) at createViewNodes (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:14033:5) at createRootView (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:13894:5) at callWithDebugContext (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:15319:42) at Object.debugCreateRootView [as createRootView] (D:/COMMON/C8O/sc761_64/workspace/MB_761_04070/_private/ionic/node_modules/@angular/core/esm5/core.js:14602:12)

Create a new Mobile Builder project in Convertigo 7.6.1, drop a "**Sliding Tabs Container**" component, Open Visual App Viewer.

It works using **TPL 7.5.7**

**Comment by nicolas-albert** [comment]
I look in the code of the 5.2.0 and it still use the Observable object.
In master and 6.0.0-beta tags, it doesn't use it.
But their is no npm package for that version !
So I try to use the [git urls as dependency](https://docs.npmjs.com/files/package.json#git-urls-as-dependen) but it doesn't retrieve it : git+https://github.com:zyra/ionic-super-tabs.git#v6.0.0-beta.11
Here the repo of the plugin : https://github.com/zyra/ionic-super-tabs

**Comment by CharlesGrimont** [comment]
This lib uses rxjs@5.2.0, and we are using rxjs@5.3.3, path of import changes bettwen versions of rxjs.
So we need to use rxjs-compat lib to fix this issue

**Comment by nicolas-albert** [comment]
Tested with **convertigo-04303-hotfix-7.6.2-7.6.2-beta**
