### ISSUE TITLE
Right-clicking a "SharedComponent" component from another project does not focus element in treeview

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#165]
You can use projects from #163 
In project '**issue163**', from page "**Use Shared**", if you right-click button "**CLICK ME**", it does nothing. It does not focus component from the other project (**issue163_lib**).
It works with a "**SharedComponent**" component from same project.
It would be great if it could work also when referencing shared components from other projects.

**Comment by nicolas-albert** [comment]
Do we backport this to 7.6.3 ?

**Comment by gregory-vorbe** [comment]
Is it supposed to work also when double-clicking the SharedComponent in Tree view ?
(I clicked the "Button #BtnShared" component from issue163_lib and was expecting to jump to page with button "CLICK ME" from project issue163.)

**Comment by nathalie-lammelin** [comment]
> Is it supposed to work also when double-clicking the SharedComponent in Tree view ?
> (I clicked the "Button #BtnShared" component from issue163_lib and was expecting to jump to page with button "CLICK ME" from project issue163.)

No. A shared component may be used in many pages. We cannot decide which page to load.

**Comment by gregory-vorbe** [comment]
You are right, didn't think of this case...

OK in **Convertigo EMS Studio 7.6.1_beta (build 04088-hotfix-7.6.1-7.6.1-beta)**
