### ISSUE TITLE
Global FullSync name database prefix

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#166]
Add a new engine property that automatically prepend a string to all FullSync database name.
This will isolate multiple Convertigo server to use the same CouchDB Cluster.
This property must be invisible in Cloud mode.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**

- Need documentation update for thisengine property and naming restriction (CouchDB DB name)
