### ISSUE TITLE
Add a "Finally" handler in mobile builder

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#168]
We should have a "FInally" type handler like to "Error" handler. This would execute code anyway even if an error occurred at the end of an action.

This could be called "Finally" or "Anyway" ?

**Comment by nathalie-lammelin** [comment]
I first had compilation error, then error at runtime...
I managed to make `Promise.finally` work (see  [Property 'finally' does not exist on type 'Promise<void>'](https://stackoverflow.com/questions/52079031/property-finally-does-not-exist-on-type-promisevoid/52098456) and [Using Promise.prototype.finally() in TypeScript](https://mariusschulz.com/blog/using-promise-prototype-finally-in-typescript))

**package.json**:
- `dependencies` : added `"promise.prototype.finally": "3.1.1"`
- `devDependencies`: modified for `"typescript": "~2.7.2"`

**tsconfig.json**:
- `compilerOptions`: in `lib` added `"esnext"`

**page.ts**:
```
import { shim as finallyShim } from "promise.prototype.finally";
....
constructor(...) {
   ...
   finallyShim();
}

ATSXXXXX(stack): Promise<any> {
   return new Promise((resolve, reject) => {
      ...
   }
   .catch((error:any) => {
      ...
   })
   .finally(() => {
     ...
   })
}
```
@opicciotto @CharlesGrimont 
What do think ? Ok ?

**Comment by opicciotto** [comment]
Attention A vérifier si Ionic 3.9.2 est compatible avec cette version de
TypeScript ?





*De :* Nathalie LAMMELIN <notifications@github.com>
*Envoyé :* jeudi 31 octobre 2019 17:42
*À :* convertigo/convertigo <convertigo@noreply.github.com>
*Cc :* Convertigo <olivierp@convertigo.com>; Mention <
mention@noreply.github.com>
*Objet :* Re: [convertigo/convertigo] Add a "Finally" handler in mobile
builder (#168)



I first had compilation error, then error at runtime...
I managed to make Promise.finally work (see Property 'finally' does not
exist on type 'Promise'
<https://stackoverflow.com/questions/52079031/property-finally-does-not-exist-on-type-promisevoid/52098456>
and Using Promise.prototype.finally() in TypeScript
<https://mariusschulz.com/blog/using-promise-prototype-finally-in-typescript>
)

*package.json*:

   - dependencies : added "promise.prototype.finally": "3.1.1"
   - devDependencies: modified for "typescript": "~2.7.2"

*tsconfig.json*:

   - compilerOptions: in lib added "esnext"

*page.ts*:

import { shim as finallyShim } from "promise.prototype.finally";

....

constructor(...) {

   ...

   finallyShim();

}



ATSXXXXX(stack): Promise<any> {

   return new Promise((resolve, reject) => {

      ...

   }

   .catch((error:any) => {

      ...

   })

   .finally(() => {

     ...

   })

}

@opicciotto <https://github.com/opicciotto> @CharlesGrimont
<https://github.com/CharlesGrimont>
What do think ? Ok ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/convertigo/convertigo/issues/168?email_source=notifications&email_token=AAH64FFRMQAKULO7WGP4IJTQRMDGRA5CNFSM4IFY57TKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECYOLII#issuecomment-548464033>,
or unsubscribe

**Comment by nathalie-lammelin** [comment]
We've decided to implement a **fake** `finally` instead of using `promise.prototype.finally` (too heavy solution)

**Comment by nathalie-lammelin** [comment]
Close: reopen if needed

**Comment by gregory-vorbe** [comment]
To test the feature I have used two parallels callSequenceAction.
I was expecting the *Finally handler* to execute at the very end of the sequences but it executed twice, each time at the end of a sequence call. Is it supposed to work this way or is it supposed to execute only once and wait for all actions?
Attaching project: MobileBuilderComponents
Use *Finally* Page
Thx
[MobileBuilderComponents.zip](https://github.com/convertigo/convertigo/files/4016402/MobileBuilderComponents.zip)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : workaround
Add a simple action (e.g. LogAction) under your event and move your 2 CallSequence inside.

The feature will be improved for 7.8.0 by #291.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**
