### ISSUE TITLE
Add Lazy loading feature to MB

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#169]
See https://ionicframework.com/blog/ionic-and-lazy-loading-pt-1/

**Comment by opicciotto** [comment]
Official documentation is here 👍 
https://ionicframework.com/docs/v3/api/navigation/IonicPage/

**Comment by opicciotto** [comment]
Add a "LazyLoad Priority" field to pages. Can be
- High
- low
-Off

This has to be generated in the @ionicPage() decorator as :

@IonicPage({
  name: 'my-page',
  priority: 'high'
})

Also we can use our page  segment property to set the 'name' in the @IonicPage Decorator

**Comment by nathalie-lammelin** [comment]
to be tested before close

**Comment by opicciotto** [comment]
Globally works as expected, but some additional work has to be done to support additional Angular components declared in customActions or by additional components such as chart or calendar :

As we use lazyLoading we have a module per page. So we must also declare the additional module in the page.module.ts. For example if we want to use charts in a Dashboard page :

```
import { NgModule } 			from '@angular/core';
import { ChartsModule } from 'ng2-charts';

import { IonicPageModule } 		from 'ionic-angular';
import { Dashboard } from "./dashboard";


@NgModule({
  declarations: [
	Dashboard
  ],
  imports: [
	ChartsModule,
	IonicPageModule.forChild(Dashboard)
  ]
})
export class DashboardModule {}


```

**Comment by nathalie-lammelin** [comment]
A test project: [issue169.zip](https://github.com/convertigo/convertigo/files/3584517/issue169.zip)

first Page (high priority) has a button to root to Page1
`Chart` component in Page1 (low priority)
`Signature` component in Page2 (low priority)
`TextToSpeech` action in a Page3 (low priority)
`TextToSpeech` shared action invoked from Page4 (low priority)

**Comment by CharlesGrimont** [comment]
We can't use i18n translate module, defines in app.component.ts of template,

We must be able to import a module in a specific page
or in each pages

Test project:  [convertigo_issue169.zip](https://github.com/convertigo/convertigo/files/3594901/convertigo_issue169.zip)

**Comment by nathalie-lammelin** [comment]
> We can't use i18n translate module, defines in app.component.ts of template,
> 
> We must be able to import a module in a specific page
> or in each pages
> 
> Test project: [convertigo_issue169.zip](https://github.com/convertigo/convertigo/files/3594901/convertigo_issue169.zip)

You can do it using a `CustomAction` :
1 - Add a `PageEvent` to your page with a `CustomAction` under (which does nothing)
2 - Configure your action properties : 
   App imports : TranslateModule, @ngx-translate/core
   App modules : TranslateModule
By the way, it could be easier to have a `UseTranslationAction` we could DnD instead of using a `CustomAction`, **OR**, we could decide to have this TranslateModule available for all pages by default (hard code in `page.module.tpl` of the `_tpl_7_7_0`)

![MB_Translation](https://user-images.githubusercontent.com/27724039/66317115-3427f980-e919-11e9-93af-83f7b38733dc.PNG)

**Comment by nathalie-lammelin** [comment]
TranslateModule is available for **all** pages since last commit with _tpl_7_7_0 (v 7.7.0.**4**).
It is therefore **unnecessary** to add a CustomAction to reference the module.

**Comment by nathalie-lammelin** [comment]
We need **CAF** modifications to handle lazy loading for **c8oRoute**

**Comment by opicciotto** [comment]
Hello here is an issue found using Calendar Picker.

```
Error: Uncaught (in promise): Error: No component factory found for CalendarModal. Did you add it to @NgModule.entryComponents?
Error: No component factory found for CalendarModal. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (http://localhost:8100/build/vendor.js:4304:34)
    at CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:8100/build/vendor.js:4368:19)
    at ModalCmp.ionViewPreLoad (http://localhost:8100/build/vendor.js:68427:36)
    at ModalImpl.ViewController._lifecycle (http://localhost:8100/build/vendor.js:22727:33)
    at ModalImpl.ViewController._preLoad (http://localhost:8100/build/vendor.js:22589:14)
    at OverlayPortal.NavControllerBase._preLoad (http://localhost:8100/build/vendor.js:61215:14)
    at OverlayPortal.NavControllerBase._viewInit (http://localhost:8100/build/vendor.js:60884:14)
    at http://localhost:8100/build/vendor.js:60695:23
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5135:33)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:19174)
    at OverlayPortal.NavControllerBase._fireError (http://localhost:8100/build/vendor.js:60664:16)
    at OverlayPortal.NavControllerBase._failed (http://localhost:8100/build/vendor.js:60657:14)

```

**Comment by opicciotto** [comment]
Since lazy loading seems that relaunching a MobileBuilder view when a CustomAction is still edited causes a NPM error.

This is because the icon-app-script tries to compile a src/page/xxxx.temp.ts file and this file is not NgModule compliant.

I suggest to close all CustomAction, Page Class & App Class editors when we relaunch a MobileBuilder Build.

**Comment by nathalie-lammelin** [comment]
need #238 to be done

**Comment by nathalie-lammelin** [comment]
Close: reopen if needed

**Comment by opicciotto** [comment]
We are now using lazy loading for 3 months and complex projects like ionicConferenceApp ; C8oForms & C8Osignup are OK. So we assume this global feature is now Q&A tested. If specific issues are found they will have their own Issue#

**Comment by nathalie-lammelin** [comment]
Improvement for Lazy loading will be made in #292

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0 (build 06456-release-7.7.0-7.7.0)**
 - Barcode Scanner, Camera, File Chooser, SpeechToText, TextToSpeech working correctly.
