### ISSUE TITLE
Treeview component doesn't work any more

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#17]
Compilation errors because of double declarations

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 7.6.0_beta (build 03079-develop-7.6.0-beta)**:

 - Replace '**treenodes**' by '**Tree data**' property in documentation:
 ![image](https://user-images.githubusercontent.com/1685373/58101593-3c88cd80-7be0-11e9-8344-4f22d7914808.png)
 - Error at runtime after component was added (same after re-install packages):
![image](https://user-images.githubusercontent.com/1685373/58102062-fa13c080-7be0-11e9-884d-36f8903da2d5.png)
![image](https://user-images.githubusercontent.com/1685373/58102182-262f4180-7be1-11e9-8bfe-66b5c15e139e.png)

**Comment by nathalie-lammelin** [comment]
Tested in AppViewer and Browser, dev mode and prod mode.

**Comment by gregory-vorbe** [comment]
Convertigo EMS Studio 7.6.1_beta (build 04033-hotfix-7.6.1-7.6.1-beta)

 * Replace '**treenodes**' by '**Tree data**' property in documentation:
    ![Treeview](https://user-images.githubusercontent.com/1685373/58101593-3c88cd80-7be0-11e9-8344-4f22d7914808.png)
 * '**Is Expanded Field**' not working, tree is always collapsed.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.1_beta (build 04042-hotfix-7.6.1-7.6.1-beta)**
