### ISSUE TITLE
Allow app "useClickForTap" to handle differently "(tap)" and "onTap" events

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#178]
In some case we need a real `(tap)` because Ionic `(click)` is buggy.
In such case, `(tap)` must not be replaced by `(click)` in source generation even if app `useClickForTap` property has been set to `true`.

**Comment by nathalie-lammelin** [comment]
Need to **write** `(tap)` instead of selecting `onTap` from combo

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.3_beta (build 04506-hotfix-7.6.3-7.6.3-beta)**
