### ISSUE TITLE
Import and reference projects by a GIT url

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#184]
Instead of retrieve and/or deploy project dependencies or import a project through a **[project].car** file, it could be directly imported by a **string** that define :

- the project name
- the git url
- optionally the branch or the tag to checkout
- optionally the subpath of the project inside the repository

format: **[project name]=[git url]:path=[sub path]:branch=[branch name]**

sample: **qaSteps=git@bitbucket.org:convertigoqualif/convertigo-qualif-jmx-2.git:path=workspace/projects/qaSteps:branch=master**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05102-develop-7.7.0-beta)**
