### ISSUE TITLE
While invoking a shared action, variables are overriden with previous invoke ones

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#185]
Seen in a recursive case between two shared actions.
See attached project : [issue185.zip](https://github.com/convertigo/convertigo/files/3580338/issue185.zip)
In a 7.6.3 Studio, clicking the page button will end in an endless loop...

**Comment by nathalie-lammelin** [comment]
Updated attached project.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.4_beta (build 04793-hotfix-7.6.4-7.6.4-beta)**
 - tested with issue185.car
