### ISSUE TITLE
Within a shared action, cannot use 'this' keyword in actions variable/property values

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#186]
It ends with an error at runtime:
- cannot read property 'xxxx' of undefined
- c8oPage is not defined

A workaround is to replace **this** by **page**

See attached project : [issue186.zip](https://github.com/convertigo/convertigo/files/3579192/issue186.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.4_beta (build 04793-hotfix-7.6.4-7.6.4-beta)**

- Tested with issue186.car
