### ISSUE TITLE
Improve assets files copy at build time

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#187]
Assets files may be corrupted at build time because of:
- double copy process (src dir <=> build dir)
- large files

**Comment by gregory-vorbe** [comment]
Improvement has been tested with a previous version.
I just checked that the code and logs are still present in the current version: 
OK in **Convertigo EMS Studio 7.6.4_beta (build 04802-hotfix-7.6.4-7.6.4-beta)**
