### ISSUE TITLE
Update JxBrowser to 6.21 and use the 64bit version for windows

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#19]
We use a **JxBrowser 6.19.1** (chromium 60 based) that use a 32 bit version on Windows 64 bit.
With the new **JxBrowser 6.21** (chromium 64 based), the 64 bit version is available for Windows.

Maybe some other improvements : 

- [6.20 release note](https://jxbrowser.support.teamdev.com/support/discussions/topics/9000043250)
- [6.21 release node](https://jxbrowser.support.teamdev.com/support/discussions/topics/9000044535)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03052-develop-7.6.0-beta)** :

 - Bundle-Name: JxBrowser 6.23.1 Chromium Windows 64-bit
