### ISSUE TITLE
Integrate Fauxton into Convertigo Admin

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#192]
Add an icon "Fullsync" to the admin sidebar to access to the Fauxton of the fullsync connector and compatible with #166 **Global FullSync name database prefix** (only show filter DB with this prefix).

**Comment by nicolas-albert** [comment]
Move replication via integrated Fauxton to #264.

TODO : hide replication menu for the current version

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**

 - Replication button hidden.
