### ISSUE TITLE
Optimize CouchDB PostBulk merge/override to do less requests

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#193]
With PostBulk for CouchDB Connector or the FullSync Connector without c8oHash, and the policy Merge or Override, 1 request per document is done and that take a lot of time.
In this case, we can use a **_all_docs** request to replace multiple requests and save a lot of time.

**Comment by nicolas-albert** [comment]
Validated by the client.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.4_beta (build 04802-hotfix-7.6.4-7.6.4-beta)**
