### ISSUE TITLE
FS getDocument transaction failed 404 with an id containing a +

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#194]
We use HttpClient 4.5.9 for the FullSync/CouchDB request.
HttpClient 4.5.7 broke many projects by changing the way of the url encoding :

- https://github.com/spring-projects/spring-boot/issues/16043
- https://github.com/aws/aws-sdk-java/issues/1919

We have to use HttpClient 4.5.6 or 4.5.10.

**Comment by nicolas-albert** [comment]
[issue194.zip](https://github.com/convertigo/convertigo/files/3616388/issue194.zip)

First, use the TC of PostDocument, then the TC of the GetDocument.

GetDocument return 404 with the bug.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.4_beta (build 04775-hotfix-7.6.4-7.6.4-beta)**
