### ISSUE TITLE
Missing fake sapjco3.jar to replace with the true sapjco3.jar

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#197]
For SAP, we have to replace our fakejar with a true SAP JCO jar (and the dll).
This jar is missing in **7.6.3** (integrated in dependencies.jar).

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Server 7.6.4_beta (build 04775-hotfix-7.6.4-7.6.4-beta)**
