### ISSUE TITLE
CloseModalAction.ts contains Garbage resulting from improper merge

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#20]
convertigo/engine/src/com/twinsoft/convertigo/beans/mobile/components/dynamic/actionbeans/CloseModalAction.ts

Is containing Garbage from and improper merge and has to be cleaned up.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
