### ISSUE TITLE
Call index.jsp should return index.html content

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#200]
With previous Convertigo Studio and Server versions, if we called convertigo/projects/<projectName>/index.jsp the index.html content was returned.

This is not the case with the current Studio for Windows.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.4_beta (build 04793-hotfix-7.6.4-7.6.4-beta)**
