### ISSUE TITLE
Set the PWA App title to the MobileApplication's  'Application Name' property 

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#201]
As of today the <title> tag of the Applications' index.html  is always set to 'Ionic App'
This should be set to the value of the MobileApplication's 'Application Name' property.

**Comment by gregory-vorbe** [comment]
tested in **Convertigo EMS Studio 7.7.0_beta (build 04926-develop-7.7.0-beta)**

If possible, the name should be taken from the **MobileApplication** object and its property named **Application name**
If not possible, and the name is taken from the **Application** object, it needs to be clearly documented.

**Comment by nathalie-lammelin** [comment]
Please take care that `applicationName` property is empty by default, thus the title in `index.html` will be empty if property is not set.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05022-develop-7.7.0-beta)**

- If **Application name** property is empty, the tab name in Chrome is the URL.
