### ISSUE TITLE
SmtpStep failed with "no object DCH for MIME"

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#202]
The qualif project and other failed to execute with the following runtime error:

**javax.activation.UnsupportedDataTypeException: no object DCH for MIME type multipart/mixed;**

This look like this error : https://stackoverflow.com/questions/21856211/javax-activation-unsupporteddatatypeexception-no-object-dch-for-mime-type-multi

**Comment by nicolas-albert** [comment]
Must be backported to 7.6.5

**Comment by gregory-vorbe** [comment]
This is not working when an attachment is set in **Attachments** property :
[testSMTP.car.zip](https://github.com/convertigo/convertigo/files/3779248/testSMTP.car.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05906-hotfix-7.6.5-7.6.5-beta)**
