### ISSUE TITLE
PopoverAction "Css Class" property can not be set

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#205]
"Css Class" property of a Popover component is alway null in function **actionBeans.PopoverAction(...., cssClass: null, ....)**

**Comment by nathalie-lammelin** [comment]
If the property is **not set** it will generate :  `..., cssClass: null, ...`
You **can** set the property to a comma seperated list of class names `pop1,pop2`. It will generate :
```
<button class="class1570463687658" type="button" ion-button (tap)="resolveError(actionBeans.PopoverAction(this,merge(merge({},{tplVersion: '7.6.0.5', data: {user:'user1', age:35}, cssClass: 'pop1, pop2', showBackdrop: true, page: 'issue205.MobileApplication.Application.Page1', enableBackdropDismiss: true, event: (event == undefined ? $event : event)}), {stack:{root: {scope:{}, in:{}, out:$event}}}),{}, $event))">
popover page1
</button>
```

**Comment by gregory-vorbe** [comment]
My bad.  I was not looking in the correct PopOver component.
I confirm that setting one or more classes to the property correctly generates the code.
