### ISSUE TITLE
CouchDB server Databases Transaction : add query parameters

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#206]
The **_all_dbs** request can be use with query parameters.
We have to map them to our **GetServerDatabasesTransaction** properties.

See https://docs.couchdb.org/en/stable/api/server/common.html#all-dbs

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 04926-develop-7.7.0-beta)**

**Comment by gregory-vorbe** [comment]
When right-clicking the transaction, the menu **Add variables for dynamic properties** does not show off.
