### ISSUE TITLE
Multivalued variable values are <null> at project loading

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#21]
Create a sequence:
* add one single-valued variable and set a default value
* add one multi-valued variable and set a default value
* add an inputVar steps (output mode set to true)

Execute the sequence : the result is OK for both variables.
Reload project an execute the sequence: the result is KO : multivalued variable is not present (null)

Values are correctly saved in .yaml, but incorrectly loaded from .yaml into bean.

**Comment by nicolas-albert** [comment]
The YAML unshrinks to:

```
<property isNull="true" name="value">
    <xmlizable classname="com.twinsoft.convertigo.beans.common.XMLVector">
        <com.twinsoft.convertigo.beans.common.XMLVector>
            <java.lang.String value="m1"/>
            <java.lang.String value="m2"/>
        </com.twinsoft.convertigo.beans.common.XMLVector>
    </xmlizable>
</property>
```

The **isNull** must be **false** in this case (ok if changed by hand), I have to handle this.

**Comment by nathalie-lammelin** [comment]
Tested: OK

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03052-develop-7.6.0-beta)**
