### ISSUE TITLE
Review boolean properties in pseudo-beans description file (ion_objects.json)

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#214]
A **boolean** property must have a **default value** set : `"value": "false"` **or** `"value": "true"`
Possible values must not include the `false (not set)` entry : `"values": ["false", "true"]`

**Comment by nathalie-lammelin** [comment]
Following properties of pseudo-beans or pseudo-actions have been fixed : 
- Tabs : `TabsHighlight`

- ModalAction: `blockWhileDisplayed`, `showBackdrop`, `enableBackdropDismiss`
- PopoverAction: `showBackdrop`, `enableBackdropDismiss`
- ToastAction: `showCloseButton`, `dismissOnPageChange`
- CalendarPickerAction: `canBackwardsSelected`, `closeIcon`, `doneIcon`
- FullSyncViewAction: `reduce`
- ActionSheetAction: `androidEnableCancelButton`, `winphoneEnableCancelButton`, `destructiveButtonLast`
- CameraAction: `correctOrientation`, `saveToPhotoAlbum`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05284-develop-7.7.0-beta)**
