### ISSUE TITLE
Add a new i18n property for Text

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#217]
Add a right click action on page or application, to:
- Look for all Text beans with `value` in **TXT** mode and with property `i18n` set to `true`.
- Generate `text_key/text_value` pairs (which does not exist) in `<lang>`.json.
  key is equals to normalization of the text value, up to 40 characters

At html code generation:
Replace `value` in Html with `{{ text_key | translate }}`.

Default translation is based on **`en`** language.
To enable the i18n feature for the browser default language, edit app class and **uncomment** code if it is not: `// translate.use(translate.getBrowserLang());`

**Comment by opicciotto** [comment]
I would say that the action should set the i18n property to true for all TextBeans in TXT mode and do not perform any action if the property is already found to be true.

**Comment by nathalie-lammelin** [comment]
> I would say that the action should set the i18n property to true for all TextBeans in TXT mode and do not perform any action if the property is already found to be true.

After discussion, we should allow cases where Text must not be translated.
The property will be set to `true `by default, it will be up to the developer to choose.

**Comment by nathalie-lammelin** [comment]
Here is a project working with last build [05230](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-05230-develop-7.7.0-beta/) and using last _tpl `7.7.0 (v7.7.0.5)` : 
[issue217.zip](https://github.com/convertigo/convertigo/files/3734995/issue217.zip)

**Comment by nathalie-lammelin** [comment]
at [82f3887](https://github.com/convertigo/convertigo/commit/82f3887ab27054af3792e7092c36cdeacf345b41) : Made changes for menu (auto items): needs _tpl **7.7.0.6**

**Comment by opicciotto** [comment]
We should automatically enable translate service in the app.component.ts 👍 

```
 platform.ready().then(() => {
            statusBar.styleDefault();
            /**
             * Then we finalize initialization
             */
            this.c8o.finalizeInit().then(()=>{
                this.resetImageCache();
                /*Begin_c8o_AppInitialization*/
                /* Uncomment the following lines to enable the i18n feature.
                 * You should add a json per language in the assets/i18n folder. */
                 translate.setDefaultLang('en');
                 translate.use(translate.getBrowserLang());
                
                /* Uncomment the following lines to enable the custom status bar color. */
                // statusBar.overlaysWebView(false);
                // statusBar.backgroundColorByHexString("#000000");
                // statusBar.styleBlackOpaque();
			/*End_c8o_AppInitialization*/
            });

```

Do we ask with a dialog bow to the user if he wants to enable it or do we tell him to edit its application class to uncomment lines ?

**Comment by opicciotto** [comment]
Also, Automatic Google API  Translation creates UTF8 Chars in the JSON file 👍
ex 👍 

` "Want_to_host_this_on_your_server_or_clou": "Voulez-vous hÃ©berger cela sur votre serveur ou votre cloud?",
`

**Comment by nathalie-lammelin** [comment]
Close: reopen if needed

**Comment by nathalie-lammelin** [comment]
Does not work for 
`
<?xml version="1.0" encoding="ISO-8859-1"?><convertigo-clipboard>
    <mobilecomponent classname="com.twinsoft.convertigo.beans.mobile.components.UIText" priority="1574779136079" version="7.7.0.m006">
        <property name="comment">
            <java.lang.String value=""/>
        </property>
        <property name="i18n">
            <java.lang.Boolean value="true"/>
        </property>
        <property name="isEnabled">
            <java.lang.Boolean value="true"/>
        </property>
        <property name="name">
            <java.lang.String value="Text"/>
        </property>
        <property name="textValue">
            <xmlizable classname="com.twinsoft.convertigo.beans.mobile.components.MobileSmartSourceType">
                <MobileSmartSourceType>plain:07&#176;25'30"E</MobileSmartSourceType>
            </xmlizable>
        </property>
        <dnd>
            <project name="RadioExplorer"/>
            <mobileapplication name="MobileApplication"/>
            <application name="Application"/>
        </dnd>
    </mobilecomponent>
</convertigo-clipboard>
`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06146-develop-7.7.0-beta)**
