### ISSUE TITLE
Implement a  Database revision number for FullSync

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#22]
When we use a full sync database, clients have to be sure that the database on the server is not reset. Otherwise, all documents held locally in the client database will be pushed back to the server.  To prevent this we implement a Database revision number.

This number is automatically updated each time a RESET transaction is executed on the server.  The revision number is held in the _design/c8o  Design document.

When the client replicates the database, we first have to see the server _design/c8o revision number and compare it to the local _design/c8o. If they do not match, the client will automatically perform a RESET on the local database before syncing, resulting in a clean client database.

This process is to be done automatically by the SDKs.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03756-7.6.0-rc1)**

 * New ~c8oDbVersion entry in _design/c8o

**Comment by gregory-vorbe** [comment]
The **Add variables for dynamic properties** menu when right-clicking the transaction does not show off.
