### ISSUE TITLE
Using twice the same SharedComponent in a Page duplicates its action declarations

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#221]
Backport 'Duplicates' fixes from #191

**Comment by nathalie-lammelin** [comment]
Project for test : [issue221.zip](https://github.com/convertigo/convertigo/files/3712719/issue221.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05366-hotfix-7.6.5-7.6.5-beta)**

- Tested with issue221.car
