### ISSUE TITLE
Mobile Builder viewer can affect same Node.JS port for parallel build

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#222]
Open 2 MB viewer at the same time, they will listen at the same port (8100).
If you wait the first to be open, the second will be 8101.
We have to "reserve" port from other viewers.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05275-hotfix-7.6.5-7.6.5-beta)**
