### ISSUE TITLE
Bean Camera not working any more in web browser

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#225]
[debug] [MB] CameraAction : 
StaticInjectorError(AppModule)[Camera]: 
  StaticInjectorError(Platform: core)[Camera]: 
    NullInjectorError: No provider for Camera!

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 05204-develop-7.7.0-beta)**
