### ISSUE TITLE
IonicConferenceApp sample project does not work as intended

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#228]
Sample is working well using `tpl_7_5_2` and `tpl_7_5_3`

Since `tpl_7_5_4` have some trouble with the loading controler which does not dismiss: app is blocked.
 1 - On the **Schedule** page click on the first conference "Migrating to Ionic2"
The **SessionDetail** page is pushed but the loading controler is never dismissed
Same thing if you click on speaker from the **SpeakerList** page
 2 - Some `CustomAction`s have `page.call(...)` in code
Note that the **call** signature has changed (since `caf 1.1.7/sdk 3.0.0` for `tpl_7_6_0`) adding a new 'noLoading' parameter

**Using `tpl_7_6_5`**
it's ok except for the click on 'About...' of a speaker.
```
Error: Uncaught (in promise): TypeError: Cannot convert object to primitive value
TypeError: Cannot convert object to primitive value
    at eval (C:/Dev/eclipse-2019-06/runtime-HotFix-765/IonicConferenceApp/_private/ionic/node_modules/c8ocaf/src/caf/convertigo.base.ts:146:62)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (C:/Dev/eclipse-2019-06/runtime-HotFix-765/IonicConferenceApp/_private/ionic/node_modules/@angular/core/esm5/core.js:4981:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (C:/Dev/eclipse-2019-06/runtime-HotFix-765/IonicConferenceApp/_private/ionic/node_modules/@angular/core/esm5/core.js:4972:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at http://localhost:8100/build/polyfills.js:3:20273
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (C:/Dev/eclipse-2019-06/runtime-HotFix-765/IonicConferenceApp/_private/ionic/node_modules/@angular/core/esm5/core.js:4972:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)
    at IDBRequest.v (http://localhost:8100/build/polyfills.js:2:27893)

```
debugging code, the trouble comes from 
```
    C8oFullSyncCbl.prototype.handleGetDocumentRequest = function (fullSyncDatabaseName, docid, parameters) {
        var fullSyncDatabase = null;
        var dictDoc = {};
        var param;
        param = parameters["attachments"] ? { attachments: true } : {};
        parameters["binary"] ? param["binary"] = true : {};
        fullSyncDatabase = this.getOrCreateFullSyncDatabase(fullSyncDatabaseName);
        return new Promise(function (resolve, reject) {
            fullSyncDatabase.getdatabase.get(docid, param).then(function (document) {
                var e_1, _a;
                if (document != null) {
                    dictDoc = document;
                    var attachments = document[C8oFullSync.FULL_SYNC__ATTACHMENTS];
                    if (attachments != null) {
                        try {
                            for (var attachments_1 = __values(attachments), attachments_1_1 = attachments_1.next(); !attachments_1_1.done; attachments_1_1 = attachments_1.next()) {
                                var attachmentName = attachments_1_1.value;
                                var url = attachments.url;
                                var attachmentDesc = attachments[attachmentName];
                                attachmentDesc[C8oFullSyncCbl.ATTACHMENT_PROPERTY_KEY_CONTENT_URL] = url.toString();
                                var dictAny = {};
                                dictAny[attachmentName] = attachmentDesc;
                                dictDoc[C8oFullSyncCbl.FULL_SYNC__ATTACHMENTS] = dictAny;
                            }
                        }
                        catch (e_1_1) { e_1 = { error: e_1_1 }; }
                        finally {
                            try {
                                if (attachments_1_1 && !attachments_1_1.done && (_a = attachments_1.return)) _a.call(attachments_1);
                            }
                            finally { if (e_1) throw e_1.error; }
                        }
                    }
                }
                else {
                    reject(new C8oRessourceNotFoundException((C8oExceptionMessage.ressourceNotFound("requested document \"" + docid + "\""))));
                }
                if (dictDoc === null) {
                    dictDoc = {};
                }
                resolve(dictDoc);
            })
                .catch(function (error) {
                reject(error);
            });
        });
    };

```
the vars `attachmentName, url, attachmentDesc` are all undefined.
the code `url.toString()` make the exception to be thrown

**Comment by nicolas-albert** [comment]
Who will handle this issue ?
@CharlesGrimont I imagine you cannot.

**Comment by nathalie-lammelin** [comment]
Postponed from milestone `7.6.5` to milestone `7.7.0`

**Comment by nathalie-lammelin** [comment]
Using **tpl_7_7_0** (version 7.7.0.**13**) : it's ok except for the click on 'About...' of a speaker.
`
(146.058) Error occured when calling fs://conferenceapp.get#speakerDet:Error: Failed to process the fullsync request
    at new C8oException (http://localhost:8100/build/vendor.js:75102:28)
    at http://localhost:8100/build/vendor.js:78002:40
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5135:33)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
    at r.run (http://localhost:8100/build/polyfills.js:3:10143)
    at http://localhost:8100/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5126:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
`

**Comment by nicolas-albert** [comment]
![i228-debug](https://user-images.githubusercontent.com/225279/70072194-cf2a1080-15f6-11ea-850c-e26c7e711823.png)

This is for @CharlesGrimont .
The error is thrown at the blue line : **url.toString()** -> url is undefined.
This is also why the icon doesn't work on the speaker list.
But if I use a **FsImage**, I have the avatar.
The **CallFullSync** action failed with a simple **.get** on a document with an attachment.

**Comment by CharlesGrimont** [comment]
https://github.com/convertigo/c8osdk-angular-caf/issues/23

This fix preview of images in the whole app except when entering to page speakerDetails

**Comment by CharlesGrimont** [comment]
seems to be resolved by using both new sdk and caf,
However we will wait until npmjs bug will be corrected to test it correctly

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**
Demo project is shipped with TPL_7.5.2 causing Avatar image not displaying.
It is working when changing to TPL_7.7.0.
IonicConferenceApp should be updated to TPL 7.7.0 in Studio

**Comment by gregory-vorbe** [comment]
What is the button "Map" supposed to display?

**Comment by CharlesGrimont** [comment]
@gregory-vorbe just a map if I remember well

**Comment by gregory-vorbe** [comment]
There are MapMarkers defined under the Map but they are not showing because the  **Icon** property is set to "**false**" instead of "**not set**":
![image](https://user-images.githubusercontent.com/1685373/71905666-e5cd0580-3168-11ea-9345-bcd80752a3eb.png)

Who can change the project to use TPL_7.7.0 and fix **Icon** property?

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : I can do it if needed ;)

**Comment by gregory-vorbe** [comment]
Yes, please!
Thx

**Comment by gregory-vorbe** [comment]
OK **Convertigo EMS Studio 7.7.0_beta (build 06399-develop-7.7.0-beta)**
OK on **Android Phone** (local build)
