### ISSUE TITLE
Need to alert user for packages reinstallation when changing MB template

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#231]

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05275-hotfix-7.6.5-7.6.5-beta)**

![image](https://user-images.githubusercontent.com/1685373/67098781-14b48a80-f1bd-11e9-934d-912db6c4e39a.png)

![image](https://user-images.githubusercontent.com/1685373/67098787-1aaa6b80-f1bd-11e9-9e50-9a5958686730.png)
