### ISSUE TITLE
Source Picker still displaying "WAITING FOR SCHEMAS GENERATION...."

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#235]
Happens now frequently,  in sequencer when we source from from one step to an other, the source picker popup display no data and we have this message displayed :

![image](https://user-images.githubusercontent.com/1043988/67657938-7bbe0600-f958-11e9-9b67-29905351ff18.png)

No error is shown in console, nor in the engine.log

Also the Source picker view remain empty when we select "Show in picker..." menu on a step.

**Comment by nathalie-lammelin** [comment]
@opicciotto : do you manage to generate your project schema through the schema view ?
Then use source picker...

**Comment by nathalie-lammelin** [comment]
Reopen if needed

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**
