### ISSUE TITLE
It would be nice to have defaultHistory property on Page

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#236]
defaultHistory allow us to get a default value into page dynamic list

The defaultHistory property takes an array of strings. For example, setting the history of the detail page to the list page where the name is list:

@IonicPage({
  name: 'detail-page',
  segment: 'detail/:id',
  defaultHistory: ['list']
})

cf: https://ionicframework.com/docs/v3/api/navigation/IonicPage/

**Comment by nathalie-lammelin** [comment]
A test project: [issue236.zip](https://github.com/convertigo/convertigo/files/3783353/issue236.zip)
- Import the project and double click on` Page2` to launch the app.
- Then from the `Page2` (displayed) you should see a `back` button which will navigate back to `Page1` and then to `Page` (`default history` set for `Page2`).
- Now, from `Page` click on the `Push to Page2` button. Then from `Page2` the `back` button will navigate back to `Page` (real history).

**Comment by nathalie-lammelin** [comment]
> A test project: [issue236.zip](https://github.com/convertigo/convertigo/files/3783691/issue236.zip)
> Work with a tpl_7_7_0 with 7.7.0.**8** version !
> .....

Not working with `Root page`...

**Comment by nathalie-lammelin** [comment]
Ionic `defaultHistory` is not working as intended => postponed.

=> **Do not include in 7.7.0 changelog !**
