### ISSUE TITLE
bean Post data post additional data 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#237]
when you post a data using bean post data, 

"tplVersion":"7.7.0.7","noLoading":false

are also stored

**Comment by CharlesGrimont** [comment]
![erreur#237](https://user-images.githubusercontent.com/11558728/67754357-9c5c8d80-fa36-11e9-99cc-649c43605e5d.png)

Can't build since this commit

**Comment by opicciotto** [comment]
Is this used in C8OForms ? Can @CharlesGrimont test if this is ok now ?

**Comment by CharlesGrimont** [comment]
Bug still there, at least with post data and merge policy...

You can see there a demo that reproduce this bug

[bugPostFSWrong.zip](https://github.com/convertigo/convertigo/files/4039947/bugPostFSWrong.zip)

**Comment by gregory-vorbe** [comment]
Are "actionName" and "actionFunction" keys the extra data in the demo project?

**Comment by CharlesGrimont** [comment]
Yes and stack in case of multiple actions within the event

**Comment by CharlesGrimont** [comment]
The multiple element case can be fixed by editing [FullSyncPostAction.ts](https://github.com/convertigo/convertigo/blob/develop/engine/src/com/twinsoft/convertigo/beans/mobile/components/dynamic/actionbeans/FullSyncPostAction.ts) inseting these two lines ...

`
delete props["actionName"];
delete props["actionFunction"];`

I don't see any risk of regression by doing this, however i don't know if deleting stack is risky ..
(for the signle element case).

Also, I do not know if the structural change that introduced this regression could introduce it for other beans...

[Here is a reproduction project](https://github.com/convertigo/convertigo/files/4045725/bugPostFSWrong.zip)

Any one has an idea ?

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0 (build 06496-release-7.7.0-7.7.0)**
