### ISSUE TITLE
FS transaction cannot post/bulk over a deleted document with an override policy

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#239]
To reproduce, post a new doc, remove the doc, post again with override : update conflict.

This is because the current code retrieve the _rev of the deleted document and CouchDB doesn't like it.

**Comment by nicolas-albert** [comment]
[issue239.zip](https://github.com/convertigo/convertigo/files/3793997/issue239.zip)
Project to reproduce, issue with **WithBulkMerge** and **WithPostMerge**.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05992-hotfix-7.6.5-7.6.5-beta)** and **Convertigo EMS Server 7.6.5_beta (build 05992-hotfix-7.6.5-7.6.5-beta)**
