### ISSUE TITLE
Call Step generates invalid call data when a variable sources a self closing tag

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#24]
Looking for child nodes on a self closing tag (`<tag />`) ends with an **empty** NodeList as variable value.

A **non** self closing tag (`<tag></tag>`) ends with a **non** empty NodeList which contains one Text node with an empty string value.

**Comment by nathalie-lammelin** [comment]
7.5 `.zip` project to be renamed to `.car`
[issue24.zip](https://github.com/convertigo/convertigo/files/3191377/issue24.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03000-develop-7.6.0-beta)**
