### ISSUE TITLE
Add a new lib_UserManager library

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#241]
This library  handles  all login and user management for Convertigo projects.  It features 

- User / Password login using salted passwords
- Google OAuth Sign in
- LinkediN OAuth Sign in
- Azure AD OAuth Sign in

The library  can be used in conjunction with the lib_OAuth library. 

The library also provides a Shared Component   providing the UI. The shared component can be dropped in any project to provide a signin feature.

**Comment by gregory-vorbe** [comment]
Feature present in **Convertigo EMS Studio 7.7.0 (build 06456-release-7.7.0-7.7.0)**
Can not be easily tested. Needs providers account.

 - Added readme.md
