### ISSUE TITLE
Upgrade templates to Ionic 3.9.9

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#242]
related with #150

**Comment by opicciotto** [comment]
https://github.com/ionic-team/ionic-v3/blob/v3.9.9/CHANGELOG.md

**Comment by CharlesGrimont** [comment]
done in 7.7.**10**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06082-develop-7.7.0-beta)**
