### ISSUE TITLE
Set header Cache-Control to max-age=X for static resources

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#243]
When Convertigo serve a static file, the Cache-Control is 'public' then the browser can keep the file without doing request for an unknow time.
We can add a new Engine Properties to set the time in second for the max-age.
Default to 10 sec seems good.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05983-hotfix-7.6.5-7.6.5-beta)**
