### ISSUE TITLE
Set CORS response headers (Access-Control-) also for error responses

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#244]
When a web request failed due to internal error (key expired, project not found and certainly others), the response isn't showed in the Chrome debug or to the SDK because of the browser CORS policy.
For thoses cases, the global CORS policy of the Convertigo serveur should be used (default =Origin).

Sample with CORS response:
`curl -v 'https://qualif-sdk.convertigo.net/convertigo/projects/ClientSDKtesting/.json' -H 'Origin: http://localhost:9876' --data '__sequence=LoginTesting&__uuid=web-a3863169-baaf-4556-afe9-36a2bddb4c8c&__removeNamespaces=true'`

Sample with error and no CORS response:
`curl -v 'https://qualif-sdk.convertigo.net/convertigo/projects/ClientSDKtestingNO/.json' -H 'Origin: http://localhost:9876' --data '__sequence=LoginTesting&__uuid=web-a3863169-baaf-4556-afe9-36a2bddb4c8c&__removeNamespaces=true'`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05983-hotfix-7.6.5-7.6.5-beta)**
