### ISSUE TITLE
Need a new callSequence property that disable auto login for this sequence

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#245]
In some cases, for example in case of sequence that removes session we don't want SDK to autologin for this sequence, 

so we need to set a flag especially for this sequence that disable autologin

so you have to pass in parameters  "__disableAutologin" : true.

Available from SDK 3.0.2

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06399-develop-7.7.0-beta)**
