### ISSUE TITLE
Some beans not working any more with TPL 7.7.0.10

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#246]
For some beans, we need to know if actual template version is greater than another
since we use `string.localcompare` to do it it's not working anymore in some case such as:

`"7.6.0.2" < "7.6.0.10" => false`
so we need to add a new comparison function to https://github.com/convertigo/c8osdk-angular-caf to do it.

Beans that might be concerned by this issue are:
* CallFullSyncAction
* CallSequenceAction
* FullSyncDeleteAction
* FullSyncDeleteAttachmentAction
* FullSyncGetAction
* FullSyncPostAction
* FullSyncPutAttachmentAction
* FullSyncViewAction
* ModalAction
* PopoverAction
* PushPageAction
* RootPageAction

**Comment by opicciotto** [comment]
No tested unitarly  but as Projects like ionicConferenceApp or C8oSignup are working perfectly with TPL V 7.7.0.16  we can assume this is tested OK.
