### ISSUE TITLE
Signature component generates a wrong base64 with some background colors

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#247]
The function that affects value to signature component, is ` .toDataURL('image/jpeg', 0.5); `

The default background-color is  `rgba(0,0,0,0)` (transparent black) that don't allow to export image as base64 ...

Documentation said Use a non-transparent color e.g. 'white' or 'rgb(255,255,255)' (opaque white) if you'd like to save signatures as JPEG images.

We maight change it to png to allow export with any colors

**Comment by nathalie-lammelin** [comment]
For ChangeLog:
**Breaking change**: signature now generate PNG data instead of JPEG data

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06010-develop-7.7.0-beta)**

- Bean documentation needs to be updated to state that the default output is a Base64 PNG of the form "data:image/png;base64,\<base64>"
- Documentation would also need some hints on how to retrieve the Base64 value.
