### ISSUE TITLE
Inject TranslateService in page.tpl and app.tpl

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#248]
In order to be able to use a 

`translate.instant('any_i18n_KEY')
`
In any Action bean or Component property  to handle i18N, we must inject a TranslateService as translate in our page and app components.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06146-develop-7.7.0-beta)**
