### ISSUE TITLE
Build Error on Centos 7

### ISSUE THREAD

**Issue by sanyaade-iot** [convertigo/convertigo#25]
Hi Everybody,

I tried to build convertigo code on Centos 7 but I got build error messages for CSVParserBuilder
Please see below:-

> ` symbol:   class CSVParserBuilder
  location: class ReadCSVStep
/home/sanyaade/Compilers/eclipse/workspace/convertigo-7.5.2/engine/src/com/twinsoft/convertigo/beans/steps/ReadCSVStep.java:145: error: cannot find symbol
                return new CSVReaderBuilder(reader).withCSVParser(new CSVParserBuilder().withSeparator(separator.charAt(0)).build()).build();
                           ^
  symbol:   class CSVReaderBuilder
  location: class ReadCSVStep
/home/sanyaade/Compilers/eclipse/workspace/convertigo-7.5.2/engine/src/com/twinsoft/convertigo/beans/steps/ReadCSVStep.java:265: error: cannot find symbol
                                        CSVReader csvReader = getCSVReader(reader);
                                        ^
  symbol:   class CSVReader
  location: class ReadCSVStep
/home/sanyaade/Compilers/eclipse/workspace/convertigo-7.5.2/engine/src/com/twinsoft/convertigo/engine/util/JAXBUtils.java:83: error: cannot access ErrorListener
                XJCListener l = new XJCListener() {
                                ^
  class file for com.sun.xml.bind.api.ErrorListener not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
18 errors
:engine:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':engine:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.759 secs
[sanyaade@skillmender convertigo-7.5.2]$ 
`

![image](https://user-images.githubusercontent.com/7230207/46915377-c3b6f880-cfa2-11e8-8e81-60c8b34d4885.png)

Please help!

Hear from you soon!

God blesses!!!

Best regards,
Sanyaade

**Comment by opicciotto** [comment]
Unfortunately, we cannot support build issues for non SLA customers.
