### ISSUE TITLE
Add some missing properties for CouchDB transactions for CouchDB 2.x server

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#252]
Backport of #206 and also :
Add 'keys' query parameter for getView and allDocs transactions,
add query to putDatabase transaction,
handle CDB 2.x config, stats, and restart urls,
handle config response,
handle filter parameter for replication.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05983-hotfix-7.6.5-7.6.5-beta)**
