### ISSUE TITLE
Android localbuild application cannot reach http://192.168.x.x

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#253]
If we set a Mobile Application endpoint to our local Studio over the local network in HTTP, the application cannot do any HTTP request.
The application **android:usesCleartextTraffic="true"** must be set in the Cordova config.xml in order to work.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05958-hotfix-7.6.5-7.6.5-beta)**

 * No migration code for older projects, only available for newly created Mobile Builder projects.
