### ISSUE TITLE
TestPlatform differs mobile local revision for FlashUpdate to prevent TestPlatform's hanging

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#254]
If a Mobile Application project change (new deployment) and the TestPlatform is requested, it can hang during the FlashUpdate file prepare (few seconds on slow drives).

The idea is to call a new service to get the Local Revision that handle the FlashUpdate prepare file.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05958-hotfix-7.6.5-7.6.5-beta)**
