### ISSUE TITLE
Purge transaction over a CouchDB Connector create a 'weird' document

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#256]
This not happen using a Fullsync connector.
Purge transaction over a CouchDB Connector, that remove deleted documents, create a 'weird' document :
```
{
"_id": "a9e7c83740b7175af15046cc70144866",
"_rev": "1-82be81a81a6064a6283b9b280004ab30",
"error": "not_found",
"reason": "missing",
"~c8oDbVersion": "k34auar8"
}
```
Before trying to update the DbVersion of the C8o design document, we have to check if it exists.

**Comment by nicolas-albert** [comment]
[issue256.zip](https://github.com/convertigo/convertigo/files/3864444/issue256.zip)

Project to reproduce, just call the **MakeBug** sequence and you will see the 'weird' document in the allDocs output.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Server 7.6.5_beta (build 05906-hotfix-7.6.5-7.6.5-beta)**

- Tested with build 05851 to reproduce issue.
