### ISSUE TITLE
Where's lib source repository?

### ISSUE THREAD

**Issue by jianan789** [convertigo/convertigo#257]
compileFlat 'com.convertigo.lib:ctgclient:2010.06.14'
	compileFlat 'com.convertigo.lib:httpclientAuthHelper:2014.12.23'
	compileFlat 'com.convertigo.lib:mozilla-interfaces:1.9.0.17'
	compileFlat 'com.convertigo.lib:ojdbc7:12.1.0.2'
	compileFlat 'com.convertigo.lib:soapui-xmlbeans:3.5.1'
	compileFlat 'com.convertigo.lib:soapui:3.5.1'

**Comment by nicolas-albert** [comment]
In our repository :
```
maven {
	url "https://m2.convertigo.com"
}
```

**Comment by jianan789** [comment]
Thanks, Only jar files, no source code？

**Comment by opicciotto** [comment]
Hello, 
What are are you trying to achieve ? are you interested for contributing for a PR ?

**Comment by jianan789** [comment]
> Hello,
> What are are you trying to achieve ? are you interested for contributing for a PR ?

Thanks,
 I just want to see how “CouchDbManager” is implemented.(in convertigo-provider-couchdb.jar）
And why CouchDB is the mainstream database for Convertigo?
Is any details about fullsync?
