### ISSUE TITLE
Add new actionName, actionFunction properties for Action

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#259]
Action properties (available through `props` parameter) :
- `tplVersion` : the template project version
- `actionName` : the action name (bean name: `MyCustom1, Log1, InvokeSharedAction,...`)
- `actionFunction`: the action function name (`CTSxxx, STSxxx, LogAction,...`)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.5_beta (build 05958-hotfix-7.6.5-7.6.5-beta)**
