### ISSUE TITLE
[MB] CalendarPickerAction isn't working as expected

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#26]
For `defaultTitle` (Day Title) and `defaultSubtitle` (Subtitle) **string** properties, user is able to choose `not set` (false). The calendar diplays `false` and should not.

- OR the implementation of the action (CalendarPickerAction.ts) should ignore those properties (when value equals false)
- OR the description of the action (ion_objects.json) should be modified by adding `values:[true]`

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 7.6.0_beta (build 03079-develop-7.6.0-beta)**:

 - No '**not set**' TX value available for: **Day Title** and **Subtitle**.
 - No link to doc reference of the original component used.
 - class CalendarResult layout broken:
 ![image](https://user-images.githubusercontent.com/1685373/58098014-f7ad6880-7bd8-11e9-96d2-b0fc35847087.png)

**Comment by nathalie-lammelin** [comment]
TX mode: `Day Title` and `Subtitle` properties must have a value (default is empty string), thus 'not set' is not available.
Documentation has been fixed, a link to doc added.

**Comment by gregory-vorbe** [comment]
I thought **'not set'** was the default property value of a component.
In calendar component, **'Title'** has default property value to **'not set'** and it displays Title as **'CALENDAR'** (same behaviour for 'Close label' and 'Done label'...)

 - Typos in **'Disable weeks days'** property and doc : Should be **'Disable week days'** without 's' to 'week'
 - Missing **'monthPickerFormat'** to set Months display (in French, for example when format is MMM).

**Comment by gregory-vorbe** [comment]
Months localization is set by 'moment' dependency and set by:

```
Localization
your root module

import { NgModule, LOCALE_ID } from '@angular/core';
...
 
@NgModule({
  ...
  providers: [{ provide: LOCALE_ID, useValue: "zh-CN" }]
})
```
==> https://www.npmjs.com/package/ion2-calendar#localization

**Comment by gregory-vorbe** [comment]
I made a mistake, I think the property **monthPickerFormat** is only available in "Components Mode" of this plugin and we are using the "Modal mode" in our bean.

**Comment by nathalie-lammelin** [comment]
We are using the "Components Mode" using `CalendarModule` of `ion2-calendar`.
Please close issue if its ok for you or add clarification and/or a way to reproduce a bad behavior.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03786-release-7.6.0-7.6.0)**
