### ISSUE TITLE
Use a workaround for Lazy loading & Chrome debugging issue

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#261]
See [https://forum.ionicframework.com/t/debugger-breakpoint-not-correct-in-chrome-mapping-wrong/109950](https://forum.ionicframework.com/t/debugger-breakpoint-not-correct-in-chrome-mapping-wrong/109950)

**Comment by nathalie-lammelin** [comment]
Tested with @Avrahqedivra on a customer project : OK.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06367-develop-7.7.0-beta)**
 - D+ mode not visible in Mobile Debug Tab, only in Chrome browser Debugger.
