### ISSUE TITLE
Add new changeDetectionStrategy property for Page bean

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#266]
Use in component decorator
`@Component({
selector: 'page-page1', 
templateUrl: 'page1.html', 
changeDetection: ChangeDetectionStrategy.OnPush})
`

Helps fix the `ExpressionChangedAfterItHasBeenCheckedError `errors (which do not occurs in Production mode)

**Comment by nathalie-lammelin** [comment]
Project for test (need a `_tpl_7_7_0` with version **`7.7.0.14`**) : [issue266.zip](https://github.com/convertigo/convertigo/files/3902099/issue266.zip)

* Import project in Studio and Launch app
  * From menu go to second page -> it generate errors (which you can close)
  * Go back to first root page -> it generates errors (which you can close)
The third grid row is causing the errors...
* Now, set the `Changes detection strategy` property of Page1 from `Default` to `OnPush`
  * From menu go to second page ->no error
  * Go back to first root page ->no error

These errors occur for any **non-production** build mode.
They make it possible to identify and correct a possible problem related to the page lifecycle.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06334-develop-7.7.0-beta)**
