### ISSUE TITLE
Upgrade to JxBrowser 7.3

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#267]
Replace JxBrowser 7.2 by 7.3 and make some adjustments.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06082-develop-7.7.0-beta)**

**Comment by nicolas-albert** [comment]
JxBrowser 7.4 released.
Change gradle to use it.
Have to fix #289 !
