### ISSUE TITLE
SampleMobileOffChat project does not work as intented since 7.6.4

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#268]
Login page does not work as intented.
Some `CustomAction`s must be updated since [#185](https://github.com/convertigo/convertigo/issues/185) has been fixed.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06146-develop-7.7.0-beta)**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06197-hotfix-7.6.6-7.6.6-beta)**
