### ISSUE TITLE
__body and Application/json header should automatically transmit JSON from Xpath Source

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#269]
Currently, if you want to pass a Json string to **__body** variable from a complex Step you have to create it manually using a intermediate Steps.
A nice new feature would be that the __body variable type is automatically rendered in Json when the transaction's header is **Application/json**

**Comment by nicolas-albert** [comment]
Project to reproduce (call the MakeJSON sequence).
[issue269.zip](https://github.com/convertigo/convertigo/files/3912213/issue269.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06138-develop-7.7.0-beta)**

- Supports **type** attribute (object, array,...)
- Supports **__contentType**
