### ISSUE TITLE
global_symbols.properties multiple write at startup and can lose symbols with multi-instance

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#272]
Issue seen with Kubernetes using the **Deployment** mode.
Multi replicate Pod starts at the same time with a shared workspace.
Each instances read/write the **global_symbols.properties** at the same time, corrupt the file and load invalid symbols.
This file should be only read but not write at the Engine startup.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06197-hotfix-7.6.6-7.6.6-beta)**
