### ISSUE TITLE
Premature end of Sequence if calls done on the same Context at the same time

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#273]
Hard to reproduce but can happen if calls are made at the same time for the same session and the same contextName.
The ContextManager can create multiple Context for multiple Sequence. If once Sequence is terminated, subcontext are killed too, based on the contextID and do a premature end of sub-Sequence of other Sequences.

**Comment by opicciotto** [comment]
Top.. on peut essayer ?

Le jeu. 5 déc. 2019 à 17:10, Albert Nicolas <notifications@github.com> a
écrit :

**Comment by nicolas-albert** [comment]
Same fix tested with project on 7.7.0 → **OK**
