### ISSUE TITLE
Set Cookie HttpOnly and Secure (via Docker setting)

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#276]
Cookies come from Tomcat.
It should be set to not be read by the client JS cookie API by using the **HttpOnly** flag.
Also, Docker serves an HTTP connector but often accessible behind an HTTPS front. The **Secure** cookie flag should be used in this case to prevent usage of Cookies over HTTP.
Maybe the Docker image could enable **Secure** mode with an environment variable **COOKIE_SECURE=true**.

**Comment by gregory-vorbe** [comment]
OK in **docker pull convertigo/convertigo-ci:06223-hotfix-7.6.6-7.6.6-beta**
