### ISSUE TITLE
Global properties: cipher stored values for keys with .secret suffix

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#277]
Sometime, symbols store password.
This isn't nice to see them directly in the admin console, and they should be hidden and ciphered on save.
We should introduce an **Add Secret Symbol** button to add symbols with a **.secret** suffix. The engine will save them and load them using our cipher tool.

**Comment by gregory-vorbe** [comment]
Inputs are visible under the symbols table:
![image](https://user-images.githubusercontent.com/1685373/70801577-8a993480-1daf-11ea-8e88-9c9731c49704.png)

**Comment by gregory-vorbe** [comment]
Is it a wanted behaviour the symbol's name cannot be changed (disabled input)?
![image](https://user-images.githubusercontent.com/1685373/70801759-0c895d80-1db0-11ea-8c50-f8112a19ee35.png)

**Comment by nicolas-albert** [comment]
Yes, because the value is unknown at client side, the API cannot do this easily.
The new symbol should be created and the old deleted.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06214-hotfix-7.6.6-7.6.6-beta)**

- Good to know: You can use legacy Add button and create a symbol name with .secret appended at the end, this will create a ciphered and secret symbol
