### ISSUE TITLE
Password policy for administration console account

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#278]
Add a password check rule before adding or modifying a password on the administration for : roles and admin + testplatform accounts.

The rule is just a regex to match. The regex can be edited through an Engine property.

The default regex can be tested here : https://regex101.com/r/N5ftVr/1
```
^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])[\w~@#$%^&*+=`|{}:;!.?\"()\[\]-]{8,20}$
```

The password must respect: almost 1 lowercase, 1 uppercase, 1 digit and between 8-20 characters.

**Comment by gregory-vorbe** [comment]
**at least** not **almost**

![image](https://user-images.githubusercontent.com/1685373/70802813-c7b2f600-1db2-11ea-8852-0d7f0770b2f1.png)

**Comment by gregory-vorbe** [comment]
OK **Convertigo EMS Studio 7.6.6_beta (build 06214-hotfix-7.6.6-7.6.6-beta)**

But...

If you change the regular expression in the administration console, the message will not be accurate any more.
Maybe we should only warn the user that the password does not meet the policy requirements.

**Comment by nicolas-albert** [comment]
Already done.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06223-hotfix-7.6.6-7.6.6-beta)**

**Comment by gregory-vorbe** [comment]
OK (again) in **Convertigo EMS Studio 7.6.6_beta (build 06248-hotfix-7.6.6-7.6.6-beta)**
