### ISSUE TITLE
Dev Network link is borken in admin and TP

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#279]
Points to https://www.convertigo.com/developernetwork and goes to Convertigo home page.

![image](https://user-images.githubusercontent.com/1685373/70793279-3dab6300-1d9b-11ea-9b57-c5a552bf6ff3.png)

**Comment by nicolas-albert** [comment]
@opicciotto do you have an idea for a new href ?

**Comment by opicciotto** [comment]
Should go to 
http://www.convertigo.com/documentation/latest/

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06223-hotfix-7.6.6-7.6.6-beta)**
