### ISSUE TITLE
Strange entry in environment variables in Administration Console

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#282]
![image](https://user-images.githubusercontent.com/1685373/70794390-d642e280-1d9d-11ea-805f-046296d54891.png)

Name **=::**
Value  ::\

**Comment by nicolas-albert** [comment]
This variable exists on the Studio, maybe Eclipse launcher add this.
Can be seen in Help / About Studio / Installation Details :
```
*** System environment variables:
=::=::\
ALLUSERSPROFILE=C:\ProgramData
```
