### ISSUE TITLE
Review starting wizard for the new Convertigo Cloud

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#286]
Change wizard pages about PSC + trial.convertigo.net and write about the new Cloud trial.

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 7.7.0_beta (build 06334-develop-7.7.0-beta)**
Typo : **Convertigo Community suppprt**

![image](https://user-images.githubusercontent.com/1685373/71577584-0821ac00-2af5-11ea-8c6d-27a2d6f21df1.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06351-develop-7.7.0-beta)**
