### ISSUE TITLE
Add ngx-chips component for MB as a shared component

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#287]
demo: https://angular-mfppay.stackblitz.io/ 

plugin: https://github.com/Gbuomprisco/ngx-chips

**Comment by nathalie-lammelin** [comment]
Project with sample pages (for lib, not finished) working with tpl 7.7.0.**16** : [issue285_287.zip](https://github.com/convertigo/convertigo/files/4019960/issue285_287.zip)

**Comment by nathalie-lammelin** [comment]
#287 : Updated project on 08 January 2020 : [issue285_287.zip](https://github.com/convertigo/convertigo/files/4034715/issue285_287.zip)

**Comment by nathalie-lammelin** [comment]
#287 : Updated project on 10 January 2020 :  [issue285_287.zip](https://github.com/convertigo/convertigo/files/4046484/issue285_287.zip)

**Comment by nathalie-lammelin** [comment]
#287 : Updated project on 13 January 2020 : [issue285_287.zip](https://github.com/convertigo/convertigo/files/4053044/issue285_287.zip)

**Comment by CharlesGrimont** [comment]
version 2.1.0 of ngx-chips is not supporting build prod, however version "ngx-chips": "2.0.2" does 
cf: https://github.com/angular/angular-cli/issues/15852

**Comment by nathalie-lammelin** [comment]
Done: see [c8oprj-lib-extended-components](https://github.com/convertigo/c8oprj-lib-extended-components)
