### ISSUE TITLE
Update admin documentations link to the new doc

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#288]
Changing all **?** links of administration console from **document** to **documentation**. Like:

- https://www.convertigo.com/document/latest/operating-guide/using-convertigo-administration-console/
- https://www.convertigo.com/documentation/latest/operating-guide/using-convertigo-administration-console/

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.6_beta (build 06248-hotfix-7.6.6-7.6.6-beta)**
