### ISSUE TITLE
MacOS X Studio displays white pages for all JxBrowser components including Mobile Viewer Window

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#289]

**Comment by nicolas-albert** [comment]
I've contacted the JxBrowser support:

> As you may know, SWT works in JxBrowser 6 via the SWT-AWT bridge. Unfortunately, we didn't test the SWT-AWT bridge in JxBrowser 7. We are now working on a pure SWT implementation without a bridge. Most likely, the issue will be resolved once we implement pure SWT support in JxBrowser 7.

Switch back to the latest JxBrowser 6.x to fix Mac Studio.
