### ISSUE TITLE
Add a PostFind CDB/FS transaction for Mango Query

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#290]
CouchDB 2.x introduce the **POST {db}/_find** request to do a **Mango Query** : https://docs.couchdb.org/en/latest/api/database/find.html

Add this missing transaction.

Also, it can be nice to use JS for the Query that use extra parameters.

**Comment by nicolas-albert** [comment]
We have to add a way to create Index for speedup mango queries: https://docs.couchdb.org/en/2.3.1/api/database/find.html#db-index

The feature to create automatic index doesn't exist: https://github.com/apache/couchdb/issues/1671

**Comment by nicolas-albert** [comment]
[Conv290.zip](https://github.com/convertigo/convertigo/files/4039824/Conv290.zip)

Testing project, need retailStore project.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.0_beta (build 06447-develop-7.7.0-beta)**
 - Adding, renaming, deleting Json_Index is working correctly
 - Param selector can use complex syntax
