### ISSUE TITLE
Improve event catch/finally feature for actions

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#291]
The `catch/finally` feature is handled in action function.
It is executed twice for parallel actions (See #168)

=> We need to handle in the parent container event. Will be done for `NGX` projects **only**

**Comment by nathalie-lammelin** [comment]
Done for NGX only.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**
