### ISSUE TITLE
Attribute / jAttribute Steps does not show value

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#300]
Add the 'Default value' or 'Expression' or 'Source' for the Attribute / jAttribute Steps in the treeview:

![image](https://user-images.githubusercontent.com/1685373/72917732-ab589080-3d44-11ea-8d9b-c0da916b2063.png)

**Comment by nathalie-lammelin** [comment]
Test project : [issue300.zip](https://github.com/convertigo/convertigo/files/4107507/issue300.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06733-hotfix-7.7.1-7.7.1-beta)**

![image](https://user-images.githubusercontent.com/1685373/73939523-f13b5a00-48e9-11ea-9786-8498c2e585ac.png)
