### ISSUE TITLE
Update engine convertigo-provider-sap dependency to 7.6.6-SNAPSHOT

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#306]
[report of devus #5764](https://bitbucket.org/convertigo/convertigo-provider-sap/commits/f8f6fd12d46ae8dab3fa57d1b42242d7eec2d74d)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06733-hotfix-7.7.1-7.7.1-beta)**
