### ISSUE TITLE
Set the project compatibility version to the highest bean version used

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#307]
When a project is saved, the current Convertigo version is written to the yaml, like **↑convertigo: 7.6.0.m006**

An older Studio can open it again, except with the "product check version" property.

The idea here is to set the Convertigo version compatible with beans used in the project. At the save time, we can find the latest bean version used in the current project and use it.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06789-hotfix-7.7.1-7.7.1-beta)**
