### ISSUE TITLE
Update Template/Sample projects before 7.7.1 release

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#308]
Migration to minimal version, Check samples are still running ok

**Comment by nathalie-lammelin** [comment]
Templates updated at [06a0f91](https://github.com/convertigo/convertigo/commit/06a0f9149ed71327557b2f7450d58d567fd56861)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06789-hotfix-7.7.1-7.7.1-beta)**
