### ISSUE TITLE
Update Template/Sample projects before 7.9.0 release

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#309]
Migration to minimal version, Check samples are still running ok

**Comment by gregory-vorbe** [comment]
* Amazon_Lex lib still use 7.6.0 TPL
 * Can not import Sigfox lib, it uses the same project name as Amazon_LEX
 * lib_UserManager uses the 7.7.0 TPL version
 * Some project does not come from Github repo (sample_mobileRetailStore, HelloWorld, Offchat...) is it normal ?

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.0_beta (build 10075-develop-7.9.0-beta)**
