### ISSUE TITLE
customAction copy failed to copy complete code

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#310]
Here is original customAction code:

	/**
	 * Function keyPad
	 *   
	 * 
	 * @param page  , the current page
	 * @param props , the object which holds properties key-value pairs
	 * @param vars  , the object which holds variables key-value pairs
	 * @param event , the current event object
	 */
	CTS1580223604644(page: C8oPageBase, props, vars, event: any) : Promise<any> {
		return new Promise((resolve, reject) => {
		/*Begin_c8o_function:CTS1580223604644*/
		page.c8o.log.debug('[MB] '+ props.actionFunction +': '+ props.actionName);
		page.local.keys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", " ", " ", " ", " ", " ", " "];
		page.local.shuffle = function(o) {for(var j, x, i = o.length; i; j = Math.floor(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);return o};
		page.local.keys = page.local.shuffle(page.local.keys);
		delete page.local.shuffle;
		page.c8o.log.debug('page.local.keys: ' + page.local.keys);
		
		setTimeout(() => {
		    this[vars.setFocus].setFocus();
		    this.local.focusedInput = 'contract';
		}, 150);
	    resolve();
		/*End_c8o_function:CTS1580223604644*/
		});
	}

If I Copy/Paste customAction component to another project, the code of the new customAction is:

	/**
	 * Function keyPad
	 *   
	 * 
	 * @param page  , the current page
	 * @param props , the object which holds properties key-value pairs
	 * @param vars  , the object which holds variables key-value pairs
	 * @param event , the current event object
	 */
	CTS1580309646676(page: C8oPageBase, props, vars, event: any) : Promise<any> {
		return new Promise((resolve, reject) => {
		/*Begin_c8o_function:CTS1580309646676*/
		page.c8o.log.debug('[MB] '+ props.actionFunction +': '+ props.actionName);
		page.local.keys = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "		/*End_c8o_function:CTS1580309646676*/
		});
	}

It is truncated where the next character should be a non-breakable space (ALT+06160)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : could not reproduce with a 7.7.1 at v83b2d47 build on Jan 29, 2020

**Comment by gregory-vorbe** [comment]
Made a sample project to reproduce issue:

[issue310.zip](https://github.com/convertigo/convertigo/files/4134236/issue310.zip)

Copy/Paste as a sibling the KeyPage shareAction.

**Comment by nathalie-lammelin** [comment]
The non-breakable space is escaped through xml serialization (while copy) as below

![issue310](https://user-images.githubusercontent.com/27724039/73470414-23980500-4388-11ea-9dd1-cfd9affed327.PNG)
and the property value isn't well deserialized back (while paste) .
We got/load the first `CDATA` only.

**Comment by nathalie-lammelin** [comment]
Issue has been fixed.
But instead of copying / pasting the non-breakable space character in the editor it's better to use the following code in action
- `'\xa0'`
- `String.fromCharCode(160)`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06733-hotfix-7.7.1-7.7.1-beta)**
