### ISSUE TITLE
Log files renamed by the log viewer aren't automatically removed

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#311]
Log4J handle log file, using a rolling appender that don't create more than a configured number of file.
The "Log4J default appender max backup index" engine property default value is 25.
But the convertigo log viewer rename this files using a timestamp name (like engine.k3k7zu90.k4sa113y.log).
The rolling appender doesn't handle them, and they aren't removed automatically.
This should be the case to prevent too many space used by log files.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06781-hotfix-7.7.1-7.7.1-beta)**
