### ISSUE TITLE
PageEvent of a shared component may not be generated in calling page

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#315]
Happen when the `useShared` is deep inside the page tree (> second level).
Does not happen when the `useShared` is directly under the `Content` (for example)

**Comment by nathalie-lammelin** [comment]
For test : use project [lib_ExtendedComponents](https://github.com/convertigo/c8oprj-lib-extended-components)
- for pages `testNgxInput` and `testNgxInput1`, there is no `ionViewCanEnter()` function generated in page component ts file.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06846-hotfix-7.7.1-7.7.1-beta)**

 - Tested with [lib_ExtendedComponents](https://github.com/convertigo/c8oprj-lib-extended-components) project
- Tested with a new 7.7.0 project imported in 7.7.1 and ionViewDidEnter() event
