### ISSUE TITLE
[MB] CustomValidator various issues

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#318]
- Small typo in **The CustomValidator is a component which give you the ability** => **giveS**
 - **your validation function should return null when valid, otherwise it should return any json object filled with error informations** => How and where do we get the returned json object?
 - For an asynchronous validator, in the example promise function:
  function validate1502270851880(c: FormControl) {
/*Begin_c8o_function:validate1502270851880*/
	return new Promise(resolve => {
		//Fake a slow response from server
		setTimeout(() => {
		  if(c.value.toLowerCase() === "user"){
			resolve({
			  "username taken": true
			});
		  } else {
			resolve(null);
		  }
		}, 2000);
	});
/*End_c8o_function:validate1502270851880*/
}
How and where do you use the resolve json? ("username taken" key in the example)

**Comment by nathalie-lammelin** [comment]
Won't fix: No more `CustomValidator` and `FormValidator` in 7.9.0 (Ionic5 / Ngx components)
