### ISSUE TITLE
Xerces failed to write some unicode characters

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#32]
Xerces write 🚀 as &#55357;&#56960; and this is forbidden (other xml reader report that).
So, if you put a rocket in your project (and many other special caracters) your project will be saved as invalid and you cannot open it again.
This is true for all things that write XML in Convertigo.
Some workarounds : write in UTF-16 / patch Xerces / use Saxon to write.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03052-develop-7.6.0-beta)**
