### ISSUE TITLE
[MB] Form component always displays 'form' in project's tree view

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#324]
Even if you change the Form component name it still displays 'form'.
In MobileComponent Source picker you can not differentiate them.
My trick is to set an Identifier in each form I need to Source from:

![image](https://user-images.githubusercontent.com/1685373/75028817-4312e100-54a1-11ea-996e-3e3ec0d8dd30.png)

Displaying the Name or Tag of a compo,nent is always difficult.
In the case of a form, in my case, I would like to display the name and not the tag. But, for example, in the case of a **Break** component, I Would like the tag to be displayed and not its name:

![image](https://user-images.githubusercontent.com/1685373/75028984-8d945d80-54a1-11ea-9ee2-ce8222c322ee.png)

**Comment by nathalie-lammelin** [comment]
Done.
Since [convertigo-08898-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08898-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08898-hotfix-7.8.1-7.8.1-beta)**
