### ISSUE TITLE
PageEvent of a shared component may be incorrectly generated in calling page

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#325]
Only for `onCanEnter` and `onCanLeave` page events (using `Promise.all`) :
- `Promise.all` array may have no comma `,` (and should) to seperate entries
-  `Promise.all` array may have an entry (and should not) for 
   - a disabled event
   - an event contained in a disabled parent

To reproduce, on a page, add an `onCanEnter` event with a `Log` action.
In the content of the page, use a shared `ngxTagInput` from `lib_ExtendedComponents.MobileApplication.Application.ngxTagInput`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 06959-hotfix-7.7.1-7.7.1-beta)**
