### ISSUE TITLE
[MB] Missing ion-card-title MB component for Ionic v3 Cards

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#326]
In Mobile Builder, **Cards** category, we could have the Ionic v3 **ion-card-title** component.

**Comment by nathalie-lammelin** [comment]
Done.
Since [convertigo-08898-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08898-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
**Card Title** is working properly but i am not sure for the documentation:

> Use a Card Title component inside of a Card Header component.

According to Ionic V3 documentation and sample demo, the **ion-card-title** tag is defined inside a **ion-card-content** tag not inside **ion-card-header**.

https://github.com/ionic-team/ionic-preview-app/blob/master/src/pages/cards/image/template.html
https://ionicframework.com/docs/v3/components/#card-image

**Comment by nathalie-lammelin** [comment]
Ionic v3 doc is wrong... `CardTitle` works under `CardHeader` : tested.
I prefer this way so that the projects are compatible with Ionic5.

**Comment by gregory-vorbe** [comment]
That's a good argument and I confirm it is working that way in Ionic 3

OK in **Convertigo EMS Studio 7.8.1_beta (build 08898-hotfix-7.8.1-7.8.1-beta)**
