### ISSUE TITLE
MB Component with 'not set' properties aren't well serialized/deserialized to/from Yaml

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#328]
If we set to `false` ('not set') the `ButtonFormType` property of the `Button` bean
`{"name":"ButtonFormType","mode":"plain","value":false}`
is serialized to yaml by
`"ButtonFormType":"plain:false"`

We lose the **boolean** type of value.
Thus it is not well rendered in ui : `'false'` instead of `false ('not set')` after deserialization.
Related: #327

Seems to happen when `"plain:false"` isn't the **default** value

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07023-hotfix-7.7.1-7.7.1-beta)**

**Comment by nathalie-lammelin** [comment]
Reopen because of #334 : for boolean values

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07193-hotfix-7.7.1-7.7.1-beta)**
