### ISSUE TITLE
Updated engine convertigo-provider-sap dependency to 7.6.7-SNAPSHOT

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#329]
To do when [Report of devus #5765](http://devus.twinsoft.fr/ticket/5765#ticket) is done (waiting for customer feedback)

Update engine gradle to  `com.convertigo.provider:convertigo-provider-sap:7.6.7-SNAPSHOT`

**Comment by nathalie-lammelin** [comment]
[Report of devus #5765](https://bitbucket.org/convertigo/convertigo-provider-sap/commits/a354dfb2f45f395f899ddc60b9b56d9c3e080071) has been done

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07161-hotfix-7.7.1-7.7.1-beta)**
