### ISSUE TITLE
Enforce administration console security

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#330]
Generate and control the session with a token in headers.

**Comment by nicolas-albert** [comment]
Have to handle export from admin (projects, symbols, etc...) and deploy from studio.

**Comment by gregory-vorbe** [comment]
new XSFR properties need to be documented at https://www.convertigo.com/documentation/latest/operating-guide/using-convertigo-administration-console/#main-parameters

**Comment by nicolas-albert** [comment]
https://www.convertigo.com/documentation/hotfix-7.7.1/operating-guide/using-convertigo-administration-console/#main-parameters

**Comment by gregory-vorbe** [comment]
OK
