### ISSUE TITLE
Add a mobilebuilder_tpl_7_8_0 to set the latest SDK JS

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#332]
This will fix issue about loader.

**Comment by nathalie-lammelin** [comment]
The `mobilebuilder_tpl_7_8_0` should be modified accordingly

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
