### ISSUE TITLE
"Disable auto login" property in CallSequence component not saved upon project reloading

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#334]
Convertigo EMS Studio 7.7.1_beta (build 07177-hotfix-7.7.1-7.7.1-beta)

![image](https://user-images.githubusercontent.com/1685373/76964096-6f940e80-6922-11ea-8915-4df18ef6045b.png)

The issue was here in 7.7.0 too

**Comment by gregory-vorbe** [comment]
[testMB771_07153.zip](https://github.com/convertigo/convertigo/files/4349119/testMB771_07153.zip)

**Comment by nathalie-lammelin** [comment]
Related with #328 fix : reopen issue.

**Comment by nathalie-lammelin** [comment]
Should be fixed by #328

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07193-hotfix-7.7.1-7.7.1-beta)**
