### ISSUE TITLE
Add a memory Graph in Admin console Home page

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#335]
Like the threads, context, and  response time we should have a Memory usage graph in the Admin console home page.

**Comment by nicolas-albert** [comment]
Which kind of memory ?

**Comment by opicciotto** [comment]
Total Memory & Available memory

**Comment by nicolas-albert** [comment]
Not a heavy improvement, will be done in 7.7.1 + display "used memory" directly.

**Comment by opicciotto** [comment]
Yes and have Graph Y axis height set to Maximum memory...

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.7.1_beta (build 07233-hotfix-7.7.1-7.7.1-beta)**
