### ISSUE TITLE
Studio hangs when modifying property of shared objects

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#338]
Using property editors
![sharedComponentTresLent](https://user-images.githubusercontent.com/27724039/77451791-6ceb5a80-6df5-11ea-85ca-97aa6e47d1c7.gif)

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
