### ISSUE TITLE
Specify NodeJS version to use per mobile builder template

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#339]
We have a **ionicTpl/version.json**.
We have to extend it with a new key **nodeJsVersion**.
The mobile builder will use this value to download and use the NodeJS of this specified version.
If the key isn't present, a default NodeJS version will be used.
We should also handle the NodeJS for the TS editor of the Studio.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
