### ISSUE TITLE
Studio must add SameSite=None for Set-Cookie headers

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#340]
Since Chrome 80, **SameSite** is enabled by default with a value "**Lax**" if not specified.
Previous behavior is "**None**". It must be set to allow CORS calls between client served by NodeJS and Convertigo Studio.
Details : https://web.dev/samesite-cookies-explained/

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
