### ISSUE TITLE
Speed up project load/save

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#342]
For each bean, we have to find the default bean definition for a given version in the default **database_objects_default.xml** thanks to XPath.
But the definition doesn't change and a same bean can be multiple times in a project.
So we can make a cache with a **classname@version** key instead of doing XPath search every time.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
