### ISSUE TITLE
SharedComponent breaks layout in a header and does not accept JSON object as  a variable

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#346]
**Convertigo EMS Studio 7.8.0_beta (build 07429-release-7.8.0-7.8.0-beta)**

See attached project 
[MB_780_07429.zip](https://github.com/convertigo/convertigo/files/4427268/MB_780_07429.zip)

- Page : Working example without SharedComponent
- Page1: Button layout in header broken using sharedComponent
- Page2: Working button layout but error displaying page because of using a JSON object in SharedComponent Variable.

![image](https://user-images.githubusercontent.com/1685373/78362654-c3f1ec00-75ba-11ea-939b-3cb8e9029bdd.png)

![image](https://user-images.githubusercontent.com/1685373/78362686-cfddae00-75ba-11ea-99d2-258621825ad3.png)

![image](https://user-images.githubusercontent.com/1685373/78362726-dff58d80-75ba-11ea-90f1-9f78234629fd.png)

**Comment by gregory-vorbe** [comment]
JSON is:

{"components":[{"title":"Alert","shortDesc":"Defines an Alert component.","longDesc":["The Alerts are a great way to offer the user the ability to choose a specific action or list of actions. They also can provide the user with important information, or require them to make a decision.","The return value can be accessed by the navigation stack, using parent.out for example."]}]}

I tried to escape double-quotes with backslashes, i tried {{ '{' }}
It seems to work witout quotes around keys and with single quotes around strings.

**Comment by nathalie-lammelin** [comment]
**Page1**
This is an ionic Navbar issue.
In both page & page1, if you put your HelpButtonKO outisde the navbar but sibling to it => the layout is the same.
**Page2**
I will try to find a solution for this case where the code is generated in the html.
In the meantime, yes, use the Javascript object notation.

**Comment by nathalie-lammelin** [comment]
Won't Fix.
**Page1**
This is an ionic Navbar issue.
In both page & page1, if you put your HelpButtonKO outisde the navbar but sibling to it => the layout is the same.
**Page2**
Yes, use the Javascript object notation.
