### ISSUE TITLE
Finally Handler is executed n times

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#347]
reproduce step:
![finnalyHandler](https://user-images.githubusercontent.com/11558728/78376982-556b5900-75cf-11ea-9cdb-a89f2086603b.PNG)

if we have n first level elements, finnaly handler will be executed n times ...

reproduced in studio release/7.8.0 (commit ad383a1267cb8897ef4f97e38d29b1bcde4c4b10) 
with official template 7.8.0, 
only tested with setGlobal bean

Can be reproduced with C8Oforms: see pages=>editorPage=>Content=>Grid1=>GridRow=>ComponentsCol=>DivImg=>Controls=>onTap

**Comment by nathalie-lammelin** [comment]
@CharlesGrimont : workaround
Add a simple action (e.g. LogAction) under your event and move your ModalPage inside.

The feature will be improved for 7.9.0 by #291.
