### ISSUE TITLE
TPL 7.8.0 is missing imports in app.module.ts to support XSRF feature

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#348]

**Comment by CharlesGrimont** [comment]
see https://github.com/convertigo/convertigo/commit/8cbabf3cb2fe9ae41c5bcccb17d3ae475d1f373a

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
