### ISSUE TITLE
NPE log when FlashUpdate prepare files

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#351]
Since 7.7.0, open the testplatform with a mobile project cause this log :

**(MobileResourceHelper) fixMobileBuilderTimes failed : java.lang.NullPointerException**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.0_beta (build 07506-release-7.8.0-7.8.0-beta)**
