### ISSUE TITLE
Gradle CI task downloadNative is not including flashupdate CSS and JS directories

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#353]
Using downloadNative task to build IPA & APK, is not including the CSS and JS directories for flashupdate.

example OK (Build by test platform)

![image](https://user-images.githubusercontent.com/1043988/79189940-4f714580-7e23-11ea-992d-d135fbe0f2eb.png)

Same but built with downloadNative (KO)

![image](https://user-images.githubusercontent.com/1043988/79190151-d8887c80-7e23-11ea-9fcd-73a6a63f59d0.png)

**Comment by nicolas-albert** [comment]
Tested ok
