### ISSUE TITLE
subscribe handler is not porperly removed 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#355]
Subscribe handler is not porperly removed when leaving a page, 

when we leaves page, handler is still active, and prevents listening same event from a new instance of this page.

unsubscribe function seems to be missing handler argumement.  

see [repro_bug_subscribe.zip](https://github.com/convertigo/convertigo/files/4476438/repro_bug_subscribe.zip)

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.8.0_beta (build 07560-release-7.8.0-7.8.0-beta)**
