### ISSUE TITLE
[MB] PublishEvent component, Event data property 'not set' in TS mode

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#358]
![image](https://user-images.githubusercontent.com/1685373/79886631-8d5d0380-83f9-11ea-8e9d-a99a9748a0d8.png)

**Comment by nathalie-lammelin** [comment]
Done.
Since [convertigo-08866-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08866-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08866-hotfix-7.8.1-7.8.1-beta)**
