### ISSUE TITLE
[MB] Improve documentation for Subscribe and Publish components concerning Event data property

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#359]
- **Subscribe** should explain how to handle data passed by the Publish component (parent.out, out, stack['root'].out, etc...)
- **Publish** should precise what kind of data can be passed (TX, TS, SC)

**Comment by nathalie-lammelin** [comment]
Done.
Since [convertigo-08866-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08866-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08866-hotfix-7.8.1-7.8.1-beta)**
