### ISSUE TITLE
CustomEvent Route component needs to be documented

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#36]
CustomEvent is used to handle generic (wildcard '*') events coming from any sequence called in the project. This is the best way to handle any errors generated by any sequences in a centralized manner. For example, any sequence called within an unauthenticated session will return an error. The customEvent can catch this error and display for example an error Toast message using a dataAction.

**Comment by nathalie-lammelin** [comment]
Will be fixed in 7.5.x (see: [5707](http://devus.twinsoft.fr/ticket/5707))
