### ISSUE TITLE
SignaturePad Component : Add onBeginEvent and onEndEvent

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#360]
The Mobile Builder component **Signature** is based on https://www.npmjs.com/package/angular2-signaturepad

It seems that **onBeginEvent** and **onEndEvent** are not mapped in the **c8o-signature** component.

**Note**: Each time you draw on Signature component there is a console.log in Debugger console containing the data. It would be great to disable/remove it.

![image](https://user-images.githubusercontent.com/1685373/80616946-c9b7e180-8a41-11ea-9f00-ddbff497c83c.png)

**Comment by nathalie-lammelin** [comment]
Done.
Since [convertigo-08842-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08842-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08850-hotfix-7.8.1-7.8.1-beta)**

1. Events are fired
2. No more data log
