### ISSUE TITLE
Bump config.xml cordova-version to 10.0.0

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#364]
We need this to support the new version of PhoneGap build

**Comment by nicolas-albert** [comment]
Will update templates with config.xml using latest version of Cordova and Android/IOs versions.
This should be compatible with the gradle build for native app.
The preference phonegap-version is deprecated and cordova-version is prefered.
Adding a nodejs-version preference used for the cordova build.

**Comment by nicolas-albert** [comment]
Check for new ionic3 project and offchat sample.
Ok for convertigo-10002-develop-7.9.0-beta
