### ISSUE TITLE
[MB] HTTP 404 on en.json and fr.json on fresh MB project

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#365]
Fresh built MB project in 7.8.0 complains not finding **en.json** and **fr.json** files.
They are not supposed to be present in project or searched for.

![image](https://user-images.githubusercontent.com/1685373/84642502-d95d8d80-aefc-11ea-8ff8-90610c5f5070.png)

**Comment by nathalie-lammelin** [comment]
i18n feature is activated by default for app:
```
translate.setDefaultLang('en');
translate.use(translate.getBrowserLang());
```
`en.json` and `fr.json` files have been added to the `mobileBuilderIonic `template project
since [convertigo-08826-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08826-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08850-hotfix-7.8.1-7.8.1-beta)**

- Is the **sample-en.json** file still needed in i18n folder of the mobilebuilder tpl ?
