### ISSUE TITLE
FullSync replication missing document with c8oGrp containing dot

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#367]
If your group contains dot(s) like **my.group** and a document have a key like :
`c8oGrp: { "my.group" : true }`

The document isn't replicated.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08770-hotfix-7.8.1-7.8.1-beta)**
Sample project to test:
[Issue367.zip](https://github.com/convertigo/convertigo/files/5155393/Issue367.zip)
