### ISSUE TITLE
Support GetData bean in source picker

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#37]
GetData bean (FullSyncGetAction) is not correctly supported in source picker.
"get" checkbox is in the Design_document>view tree.
When checked the listen generated is computed with 'ddoc' and 'view', should be 'docid'.
Marker is not supported too.

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : do you have any working project (with GetData) to attach ?

**Comment by nathalie-lammelin** [comment]
Fixed in 7.5.6 (see: [5706](http://devus.twinsoft.fr/ticket/5706))
