### ISSUE TITLE
StackOverflow when generating DOM instance for recursive Schema

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#370]
Studio hang and can froze if a picker try to generate a DOM instance of a recursive Schema (see project).

**Comment by nicolas-albert** [comment]
[Issue370.zip](https://github.com/convertigo/convertigo/files/4972926/Issue370.zip)
Open the SequencJS, it should hang the Studio.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08770-hotfix-7.8.1-7.8.1-beta)**

Modified Issue370 project: **Recurse** sequence was referencing a project named "Test".
**Show in Picker** for CopyOf step was the way to reproduce freeze and Out Of Memory issue.
[Issue370_2.zip](https://github.com/convertigo/convertigo/files/5141482/Issue370_2.zip)
