### ISSUE TITLE
Visual App Viewer on Version 7.8.0

### ISSUE THREAD

**Issue by clarenceeda** [convertigo/convertigo#373]
Hello im having trouble on reinstall and exectuing packages using windows 10. here's the log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\MIS\\Documents\\convertigo workspaces\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node.exe',
1 verbose cli   'C:\\Users\\MIS\\Documents\\convertigo workspaces\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve:eval',
1 verbose cli   '--nobrowser',
1 verbose cli   '--port',
1 verbose cli   '8100',
1 verbose cli   '--livereload-port',
1 verbose cli   '35729',
1 verbose cli   '--dev-logger-port',
1 verbose cli   '53703' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'preionic:serve:eval',
4 verbose run-script   'ionic:serve:eval',
4 verbose run-script   'postionic:serve:eval' ]
5 info lifecycle Convertigo-template-app@~preionic:serve:eval: Convertigo-template-app@
6 info lifecycle Convertigo-template-app@~ionic:serve:eval: Convertigo-template-app@
7 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: unsafe-perm in lifecycle true
8 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: PATH: C:\Users\MIS\Documents\convertigo workspaces\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\bin\node-gyp-bin;C:\Users\MIS\Documents\convertigo workspaces\cmfoods\_private\ionic\node_modules\.bin;C:\Users\MIS\Documents\convertigo workspaces\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64;C:/Users/MIS/Convertigo Mobility Platform/Convertigo Mobility Platform Studio 7.8.0/jre/bin/client;C:/Users/MIS/Convertigo Mobility Platform/Convertigo Mobility Platform Studio 7.8.0/jre/bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\OpenSSH\;C:\"Program Files"\Java\jdk1.8.0_241\bin;C:\Gradle\gradle-6.4.1\bin;C:\Gradle\gradle-6.4.1\bin\bin;C:\laragon\bin\php\php-7.2.19-Win32-VC15-x64;C:\ProgramData\ComposerSetup\bin;C:\mongodb\bin;C:\Users\MIS\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.35-win64-VC15\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin;C:\laragon\bin\nginx\nginx-1.16.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v12;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-7.2.19-Win32-VC15-x64;C:\laragon\bin\putty;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\MIS\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\MIS\AppData\Roaming\Composer\vendor\bin;C:\Users\MIS\AppData\Local\Microsoft\WindowsApps;C:\Users\MIS\AppData\Local\atom\bin;C:\Users\MIS\AppData\Local\GitHubDesktop\bin;C:\Gradle\gradle-6.4.1\bin;C:\Users\MIS\AppData\Local\Programs\Microsoft VS Code\bin;C:\mongodb\bin;C:\igop\flutter\bin;C:\Users\MIS\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker Toolbox;C:\Program Files\OpenVPN\bin;C:\Users\MIS\AppData\Roaming\npm;C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.8.0;;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Users\MIS\AppData\Roaming\npm
9 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: CWD: C:\Users\MIS\Documents\convertigo workspaces\cmfoods\_private\ionic
10 silly lifecycle Convertigo-template-app@~ionic:serve:eval: Args: [ '/d /s /c',
10 silly lifecycle   'ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"' ]
11 silly lifecycle Convertigo-template-app@~ionic:serve:eval: Returned: code: 1  signal: null
12 info lifecycle Convertigo-template-app@~ionic:serve:eval: Failed to exec ionic:serve:eval script
13 verbose stack Error: Convertigo-template-app@ ionic:serve:eval: `ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\MIS\Documents\convertigo workspaces\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\MIS\Documents\convertigo workspaces\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Convertigo-template-app@
15 verbose cwd C:\Users\MIS\Documents\convertigo workspaces\cmfoods\_private\ionic
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Users\\MIS\\Documents\\convertigo workspaces\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node.exe" "C:\\Users\\MIS\\Documents\\convertigo workspaces\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve:eval" "--nobrowser" "--port" "8100" "--livereload-port" "35729" "--dev-logger-port" "53703"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error Convertigo-template-app@ ionic:serve:eval: `ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"`
22 error Exit status 1
23 error Failed at the Convertigo-template-app@ ionic:serve:eval script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by opicciotto** [comment]
Hello,
Thank you for reporting..
Where did you get this log from ? I am surprised to see numbers at the beginning of each line...
Is this the first time you have this issue or do you already have other projects running ?
We know that there was an npmjs.com  outage today so this might explain your issue...

**Comment by clarenceeda** [comment]
Hello @opicciotto ,

I got the log output from the visual app viewer and accessed it from 
C:/Users/MIS/AppData/Roaming/npm-cache/_logs/2020-08-06T12_05_24_535Z-debug.log.

I just discovered convertigo yesterday and I thinks this is the best low-code I can have. I hope it's just the npmjs outage.

**Comment by clarenceeda** [comment]
Im still having this problem. I tried installing  older version which is 7.7.0 i still get the same rror
![convertigoapppackages](https://user-images.githubusercontent.com/42695235/89663579-565b2100-d908-11ea-8dd1-8f411ae8ada2.PNG)

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\MIS\\Convertigo Mobility Platform\\Convertigo Mobility Platform Studio 7.7.0\\workspace\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node.exe',
1 verbose cli   'C:\\Users\\MIS\\Convertigo Mobility Platform\\Convertigo Mobility Platform Studio 7.7.0\\workspace\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'ionic:serve:eval',
1 verbose cli   '--nobrowser',
1 verbose cli   '--port',
1 verbose cli   '8100',
1 verbose cli   '--livereload-port',
1 verbose cli   '35729',
1 verbose cli   '--dev-logger-port',
1 verbose cli   '53703' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'preionic:serve:eval',
4 verbose run-script   'ionic:serve:eval',
4 verbose run-script   'postionic:serve:eval' ]
5 info lifecycle Convertigo-template-app@~preionic:serve:eval: Convertigo-template-app@
6 info lifecycle Convertigo-template-app@~ionic:serve:eval: Convertigo-template-app@
7 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: unsafe-perm in lifecycle true
8 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: PATH: C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\bin\node-gyp-bin;C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\cmfoods\_private\ionic\node_modules\.bin;C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64;C:/Users/MIS/Convertigo Mobility Platform/Convertigo Mobility Platform Studio 7.7.0/jre/bin/client;C:/Users/MIS/Convertigo Mobility Platform/Convertigo Mobility Platform Studio 7.7.0/jre/bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\OpenSSH\;C:\"Program Files"\Java\jdk1.8.0_241\bin;C:\Gradle\gradle-6.4.1\bin;C:\Gradle\gradle-6.4.1\bin\bin;C:\laragon\bin\php\php-7.2.19-Win32-VC15-x64;C:\ProgramData\ComposerSetup\bin;C:\mongodb\bin;C:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Program Files\apache-maven-3.6.3\bin;C:\laragon\bin;C:\laragon\bin\apache\httpd-2.4.35-win64-VC15\bin;C:\laragon\bin\composer;C:\laragon\bin\git\bin;C:\laragon\bin\git\cmd;C:\laragon\bin\git\mingw64\bin;C:\laragon\bin\git\usr\bin;C:\laragon\bin\laragon\utils;C:\laragon\bin\mysql\mysql-5.7.24-winx64\bin;C:\laragon\bin\nginx\nginx-1.16.0;C:\laragon\bin\ngrok;C:\laragon\bin\nodejs\node-v12;C:\laragon\bin\notepad++;C:\laragon\bin\php\php-7.2.19-Win32-VC15-x64;C:\laragon\bin\putty;C:\laragon\bin\redis\redis-x64-3.2.100;C:\laragon\bin\telnet;C:\laragon\usr\bin;C:\Users\MIS\AppData\Local\Yarn\config\global\node_modules\.bin;C:\Users\MIS\AppData\Roaming\Composer\vendor\bin;C:\Users\MIS\AppData\Local\Microsoft\WindowsApps;C:\Users\MIS\AppData\Local\atom\bin;C:\Users\MIS\AppData\Local\GitHubDesktop\bin;C:\Gradle\gradle-6.4.1\bin;C:\Users\MIS\AppData\Local\Programs\Microsoft VS Code\bin;C:\mongodb\bin;C:\igop\flutter\bin;C:\Users\MIS\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker Toolbox;C:\Program Files\OpenVPN\bin;C:\Program Files\apache-maven-3.6.3\bin;;C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0;;C:\Program Files\nodejs;C:\Program Files\nodejs;C:\Users\MIS\AppData\Roaming\npm
9 verbose lifecycle Convertigo-template-app@~ionic:serve:eval: CWD: C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\cmfoods\_private\ionic
10 silly lifecycle Convertigo-template-app@~ionic:serve:eval: Args: [ '/d /s /c',
10 silly lifecycle   'ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"' ]
11 silly lifecycle Convertigo-template-app@~ionic:serve:eval: Returned: code: 1  signal: null
12 info lifecycle Convertigo-template-app@~ionic:serve:eval: Failed to exec ionic:serve:eval script
13 verbose stack Error: Convertigo-template-app@ ionic:serve:eval: `ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Convertigo-template-app@
15 verbose cwd C:\Users\MIS\Convertigo Mobility Platform\Convertigo Mobility Platform Studio 7.7.0\workspace\cmfoods\_private\ionic
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Users\\MIS\\Convertigo Mobility Platform\\Convertigo Mobility Platform Studio 7.7.0\\workspace\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node.exe" "C:\\Users\\MIS\\Convertigo Mobility Platform\\Convertigo Mobility Platform Studio 7.7.0\\workspace\\.metadata\\.plugins\\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\\node-v8.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "ionic:serve:eval" "--nobrowser" "--port" "8100" "--livereload-port" "35729" "--dev-logger-port" "53703"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error Convertigo-template-app@ ionic:serve:eval: `ionic-app-scripts serve --enableLint false --sourceMapType eval "8100" "35729" "53703"`
22 error Exit status 1
23 error Failed at the Convertigo-template-app@ ionic:serve:eval script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by opicciotto** [comment]
Hello
This is weird.
Would you be available for a Zoom Call ? We can investigate this now.

**Comment by opicciotto** [comment]
Hello can you configure Studio logs to DEBUG ?
Window->Preferences->Convertigo->Engine->Logs->Log4J Studio Logger ==> DEBUG
And retry ?
You may have more detailed logs there..

**Comment by clarenceeda** [comment]
Hello,

I configured logs to debug. here's what what i got.

![convertigoapppackages](https://user-images.githubusercontent.com/42695235/89717681-88917f00-d9eb-11ea-8f11-40f48974bf28.PNG)

**Comment by clarenceeda** [comment]
thanks @opicciotto  Finally solved it.
Fixed it by setting nodejs env path to 
{workspace directory}\.metadata\.plugins\ts.eclipse.ide.server.nodejs.embed.win32.win32.x86_64\node-v8.9.1-win-x64

then run

`npm cache clean -f`
