### ISSUE TITLE
Unexpected exception using the DatabaseCacheManager with an SQL Server

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#374]
`java.lang.AbstractMethodError` thrown when calling `connection.isValid(timeout)`
Since modifications done for Oracle in the `engine.util.SqlRequester`.

=> The **jtds** driver does not implement the `isValid` method. Works only with a DataSource for wich `validationQuery` string is set at configuration (see [https://stackoverflow.com/questions/41231750/abstractmethoderror-with-jtds-jdbc-driver-on-tomcat-8/41232124](url))

**Comment by nathalie-lammelin** [comment]
Test done by @do91

**Comment by gregory-vorbe** [comment]
Tested with a class by client.
