### ISSUE TITLE
[MB] Cannot re-select the same element after a "remove highlight"

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#377]
In Studio:
*  open the Mobile Viewer
*  right click an element to highlight it
*  press the remove highlight button
* re-select the same element (doesn't work)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.8.1_beta (build 08954-hotfix-7.8.1-7.8.1-beta)**
