### ISSUE TITLE
[NGX] ion2-calendar : Events name have changed

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#381]
In ion2-calendar v3.0.0-rc.0, events name have changed:

- (onSelect)    => (select)
- (onChange) => (change)
- etc...

**Comment by nathalie-lammelin** [comment]
In **8.2.0** we use the ion2-calendar v**3.5.0**.
Events are correctly declared in ion_objects.json and correctly generated in the HTML template.


![ion-calendar-events](https://user-images.githubusercontent.com/27724039/231976213-288e27b1-bcc0-4aae-8e26-1cb4e1fa220b.png)
