### ISSUE TITLE
Some page events don't exits anymore in Ionic5 vs Ionic3

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#383]
`ionViewDidLoad, ionViewWillUnload, ionViewCanEnter, ionViewCanLeave`
See [ionic-page-events](https://ionicframework.com/docs/angular/lifecycle#ionic-page-events)

**Comment by gregory-vorbe** [comment]
The page Events documentation says : 
```
The CanActivate and CanDeactivate interfaces can be used to implement the same type of logic that the removed events ionViewCanEnter and ionViewCanLeave did.
```
Could we put back **ionViewCanEnter** and **ionViewCanLeave** events in the listbox and emulate the events with new route guard implementation?

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : we can't because it does not work the same.
If you convert an Ionic3 project to an NGX one, your old ionViewCanEnter and ionViewCanLeave will remain but are **disabled**.
This allows you to create new CanActivate and CanDeactivate guards and **backport** your code.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12373-develop-8.0.0-beta)**

- Managed to use **onCanActivate** and **onCanDeactivate** App Guards component
