### ISSUE TITLE
[SQL] Default validation query for Oracle connection pools takes too long

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#384]
Current : `SELECT * FROM ALL_TABLES WHERE ROWNUM <= 1` takes `10ms`
Needs: `SELECT 1 FROM DUAL` takes `1ms`

**Comment by nathalie-lammelin** [comment]
**For tests**:
Connection pool must be **enabled** on SQL connector (`Enable connection pool` property)
Custom validation query must be **empty** `(Connection testing query` property) to use default one

Validation query used by pool may be seen in **engine** log in **debug** mode:
`(JdbcConnectionManager) SQL validation query: ....`
Since [convertigo-08979-hotfix-7.8.1-7.8.1-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-08979-hotfix-7.8.1-7.8.1-beta/)

**Comment by gregory-vorbe** [comment]
OK in ** Convertigo EMS Studio 7.8.1_beta (build 08987-hotfix-7.8.1-7.8.1-beta)**
