### ISSUE TITLE
[MB] Backport PWA Service worker for Ngx

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#393]
See #392

- mobilebuilder_tpl_8_0_0 (should be based on mobilebuilder_tpl_7_9_0)
- mobilebuilder_tpl_8_0_0_Ionic5
- template_ngxBuilderIonic

**Comment by nathalie-lammelin** [comment]
Works with _tpl_ngx min v**8.0.0.21** !!

**Comment by nathalie-lammelin** [comment]
Works with _tpl_ngx min v**8.0.0.22** !!

**Comment by nathalie-lammelin** [comment]
Reopen: base-href need to be removed from tpl and added through build code

**Comment by nathalie-lammelin** [comment]
Works with _tpl_ngx min **v8.0.0.23** !!

**Comment by gregory-vorbe** [comment]
OK in **C:\Users\grego\git\c8oprj-lib-extended-components-ui-ngx**
