### ISSUE TITLE
JVM Terminated (Exit Code 127) When starting Convertigo Studio 

### ISSUE THREAD

**Issue by brotenet** [convertigo/convertigo#396]
Hi, :sweat_smile: 

I'm trying to start Convertigo Studio 7.8.0 on a Linux machine with the following OS version attributes...
```
Distributor ID:	Linuxmint
Description:	Linux Mint 20
Release:	20
Codename:	ulyana
Kernel: 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Java Version: openjdk version "11.0.8" 2020-07-14
- OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
- OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```
..and the JVM terminates with the following error output (failing when trying to use a GTK scroll-bar):
```
The ConvertigoStudio executable launcher no longer supports running with GTK + 2.x. Continuing using GTK+ 3.x.
log4j:WARN No appenders could be found for logger (org.eclipse.jgit.internal.storage.file.FileSnapshot).
log4j:WARN Please initialize the log4j system properly.

(Studio:41793): Gtk-CRITICAL **: 12:59:01.711: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!
```

I'm also attaching a small video in the attached archive file [2020-10-26_12.56.27.mp4.zip](https://github.com/convertigo/convertigo/files/5438407/2020-10-26_12.56.27.mp4.zip) so that you can see the entire process up to the point of termination from the JVM.

**Two questions:**
- Maybe you need to use a newer version of Eclipse for your RCP application?
- Is there a plug-in repository that I could use to instal the Studio plug-ins in a working eclipse distribution?

**Comment by nicolas-albert** [comment]
Hi,
Convertigo Studio 7.8.0 is based on Eclipse 2019-06, so GTK3 bugs should be Eclipse related.
Can you try to launch our 7.9.0 beta version based on Eclipse 2020-09 ?
You can find a build here : https://convertigo-ci.s3-eu-west-3.amazonaws.com/convertigo-09225-develop-7.9.0-beta/convertigo-studio-7.9.0-beta-linux64.tar.gz
Thanks

**Comment by brotenet** [comment]
Thanks! :smiley: 
The beta worked.

I guess you should add the download link to the releases page (with a beta version note) since the Eclipse version is outdated and not functional with latest versions of GTK.

**Comment by brotenet** [comment]
issue resolved by using latest beta: https://convertigo-ci.s3-eu-west-3.amazonaws.com/convertigo-09225-develop-7.9.0-beta/convertigo-studio-7.9.0-beta-linux64.tar.gz
