### ISSUE TITLE
Two sequences with same name but not same case does not execute individually

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#4]
You can create a sequence called **SMTP** and another one in same project called **SmtP** but the same sequence (first one created) always execute whatever sequence you choose.

**Comment by nathalie-lammelin** [comment]
We cannot ignore case for bean's name because of directories creation (connectors, pages of MB).
We must forbid the creation of objects of the same name with a different case.
Change back to milestone 7.5.x

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02918-develop-7.6.0-beta)**
