### ISSUE TITLE
Some steps are not documented yet ...

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#401]
* Count 
* Transform
* Split
* Date/Time

**Comment by nicolas-albert** [comment]
http://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/sequencer/steps/xml-steps/count/

http://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/sequencer/steps/xml-steps/transform/

http://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/sequencer/steps/xml-steps/split/

http://www.convertigo.com/documentation/develop/reference-manual/convertigo-objects/sequencer/steps/xml-steps/date-time/

Also ok in the studio wizard doc : Ok for convertigo-09978-develop-7.9.0-beta
