### ISSUE TITLE
Add missings Icons

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#402]
- ~~AppGuard bean~~
- ~~SharedComponent Event bean~~
- ~~UseVariable bean~~
- ~~SwitchCase Handler bean~~
- ~~SwitchDefault Handler bean~~
- ~~NavigatePage action~~
- ~~EmitEvent action~~
- ~~EmitValue action~~
- ~~SwitchAction action~~
- CustomAsyncAction action
- Avatar list bean

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 8.0.0_beta (build 13175-develop-8.0.0-beta)**
It seems there is a transparency issue with the **SharedComponent Event** component. Am I Wrong?
![image](https://user-images.githubusercontent.com/1685373/163144318-a04cc565-a107-4c77-b0c9-8b54a9acc3fb.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 13202-develop-8.0.0-beta)**
