### ISSUE TITLE
Can't show in picker a Fullsync transaction

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#403]
can be reproduced with this project in 7.8.1 latest

[Link to project](https://drive.google.com/file/d/1LJTTqsHgC1Ux9q0nkWEZvcuOE3sMXhFb/view?usp=sharing)

**Comment by nathalie-lammelin** [comment]
Related with #410
Workaround: refresh/reload your project once, then use the picker.

**Comment by nicolas-albert** [comment]
Not reproduced with convertigo-10123-develop-7.9.0-beta and the attached project.
