### ISSUE TITLE
Add a data return property to the CloseModal Action

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#404]
When we use the CloseModal action , it would be useful to  be able to return data to the caller; this could be done by a new **data return** property resulting by a 

`view.dismiss(data) `

When the modal is closed.

This could be done in the ionic and Ngx action beans

**Comment by nicolas-albert** [comment]
The Open Modal must be `Block while = true`
Ok for convertigo-09978-develop-7.9.0-beta
