### ISSUE TITLE
"Missing Gradle project configuration folder: .settings" problem,  Causing a red X error in  ressource view. 

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#407]
This Also prevents the Gradle tasks to display.

We shoud probably create this .settings folder when we add the Gradle nature to the project ?

**Comment by opicciotto** [comment]
Wed also need a org.eclipse.buildship.core.prefs in this directory.

**Comment by opicciotto** [comment]
Gradle Task view is still showing and error, when the projects comes from a git repo.
![image](https://user-images.githubusercontent.com/1043988/100498895-c1ee2600-3165-11eb-8a33-5055a3257edb.png)

**Comment by nicolas-albert** [comment]
#427 discourage the gradle nature
