### ISSUE TITLE
At engine start, a project may be imported more than once if it has circular references

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#410]
This results in a desynchronization of the project loaded in tree with the original project.
We can no longer use the source picker.

See in attachment:
the project "C8Oforms" is imported by both threads "Worker-8: Opening project C8Oforms" and "main"
[issue410.txt](https://github.com/convertigo/convertigo/files/5597376/issue410.txt)

**Comment by nathalie-lammelin** [comment]
A customer had the trouble too, but his project has no cirular reference: see [CONV-456](https://convertigo.atlassian.net/browse/CONV-456?atlOrigin=eyJpIjoiMTVmZGVhOGNkMmY1NDM4MWE3NWUxOWIwYTkxZGQ5NDYiLCJwIjoiaiJ9)

**Comment by nicolas-albert** [comment]
Cannot reproduce with convertigo-10123-develop-7.9.0-beta and the customer project.
