### ISSUE TITLE
We can add an expired key in the key manager

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#415]
We can add an expired key in the key manager.
For example, session key 4C1170303F8FE590-89827862559781C9 can be added with the message "The key '4C1170303F8FE590-89827862559781C9' has been successfully added." but this key is with a validity period expired.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**
