### ISSUE TITLE
Make a dark theme for Convertigo Studio

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#42]

**Comment by nicolas-albert** [comment]
Put here the link to the most important article : http://www.vogella.com/tutorials/Eclipse4CSS/article.html
Here the repository of the spy css plugin : https://download.eclipse.org/e4/snapshots/org.eclipse.e4.tools/latest/

**Comment by gregory-vorbe** [comment]
Make project treeview text white #FFFFF
Make project treeview comment green  lightgreen 
Change icons (App view toolbar,  Popover Page, Close Modal
Make Enginelog on dark backgound (Only change font colors)
Project toolbar is <> color from backgound color ==> Unify it
Fix TS , JS editors to be dark theme.

**Comment by nicolas-albert** [comment]
- change Mobile Palette *Search* and *Clear* border to blue
- remove aliasing from new project icons and MB viewer toolbar + mobile viewer
- MB viewer loader background should be grey as editors
- adapt XPath anchor yellow
- review output editor of requestables
- theme of the TS code

**Comment by gregory-vorbe** [comment]
More contrast on 'Smart Type' sources:
![image](https://user-images.githubusercontent.com/1685373/53024039-97cee680-345e-11e9-91f4-8e0c75825550.png)

![image](https://user-images.githubusercontent.com/1685373/53024084-a7e6c600-345e-11e9-9b2b-40205bebd72b.png)

**Comment by gregory-vorbe** [comment]
Need to change colors in some Wizards:

![capture_newstepwizard](https://user-images.githubusercontent.com/1685373/53024236-ebd9cb00-345e-11e9-9a4a-ceff98ca0835.PNG)
![capture_newprojectwizard](https://user-images.githubusercontent.com/1685373/53024237-ebd9cb00-345e-11e9-99c7-487d0b1932db.PNG)

**Comment by gregory-vorbe** [comment]
Combo boxes in Properties:
![image](https://user-images.githubusercontent.com/1685373/53032490-3a8f6100-346f-11e9-85fb-ca4550a04bc0.png)

**Comment by gregory-vorbe** [comment]
Make documentation links in Mobile Palette more visible:

![image](https://user-images.githubusercontent.com/1685373/53033986-99a2a500-3472-11e9-882e-ff9ccef29f48.png)

**Comment by nicolas-albert** [comment]
fix wizard backgrounds, green comment, browser based documentation
 [9d8e1d3](/convertigo/convertigo/commit/9d8e1d3bf563b19f2035f30268ac33f6734c0960)

**Comment by opicciotto** [comment]
![image](https://user-images.githubusercontent.com/1043988/53172067-b52dbd00-35e4-11e9-8fb6-98e6c1c96306.png)
Issue on shema view

**Comment by opicciotto** [comment]
Issue on App viewer icon
![image](https://user-images.githubusercontent.com/1043988/53172206-0e95ec00-35e5-11e9-833c-5d753de5affc.png)

**Comment by gregory-vorbe** [comment]
Mobile Builder : right-clic Mobile builder element, then choose New > New UI Component :
![image](https://user-images.githubusercontent.com/1685373/53415332-3f08cc00-39d1-11e9-8dcd-ba78f1edf6ce.png)

**Comment by gregory-vorbe** [comment]
Directive component icon has no transparent background:
![image](https://user-images.githubusercontent.com/1685373/53656269-17c13180-3c53-11e9-8af9-8223b89cf2ac.png)

**Comment by opicciotto** [comment]
Drag & Drop to move component up & down in a tree cause a black place holder to be displayed on a dark gray background ==> Not visible. We should turn the place holder to white.

**Comment by lexinor** [comment]
* Green text when testing connection in the install wizard is not visible enough

![c8ostudio_9](https://user-images.githubusercontent.com/28725795/55247061-eda96200-5246-11e9-9bf7-55cc603a4982.PNG)

* "Welcome" page at the start of the Studio needs to be updated and converted to dark theme

![c8ostudio_26](https://user-images.githubusercontent.com/28725795/55247225-4ed13580-5247-11e9-8bce-d37cfa7cd7b4.JPG)

**Comment by gregory-vorbe** [comment]
Is it possible to make the contextual menu dark for the FDD+P selection?
![image](https://user-images.githubusercontent.com/1685373/58086567-32a2a280-7bbf-11e9-9eab-d51b4035345b.png)

**Comment by gregory-vorbe** [comment]
JS inputs in sequence Steps properties have no more blue background:
![image](https://user-images.githubusercontent.com/1685373/58086690-68478b80-7bbf-11e9-9d9d-f8d604f33397.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03862-release-7.6.0-7.6.0)**
 * Open new specific issues if encountering problem with Dark Theme.
