### ISSUE TITLE
Add an Autostart property to a sequence object

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#420]
We need a new property on the sequence object to tell that the sequence should be started automatically in the following events:
* When project is deployed in Studio
* When project is deployed in Server
* When Server is started

**Comment by opicciotto** [comment]
This is breaking NgxMobile Builder as 
`final Project p = Engine.theApp.databaseObjectsManager.getOriginalProjectByName(projectName);`
line Seems to call clearCache() and results in releasing MobileBulder

**Comment by nicolas-albert** [comment]
Ok for convertigo-09978-develop-7.9.0-beta (Studio + Server)
