### ISSUE TITLE
Add SAML 2 SSO library to New project wizard.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#422]

**Comment by gregory-vorbe** [comment]
The project is present in the Wizard but is not properly loaded. The logs show that  there are missing symbols but no pop-up raised and the project is not in the tree view. It only works if I relaunch the Studio.
![image](https://user-images.githubusercontent.com/1685373/106588455-17222b80-654b-11eb-8474-5d3660690d1d.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.0_beta (build 10067-develop-7.9.0-beta)**

**Comment by gregory-vorbe** [comment]
Why do I always think of a new case afterward...
If both **summary** and **description** exist but are blank the **Comment** property displays **null**
