### ISSUE TITLE
Make Mobile Builder If, IfElse and CallSequence actions to display their current setting in tree view

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#423]
In Convertigo projects for readability we need these Action beans to display automatically their settings as many other convertigo beans.

bean | property configuration    | display     |example
------|------------------|------------|------------
If       | condition = expression   | if (condition) | if (out.something == 'test')
If       | condition = expression & negate = true   | if not (condition) | if not (out.something == 'test')
IfElse | condition = expression    | ifElse  (condition) | ifElse (out.something == 'test')
IfElse | condition = expression  & negate = true  | ifElse not  (condition) | ifElse not (out.something == 'test')
CallSequence | requestable = Sequence  | Call (Sequence)  | Call (SubScribeUser)

As these are pseudo beans  probably a formatDisplay() function in the ionobjects.json would do the trick ?

**Comment by nicolas-albert** [comment]
Ok for convertigo-09978-develop-7.9.0-beta
