### ISSUE TITLE
Copying / Paste a component with styles beans attached destroys content of the pasted style beans

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#425]
But copying the style bean itself is ok !

**Comment by nathalie-lammelin** [comment]
Not reproduced in 7.9.0. Reproduced in 8.0.0.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**
