### ISSUE TITLE
Copy/Paste of a shared component do not update sourced properties (SC mode)

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#429]
![issue429](https://user-images.githubusercontent.com/27724039/102467579-bf8a3800-4050-11eb-870d-b622ce5a6b75.PNG)

Copy/paste of the `sharedButton` component do not update `params1608194440714` with new priority

**Comment by nicolas-albert** [comment]
Ok for convertigo-09970-develop-7.9.0-beta
