### ISSUE TITLE
Handle end of context(s) in Internal Requester

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#432]
I attached a simple demo project.
The main sequence loads a file of 1000 entries to iterate through and launch another sequence up to 10 parallel threads.
After one parallel step is finished its context is not released and remove context step can not be used as the parallel step has its owned named context.
[ParallelStepContext.zip](https://github.com/convertigo/convertigo/files/5717131/ParallelStepContext.zip)

**Comment by nathalie-lammelin** [comment]
Seems to work if it does not use the internal requester... to be investigated

**Comment by nicolas-albert** [comment]
Ok with the docker image version 7.9.0_beta (build 09978-develop-7.9.0-beta)
