### ISSUE TITLE
Alert pop-up when CTRL+mouse drag of a sequence in a pageEvent component

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#434]
In a 'onDidEnter' pageEvent, I used to drag and drop a sequence to create the Call components. It is still working but throws an alert pop-up:
![image](https://user-images.githubusercontent.com/1685373/102773065-e5814680-4388-11eb-863d-bc3372f416af.png)

![image](https://user-images.githubusercontent.com/1685373/102773146-08135f80-4389-11eb-867e-aa501147c042.png)

**Comment by nicolas-albert** [comment]
Cannot drag-drop a sequence to another, revert the last modification.

**Comment by nicolas-albert** [comment]
Ok for convertigo-09970-develop-7.9.0-beta

**Comment by nicolas-albert** [comment]
KO for convertigo-09978-develop-7.9.0-beta
Same issue when the target is a `com.twinsoft.convertigo.beans.mobile.components.UIActionElseEvent`

**Comment by nicolas-albert** [comment]
Ok for convertigo-10002-develop-7.9.0-beta
