### ISSUE TITLE
Projects are not displaying in project view when studio starts and there are no projects reopen automatically.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#436]
Steps to reproduce:
- Have a workspace with some projects 
- close all the projects
- Quit Studio
- Relaunch studio

Project tree ss not displayed. Hit the project refresh button ==> Projects are correctly displayed now.

**Comment by nicolas-albert** [comment]
Seen once yesterday, clean machine, no project, just import a demo and empty treeview unless I use the refresh button.
Nor reproduced today.

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 7.9.0_beta (build 10067-develop-7.9.0-beta)**
