### ISSUE TITLE
Convertigo's gradle ci must have a retry policy for task deploy

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#439]
Sometimes, when deploying a project, the task `deploy` fails and we have to re-run all builds task to redeploy it

It would be great to have a retry policy on task deploy.

`
> Task :deploy
Caching disabled for task ':deploy' because:
  Build cache is disabled
Task ':deploy' is not up-to-date because:
  Task.upToDateWhen is false.
Trying to connect the user '***' to the Convertigo remote server: ***
Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
Deployement of '/home/runner/work/C8oForms/C8oForms/build/C8Oforms.car' to the Convertigo remote server: ***
 Going to buffer response body of large or unknown size. Using getResponseBodyAsStream instead is recommended.
 FAILURE: Build failed with an exception.

> Task :deploy FAILED
`

**Comment by nicolas-albert** [comment]
Working for C8oForm deployment
