### ISSUE TITLE
Can not build/serve old Ionic3 project based on custom or old tpl which does not specify nodeJsVersion

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#446]
process use the default nodeJsVersion (`v14.15.1`) which is not appropriate for project.
node_modules are not correctly installed.

**Comment by nicolas-albert** [comment]
Tested with the mobilebuilder_tpl_7_6_0 template because the node version is missing.

Ok for convertigo-09970-develop-7.9.0-beta
