### ISSUE TITLE
subscribe handler is not working in some cases

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#457]
maybe related to https://github.com/convertigo/convertigo/issues/355

Having:
- a page1
  - with an element that can publish an event such as `lib_ExtendedComponents's agGrid`
  - subscribing to `lib_ExtendedComponents's agGrid agGridRowClicked` event
- a page2
  - with an element that can publish an event such as `lib_ExtendedComponents's agGrid`
  - subscribing to `lib_ExtendedComponents's agGrid agGridRowClicked` event
- a page 3
   - with a text  

- When starting app  from `page 2` when are able to receive notifications from `lib_ExtendedComponents's agGrid agGridRowClicked` event

- When starting app  from `page 3` an then RootPage to `page2` when are able to receive notifications from `lib_ExtendedComponents's agGrid agGridRowClicked` event

- But when starting app  from `page 1` an then RootPage to `page2` we areNOT any more able to receive notifications from `lib_ExtendedComponents's agGrid agGridRowClicked` event

can be reproduced with [C8Oforms](https://github.com/convertigo/C8oForms) project at commit 2f19982815b6676aa6703ee1c12cf3efd12030ac

in this context: 

page1 is editorPage
page2 is viewerPage
page3 is selectorPage

NB: `lib_ExtendedComponents's agGrid` is used in `itemGridViewer` sharedComponent in this project

**Comment by nathalie-lammelin** [comment]
Since [988b09a](https://github.com/convertigo/convertigo/commit/988b09aee87e839d1b0bd8ea9af8682d09f19482) with tpl **7.9.0.5** [5962bde](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/5962bde5d626fc4ffaf90705a6b2d50401e5af5a)

**Comment by CharlesGrimont** [comment]
In some cases , for example when rooting `page A` over `page A` , we unsubscribe events before subscribing

 we calls 
``` typescript
this.subscriptions['topic'].unsubscribe();
```
but `this.subscriptions['topic']` is undefined and causes an Uncaught Error

We must check if defined before calling unsubscribe

**Comment by nathalie-lammelin** [comment]
Tested ok for C8oforms
