### ISSUE TITLE
Too many blank lines generated in ts file for pages which contain multiple component with identifier

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#459]
@ViewChildren...
@ViewChild...

@ViewChildren...
@ViewChild...

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.0_beta (build 10043-develop-7.9.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/106638565-528d1c00-6584-11eb-8471-ed94e35c27db.png)
![image](https://user-images.githubusercontent.com/1685373/106638715-74869e80-6584-11eb-980c-72a9f8030b1f.png)
