### ISSUE TITLE
UrlMapper: Basic authentication may be improved

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#46]
Once a user is authenticated on session, we only need to check for same user/credentials rather than execute the Auth requestable again.

**Comment by do91** [comment]
I don't understand this feature in stateless mode (bnpp/pobi case).
I need precision.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03786-release-7.6.0-7.6.0)**
