### ISSUE TITLE
Ngx text elements should be generated  on the same line

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#468]
When we use several Text elements in a Ngx project they are generated on différent lines ex 👍 
`<ion-card-title class="class1615629391449">`
Import Data for '
{{router.sharedObject?.currentDatabase}}
'
`</ion-card-title>`

This will result by adding spaces between each Text element.

![image](https://user-images.githubusercontent.com/1043988/111061056-99363600-84a1-11eb-8e0a-dc286385e54b.png)

Normally this should have been generated as 

`<ion-card-title class="class1615629391449">
Import Data for '{{router.sharedObject?.currentDatabase}}'
</ion-card-title>`

To prevent whitespaces beteween each line of the Text element.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12201-develop-8.0.0-beta)**
