### ISSUE TITLE
Split UI of libraries to dedicated projects

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#470]
To prepare the futur NGX Mobile builder, the current Convertigo libraries with UI (ionic 3) should be split to dissociate backend (sequences + connectors) and the UI (ionic 3 or NGX).

**Comment by nathalie-lammelin** [comment]
rename project, keep UI & remove backend https://github.com/convertigo/c8oprj-lib-vonage-ui-ngx/commit/feee66d86b69505233e1e750d14da728f2a0de50

**Comment by nathalie-lammelin** [comment]
rename project, keep UI & remove backend https://github.com/convertigo/c8oprj-lib-user-manager-ui-ngx/commit/200311f74a4a601e211918dad3dd5f14e996ccfa

**Comment by nathalie-lammelin** [comment]
rename project, keep UI & remove backend https://github.com/convertigo/c8oprj-lib-amazonlex-ui-ngx/commit/85dddba7d5f9fc6be31f1f93451e6aed958ae7e2

**Comment by nathalie-lammelin** [comment]
rename project, keep UI & remove backend https://github.com/convertigo/c8oprj-lib-googlesheets-ui-ngx/commit/bf0b720efb882429500c40ed5d9a203283940ac7

**Comment by nathalie-lammelin** [comment]
rename project, keep UI & remove backend https://github.com/convertigo/c8oprj-lib-excel-ui-ngx/commit/02a811870838bed4cdb29d7a8a33a2577ac0d7cc

**Comment by nathalie-lammelin** [comment]
Project | Back only | Front only: Ionic3 | Front only: Ngx
-- | -- | -- | --
lib_ExtendedComponents* | todo(remove?) | done | done
lib_UserManager* | todo | done | done
lib_Geocoding* | todo | done | done
lib_PushManager | done | done | done
lib_AmazonLEX | done | done | done
lib_Vonage | done | done | done
lib_Stripe | done | - | done
lib_GoogleSheet | done | done | done
lib_MicrosoftExcel | done | done | done
lib_SAML | done | done | done

xxxx* : used by C8oforms
