### ISSUE TITLE
Updating packages and execute cause PNPM install and fails on NGX Viewer

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#471]
After updating a package.json, it is useful to use the "Update packages and execute" command.  This should update the current project packages and relaunch the app.

But it tries to Install PNPM (This is useless as it is already installed for this project) and fails compilation after a long while.

**Comment by nathalie-lammelin** [comment]
Not reproduced:
neither by dragging a component with dependencies nor by manually modifying the file and then `Update packages and execute`.

__Note__: the existence of the `node_modules/.bin/pnpm` file is checked before installation

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**
