### ISSUE TITLE
Sequencer: Attributes generated through a 'copyOf' step are not appended to DOM

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#48]
copyOf  (under a complex)
- source: .../@attribute_name
- source: .../@*

**Comment by gregory-vorbe** [comment]
I don't understand the use case to test this fix / reproduce the issue.
Can you give more information please?
Thx

**Comment by nathalie-lammelin** [comment]
In a Sequence, **copyOf** attribute(s) under a **complexStep** was no working before fix :
- copyOf source : `.../@attribute_name`
- copyOf source: `.../@*`

See attached `issue48.zip` **7.6.0** project to be renamed to  `issue48car`.
[Issue48.zip](https://github.com/convertigo/convertigo/files/3185935/Issue48.zip)

**Comment by gregory-vorbe** [comment]
Thx.
OK in **Convertigo EMS Studio 7.6.0_beta (build 02918-develop-7.6.0-beta)**
