### ISSUE TITLE
Prevents HTTP Transaction to "auto-retry"

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#480]
The Cloud auto-deploy the C8Oforms project using a HTTP Transaction. Sometimes, the request failed and an another is done. In this case, the request is received both and the project is imported twice.

**Comment by nicolas-albert** [comment]
We have to add a new property "Auto-retry on IO error" and have to choose what is the default value.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12210-develop-8.0.0-beta)**
