### ISSUE TITLE
[Studio] HTTP calls can cause a "Unknown transaction" with a reloaded project

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#483]
Step to reproduce:

1. open a project in a Studio, don't execute anything
2. go to the Test Platform, launch a transaction
3. reload the project in the Studio
4. create a new transaction on the same connector
5. go to the Test Platform, launch the new transaction
6. the error should occurs

This is because the Studio context cache previously used connector and doesn't check if the project have changed.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 7.9.3_beta (build 10800-hotfix-7.9.3-7.9.3-beta)**
