### ISSUE TITLE
Update to latest versions of Java, Tomcat 9 and JxBrowser

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#491]
Just update latest versions in build.gradle

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.4_beta (build 10914-hotfix-7.9.4-7.9.4-beta)**

- Java: openjdk version "16.0.1" 2021-04-20
- Tomcat: tomcat-embed-core-9.0.46.jar
- jxBrowser: jxbrowser-swt-7.15.jar
