### ISSUE TITLE
[FullSync] PostBulk with hash cause update conflict if multiple docs use the same _id

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#495]

**Comment by nicolas-albert** [comment]
Sample project:
[Ticket495.zip](https://github.com/convertigo/convertigo/files/6451908/Ticket495.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 7.9.4_beta (build 10914-hotfix-7.9.4-7.9.4-beta)**
