### ISSUE TITLE
Add regular Angular component

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#498]
We need regular component vs template based component

**Comment by nathalie-lammelin** [comment]
Works with latest tpl_8_0_0_ngx (8.0.0.3)

**Comment by nathalie-lammelin** [comment]
See also [https://github.com/convertigo/convertigo/issues/183 - Added new 'autoEmit' property for Shared Variable](https://github.com/convertigo/convertigo/commit/0ced636dcdb998871e6073427fddca59dbeb0ca7)

**Comment by nathalie-lammelin** [comment]
Feature done

**Comment by opicciotto** [comment]
tested ok in various projects
