### ISSUE TITLE
Add a DownloadHttpTransaction for the HttpConnector

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#501]
The HTTP Connector isn't designed to download large file.
There is a base64 mode output that can be used with the write base64 Step but isn't not ideal for large file (use memory, can generate big logs, ...)
This new DownloadHttpTransaction should have a parameter for the fileoutput or return a path to a random temporary path.

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 8.0.0_beta (build 12201-develop-8.0.0-beta)**

Some small typos:

An => A
![image](https://user-images.githubusercontent.com/1685373/151773150-a06c2abd-1026-4a04-8a15-bf6b1b4e523c.png)

combinaison => combination
![image](https://user-images.githubusercontent.com/1685373/151773337-b45f9fd8-5011-4754-b4a5-292e3ede90ab.png)

Length: 0
![image](https://user-images.githubusercontent.com/1685373/151773537-2df25624-e056-46d4-8659-81c062fb37cc.png)

**Comment by gregory-vorbe** [comment]
Sorry, just found another typo : Be default, files are... => By default

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12264-develop-8.0.0-beta)**
