### ISSUE TITLE
[Mobile Builder + NGX] Add an "Application Init" event

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#510]
We have NetworkReachable and some other App events but no "Application Init" event.
It could be triggered at Application startup.

**Comment by opicciotto** [comment]
Bean App event seems not to be updated with the new Event.

**Comment by nathalie-lammelin** [comment]
> Bean App event seems not to be updated with the new Event name in the list of events ,

It works only with latest _tpl_ngx v8.0.0.7 : did you get it first ?

**Comment by opicciotto** [comment]
Sorry ;) yes with the new template this is ok.
