### ISSUE TITLE
[Mobile Builder + NGX] Component highlight from right-click in AppViewer is broken

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#511]
- Launch an application in Studio
- Right click on a displayed component in the AppViewer
The MenuButton or any other component is highlighted but not the right one.

Double-click a displayable component in Treeview is OK : the right component is highlighted in AppViewer

**Comment by nicolas-albert** [comment]
Works for me, need details about issues.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12409-develop-8.0.0-beta)**
