### ISSUE TITLE
[SMTP Step] Add a property to customize the SSL version

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#515]
See #514 : add a property to customize the SSL version.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/150510995-412396b6-a3ba-4a75-8920-5c27bdb343a6.png)

From https://stackoverflow.com/a/32650252/4026111

```
SSLSocket provides a method getSupportedProtocols():

SSLSocketFactory sf = new SSLSocketFactoryImpl();
SSLSocket s = (SSLSocket) sf.createSocket();
System.out.println( Arrays.toString( s.getSupportedProtocols() )) ;

Output: [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
```
