### ISSUE TITLE
Workspace relatives paths are not working as expected

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#519]
Environement:
- Convertigo dev studio 
- Branch https://github.com/convertigo/convertigo/tree/hotfix/7.9.6
- Commit f83e692b1842d2be14abf0f0ce033cd79155f44c

Behaviour:
In Convertigo, when a path is asked, when can pass 3 kind a values:

- Absolute paths like: **"/home/workspace/Project1/data/abc.json"**
- Project relatives paths like : **".//data/abc.json"**
- Workspace relatives paths like **"./Project1/data/abc.json"**

Workspace relatives path are not working anymore,
If we call a step that use a file path, and the project from which we called that step is located in git dependencies folder:
- "./Project1/data/abc.json" will return something like: 
  -  "C:\dev\convertigo_workspaces\workspace790\.metadata\.plugins\com.twinsoft.convertigo.studio\git\Project1\data\abc.json"
- And if we call a step that use a file path, and the project from which we called that step is located in workspace folder:
- "./Project1/data/abc.json" will return something like: 
  -  "C:\dev\convertigo_workspaces\workspace790\Project1\data\abc.json"

In my case i was calling this step from a ProjectA, that was located in "C:\dev\convertigo_workspaces\workspace790\.metadata\.plugins\com.twinsoft.convertigo.studio\git" folder
but referencing "./Project1/data/abc.json", that was located in  "C:\dev\convertigo_workspaces\workspace790\"

And the path returned was wrong since its returned "C:\dev\convertigo_workspaces\workspace790\.metadata\.plugins\com.twinsoft.convertigo.studio\git\Project1\data\abc.json" while the appropriate path would be "C:\dev\convertigo_workspaces\workspace790\Project1\data\abc.json"

So I had a file not found exception

**Comment by nicolas-albert** [comment]
Path like:
`./projects/MyOtherProject/myFile.txt`
Will be solved like:
`<real path to MyOtherProject>/myFile.txt`

**Comment by nicolas-albert** [comment]
Test ok with Studio convertigo-11432-hotfix-7.9.6-7.9.6-beta
