### ISSUE TITLE
Auto configure PouchDB and use it for FullSync (default for Studio, available for server)

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#520]
FullSync is based on CouchDB and it should be configured beside Studio/Server.

For little projects or Studio usage, a PouchDB instance can replace a CouchDB server.

PouchDB can be installed and configured standalone using Nodes of Convertigo.

This new feature allows to use samples of the Studio without extra software to install.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12669-develop-8.0.0-beta)**
