### ISSUE TITLE
[NGX] TS values are not taken in account for Grid columns

### ISSUE THREAD

**Issue by mathieu-francois** [convertigo/convertigo#524]
When I set a property in TS mode for the grid column size, the value is not taken in account.  See below : 

TS mode : 
![ticket-ts-mode](https://user-images.githubusercontent.com/42969589/138704008-16138e5e-3231-4ff9-80e7-052a1bd05fa2.jpg)

Txt mode : 

![ticket-txt-mode](https://user-images.githubusercontent.com/42969589/138704074-3169c131-5cdd-457c-a75f-a2da208be7b0.jpg)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12210-develop-8.0.0-beta)**
