### ISSUE TITLE
[Studio] Execute Sequence and Transaction with JSON output

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#527]
In Studio, we can only see the XML result of a Sequence or a Transaction.
Actions should be added to the see the JSON result too.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12237-develop-8.0.0-beta)**

 - syntax coloring for XML response OK
 - "Execute again" button OK
 - Sequence debugging works
