### ISSUE TITLE
New JsonSourceStep to transform a source to a JS Object

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#528]
Convertigo can generate xml attributes type and originalKeyName used by the json requester.
We need a step that perform the same transformation to use the JS object (or JS array) in the JS scope.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12264-develop-8.0.0-beta)**

**Comment by gregory-vorbe** [comment]
Small typos on step documentation:
![image](https://user-images.githubusercontent.com/1685373/152773018-0e13f76c-bc76-4540-a5bd-0a6e7fff70ff.png)

=> uses
=> parses

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12282-develop-8.0.0-beta)**
