### ISSUE TITLE
Hide lib_ projects from project with a toggle button in project view header.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#529]
We need a new button in project view header to hide lib_ projects. 

Add this information in the new project Wizard so that users now that if they call their project lib_XXXX it will be by default hidden in project view.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)**

**Comment by gregory-vorbe** [comment]
It would be useful to know when the toggle in ON or OFF, because when you open your Studio after a long time and don't see the lib projects, you first think there is an issue and not that the toggle is ON

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)**
