### ISSUE TITLE
Admin - project list displays wrong deployment date after export

### ISSUE THREAD

**Issue by vincego** [convertigo/convertigo#53]
Deployment date is set accordingly to .car archive file last modified date. This works well until we export the project. After that, deployment date equals export date. This is because export action is replacing .car file without touching it in order to preserve original deployment date. What about adding something like `newFile.setLastModified(oldFile.lastModified())`?

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03000-develop-7.6.0-beta)**
