### ISSUE TITLE
Add a JSON to XML Step

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#530]
This step must read a SmartType jsonObject property:

- **Text or Source**: parse the string as JSON Object
- **JS**: convert the JS expression to a JSON Object

Turn the JSON Object as typed XML structure.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)**
