### ISSUE TITLE
Switching between pages holding tabs does not load the first tab page

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#532]
Page1 holds tabs with 2 tab: `tab11` (=> page11) and `tab12` (=> page12)
Page2 holds tabs with 2 tab: `tab21` (=> page21) and `tab22` (=> page22)

1. goto `Page1`, `tab11` is selected and associated `page11` is loaded
2. on `Page1`, select `tab12` : the associated `page12` is loaded
3. using Menu, goto `Page2` => the selected tab is `tab21` but the associated `page21` isn't loaded, it is still `page12`.

This is an ionic issue, see [Setting a tabs page as root does not load the first root page](https://github.com/ionic-team/ionic-framework/issues/12625).
Works well in Ngx.

We need to implement a workarround for this issue.

**Comment by nicolas-albert** [comment]
Test ok for **convertigo-11766-hotfix-7.9.7**
