### ISSUE TITLE
Add a JSON object in page template

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#533]
In many projects it is useful to dump JSON objects for debugging  in logs or directly on page. We often write :

`JSON.stringify(....)`

But the JSON object is not available by default.

We should add a 

`	private JSON:any = window.JSON;
`
In the page template so we always have this JSON object available.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12010-develop-8.0.0-beta)** for NGX projects
