### ISSUE TITLE
Add a ReadJSON and a WriteJSON steps

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#537]
Following #526 , we have to read and write JSON files with steps like XML R/W steps.

**Comment by gregory-vorbe** [comment]
Write JSON Step typos:
![image](https://user-images.githubusercontent.com/1685373/151978116-6205b0e6-2a8d-4eb3-a095-f1633a9d5a41.png)

Read JSON Step typo:
![image](https://user-images.githubusercontent.com/1685373/151978402-db32db97-8db5-49ef-b3b6-6ff0e6ee0032.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12237-develop-8.0.0-beta)**
