### ISSUE TITLE
Add an End point Wizard when building locally

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#539]
When we build locally, we need and End Point Wizard to help the user to set the application end point. The Wizard should  propose  

- http://localhost:18080/convertigo (Local studio)
- http://localhost:28080/convertigo (Local Server)
- Any of the already stored deployment configuration (remote servers)
- A list of existing local machine network IPs by ipconfig (Device testing on local studio)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/148374439-752ba163-d40a-4bc4-8b5b-572b39232ba9.png)
