### ISSUE TITLE
Re enable Grid Guide Button Options

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#542]
When cleaning the viewer context menu, the grid layout guides code was suppressed too, we should re-enable this code

`
function _c8o_showGrids(bShow) {
	//console.log("**** showGrids:" + bShow)
	class styleUtils  {
		constructor() {
			this.final_style = document.createElement('style');
			this.final_style.type = 'text/css';
		}

		addNewStyle(selector, style, id){
			this.final_style.innerHTML += selector + '{ ' + style + ' } \n';
			this.final_style.id =  id;
		}

		submitNewStyle() {
			document.getElementsByTagName('head')[0].appendChild(this.final_style);
			this.final_style = document.createElement('style');
			this.final_style.type = 'text/css';
		}
		
		removeStyle(selector) {
		    var elem = document.getElementById(selector);
		    if (elem)
		    	return elem.parentNode.removeChild(elem);
		}
	}
	
	su = new styleUtils();
	//console.log("**** showGrids: su : " + su);
	
	if (bShow) {
		su.addNewStyle("ion-grid", "border: solid 1px red",  '_c8o_style_');
		su.addNewStyle("ion-row",  "border: solid 1px blue", '_c8o_style_');
		su.addNewStyle("ion-col",  "border: solid 1px green",'_c8o_style_');
		su.submitNewStyle();
	} else {
		su.removeStyle("_c8o_style_");
	}
	
	//console.log("**** showGrids: Finished" + bShow)
}

`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**

**Comment by gregory-vorbe** [comment]
When using refresh button to refresh page, the Grid guide button is still ON but the grids border are hidden.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12282-develop-8.0.0-beta)**

 - Toggling OFF Grid Guide at page reload is a solution!
