### ISSUE TITLE
[MOBILE BUILDER] Cannot edit a fragment object

### ISSUE THREAD

**Issue by mathieu-francois** [convertigo/convertigo#546]
I set a fragment object in front end project tree view, when I double click on it to edit an error is popping : 

<img width="254" alt="Screenshot 2021-12-22 at 15 10 14" src="https://user-images.githubusercontent.com/42969589/147106016-60a3f864-5bd3-4000-a5e8-17e1b8df5b77.png">

When error has disappeared I double click on the fragment once again and a new error is popping : 

<img width="254" alt="Screenshot 2021-12-22 at 15 10 24" src="https://user-images.githubusercontent.com/42969589/147106155-5bcc30c4-7247-4acb-bf49-3ed84fcd33a7.png">

**Comment by nathalie-lammelin** [comment]
Closed.  Should be backported to next `7.9.X hotfix`. Tested with latest build [11832](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-11832-develop-8.0.0-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**

- Tested on Ionic v3 & Ionic v5 MB projects
