### ISSUE TITLE
[MobileBuilder] A project with its own mobile template should not create a ProjectReference on itself

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#548]

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**

It works for a MB NGX project but it does not work for an Ionic v3 project.
When you change MB TPL the old reference should be removed?
![image](https://user-images.githubusercontent.com/1685373/149334712-6fda5e43-f435-406d-9ab4-a6bf4688580a.png)

**Comment by nathalie-lammelin** [comment]
> **Convertigo EMS Studio 8.0.0_beta (build 11913-develop-8.0.0-beta)**
> 
> It works for a MB NGX project but it does not work for an Ionic v3 project. When you change MB TPL the old reference should be removed?

The issue has been fixed in the hotfix 7.9.8 branch, and has not been merged to the develop branch yet.
You should test IonicV3 projects using a 7.9.8 build.

**Comment by gregory-vorbe** [comment]
My bad, thought I was testing in 7.9.8
It works correctly in **Convertigo EMS Studio 7.9.8_beta (build 11958-hotfix-7.9.8-7.9.8-beta)**
