### ISSUE TITLE
Securing CouchDB

### ISSUE THREAD

**Issue by vincego** [convertigo/convertigo#55]
It would be nice to be able to secure CouchDB access through FullSync Connector (or CouchDB connector).
There are 2 complementary ways of doing that :
1. per base: create a document with id "_security" containing authorized names / roles, this limits access to some users
2. per doc: add function "validate_doc_update" to any design document, this is more flexible (read only, some documents only, etc)

**Comment by nicolas-albert** [comment]
Ok with convertigo-03826-release-7.6.0-7.6.0 !
