### ISSUE TITLE
Report patch 7.6.6 SP47

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#550]

**Comment by gregory-vorbe** [comment]
Would it be possible to have more details on this task?
Thx

**Comment by nathalie-lammelin** [comment]
> Would it be possible to have more details on this task? Thx

This concerns the postponement of done modifications (patch) for an older version of product.
The customer has validated the good functioning.
No qualification is required on this task.

**Comment by gregory-vorbe** [comment]
Thank you @nathalie-lammelin !
