### ISSUE TITLE
Create a 'Create shared Component' Wizard on MobileComponent right Click.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#552]
We need a new wizard helping to create a ShareComponent from existing MobileComponent Tree object:

- The tree will be copied to the new Shared Component.
- A Use Shared component will be placed at the existing mobile component place
- All SC and TS  sources from underlying MobileComponents will be converted to SharedCompoennt variables.
- Shared Component will be created by default in the same project
- ShareComponent Name can be edited by User (Default name is  the name of the object the user right clicked on)

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 7.9.8_beta (build 12082-hotfix-7.9.8-7.9.8-beta)**
I have created a sample project issue552.
In the Page, the "Content" component contains a "Div" with a shared component with an "Input" whose value is set with a random number on the onDidEnter event set in the sharedComponent.
It works as expected.
When creating a new shared component from wizard pointing on the top "Div" component, the process and new shared component seem corrects but the Input is not filled with the random value.
[issue552.car.zip](https://github.com/convertigo/convertigo/files/7924980/issue552.car.zip)

**Comment by nathalie-lammelin** [comment]
> When creating a new shared component from wizard pointing on the top "Div" component, the process and new shared component seem corrects but the Input is not filled with the random value. [issue552.car.zip](https://github.com/convertigo/convertigo/files/7924980/issue552.car.zip)

This is related with #568

**Comment by gregory-vorbe** [comment]
2 small typos left:
("**actions**" and "**components**" are plural, no "**s**" to "**remains**")

![image](https://user-images.githubusercontent.com/1685373/150948403-2a49a5b4-e4a8-46bf-9246-0ec33d238d95.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.8_beta (build 12100-hotfix-7.9.8-7.9.8-beta)**
