### ISSUE TITLE
Display in Ngx palette shared components/actions provided by projects.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#553]
We need to display shared components from lib_XXX projects : 

- Shared components will be displayed in a section named from the lib_XXX project by removing the 'lib_' Prefix if existing.
- Comments from Shared component is used to display documentation on the right
- Comments from Shared Variables are used to display documentation on properties
- XXX.png files at the root of the project are used as XXX named Shared Component icons.
- Readme.MD file at the root is used as link in the documentation to display more detailed information. in a MD viewer.

**Comment by nathalie-lammelin** [comment]
TODO: Need to display a default "Shared Component" icon if file is missing

**Comment by nathalie-lammelin** [comment]
Closed at c8o build 14239

**Comment by nathalie-lammelin** [comment]
Closed at c8o build 14248

**Comment by gregory-vorbe** [comment]
No icon for Shared Actions ?
![image](https://user-images.githubusercontent.com/1685373/193026295-fd0bb379-0d74-456f-baa5-5d4ba0b333c5.png)

In project's treeview, Shared actions do have an icon:
![image](https://user-images.githubusercontent.com/1685373/193026469-66f71966-6313-4422-a6ab-b4cd39bc999f.png)

**Comment by nathalie-lammelin** [comment]
Yes, No icon for shared actions of a lib (could have too many)
