### ISSUE TITLE
Add Eclipse UpdateSite support for Studio update

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#557]
Create a new S3 bucket to host built eclipse repository used by the update site feature.
Re-enable the menu for update checking.
Let the Studio start without accepting license (but not the Engine).

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.9.8_beta (build 11982-hotfix-7.9.8-7.9.8-beta)**
