### ISSUE TITLE
Bean Animate is not working as expected

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#56]
When we call bean animate, its not working as expected.

Concerning the behavior, the object that is animated change of position, or is hidden by another element in the list in case of list.

This bug can be easily resolved by using the following code ...

The purpose is to use animate.css instead of any lib, and remove and add css attribute corresponding to the animation wanted. as i the following example

```typescript
// Assuming that this.icon is a ViewChild like 
//=> 	@ViewChild("icon") public icon;
this.icon.nativeElement.classList.remove("animated");
this.icon.nativeElement.classList.remove("jackInTheBox");
setTimeout(() => {
   t = false;
   this.icon.nativeElement.classList.add("animated");
   this.icon.nativeElement.classList.add("jackInTheBox");
   this.tick();
}, 10);
```

**Comment by nathalie-lammelin** [comment]
Issue has been fixed in 7.5.x branch (fix will be available at next merge)
