### ISSUE TITLE
Can't use a shared component from menu in NGX

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#561]
Generation seems to be ok into app.components.ts
but seems to be ko into app.module.ts

**Comment by nathalie-lammelin** [comment]
Fixed using latest `tpl_8_0_0_ngx` v8.0.0.**12**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12210-develop-8.0.0-beta)** and TPL **8.0.0.12**
