### ISSUE TITLE
Undefined values in NGX Calendar component

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#562]
Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)

'From' and 'To' are set to TS 'undefined:
![image](https://user-images.githubusercontent.com/1685373/149988639-6c99c36f-8ebe-4fd3-bb71-60654cbf14f2.png)

**Comment by gregory-vorbe** [comment]
Issue still remains in **Convertigo EMS Studio 8.0.0_beta (build 12201-develop-8.0.0-beta)** TPL 8.0.0.11

**Comment by nathalie-lammelin** [comment]
'From' and 'To' must be set to TS 'undefined' (Date) for the calendar to work on startup.

**Comment by gregory-vorbe** [comment]
> 'From' and 'To' must be set to TS 'undefined' (Date) for the calendar to work on startup.

OK, i thought it was a wrong initialization.

So , it's OK in **Convertigo EMS Studio 8.0.0_beta (build 12201-develop-8.0.0-beta)**
