### ISSUE TITLE
Color issue in NGX Calendar Component

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#563]
Convertigo EMS Studio 8.0.0_beta (build 12019-develop-8.0.0-beta)
When you set "Show months picker" property to true you have access to a list of months, but they are invisible:
![image](https://user-images.githubusercontent.com/1685373/149988738-a66f7bcf-6963-4f99-ad14-d12a7998c42d.png)

**Comment by nathalie-lammelin** [comment]
closed at @[f0c9556](https://github.com/convertigo/convertigo/commit/f0c9556c276e4208c087b1d1f32788ea06df99a3) : Modified pseudo-bean events. Works with tpl 8.0.0.11!

**Comment by gregory-vorbe** [comment]
Issue still remains in **Convertigo EMS Studio 8.0.0_beta (build 12201-develop-8.0.0-beta)** TPL 8.0.0.11

**Comment by nathalie-lammelin** [comment]
When you set `Show months picker` property to `true` the month list is **visible**.
The color is correct also: ion2-calendar supports `primary, secondary, danger, light, dark`

If not, try to dnd a new Calendar into your page.

![Screenshot 2022-01-31 130359](https://user-images.githubusercontent.com/27724039/151790856-f1cbff04-33e7-4e61-9d81-4e769c19294d.png)

**Comment by gregory-vorbe** [comment]
I found out that the issue happens when the Windows 10 Dark mode is activated.

**Comment by gregory-vorbe** [comment]
Same issue if the Chrome browser is set to dark mode:

![Screenshot_2022-02-07-15-15-11-870_com android chrome](https://user-images.githubusercontent.com/1685373/152804920-d8ea02e6-8e47-4090-b53a-a999157fe79d.jpg)

**Comment by nathalie-lammelin** [comment]
@gregory-vorbe : dark mode is not yet implemented, see https://github.com/hsuanxyz/ion2-calendar/issues/320

**Comment by gregory-vorbe** [comment]
You can add css class to the Main Style component of the application.
For example : 
```
.month-packer-item button {
    color: #000 !important;
}
```

Using "**cssClass**" key in Days configuration does not seem to work as stated at https://github.com/hsuanxyz/ion2-calendar#daysconfig
