### ISSUE TITLE
Grid Column size definitions are not generated correctly

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#569]
According to the ionic documentation columns sizes should be set as  

`size-{breakpoint}=value ` but we generate
`size{breakpoint}=value `

Ex : 
`size-xs=6` should be generated instead of
`sizeXs=6`

This for all the other grid properties

**Comment by gregory-vorbe** [comment]
ok in **Convertigo EMS Studio 8.0.0_beta (build 12237-develop-8.0.0-beta)**
