### ISSUE TITLE
Some projects do not load due to a validator considered as invalid

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#57]
A validator may be added to a 'Form' component such as an Input.
If the Input do not set/declare a 'formControlName' property/attribute, an exception is thrown at next project loading: the project won't load.

**Comment by nathalie-lammelin** [comment]
To reproduce:
- Create a Page with a Form and a FormItem/GenericItem
- Drag an Input inside the Item -->the 'formControlName' property is populated with a 'varXXXX'
- Drag a ControlValidator/CustomValidator under the Input
- Save project & reload it --> the project load
- Modify the 'formControlName' property to 'not set'
- Save project & reload it --> the project won't load

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03000-develop-7.6.0-beta)**
