### ISSUE TITLE
Add back button in the default Ngx Template

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#570]
We need to add the Back button in the default NGX template  

```
<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-back-button></ion-back-button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

```

**Comment by nathalie-lammelin** [comment]
Closed. Since build **12264**.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)**

- Back button present in the First default page when creating a new NGX project.
