### ISSUE TITLE
Enable 'Hint' components when dragging NGX Components from palette

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#571]
In 95% of the cases when adding a button there will be a Text object inside. Also When adding a Grid there will be a A GridRow and a GridColumn inside. Same for ListViews, there will be a  a For Each Directive with a Label underneath.

We can have a 'Hint' section in ionic-objects.json describing what object structure we add by default when we drop a palette object. This can be described in JSON this way.

For A Grid Object for example :
```
      "hint": {
      		GridRow: {
      			GridCol: {
      			}
      		}
      }
```

For A button:
```
      "hint": {
      		TextItem: {
      		}
      }
```

For a ListView:

```
      "hint": {
      		"com.twinsoft.convertigo.beans.ngx.components.UIControlDirective" : {
      		        Label: {
      			       TextItem: {
      			}
      		}
      }



```

For a AccordeonGroup:

```
      "hint": {
      		        "Accordeon": {
      			       GenericItem : {
                                       "properties": {
                                                "slot": "header"
                                                "name": "Header"
                                       }
                                       "Label": {
                                                 "com.twinsoft....text": "Some text"
                                       }
                               },
      			       "List": {
                                       "properties": {
                                                "slot": "Content"
                                       }
                                       "GenericItem": {
                                                "label": {
                                                      "com.twinsoft....text": "Some text"
                                                }
                                       }
                               }
      			}
                       "..... "
      }



```

The Hint will be used to create the default component structure. Also we can have a Control modified (Shft, Ctrl or other) to instruct to NOT use the hind when dropping  objects. (We must have a info message  in the palette to explain this to the user) 

Any Components could be 'Hinted' this way , Cards, Pages, Tabbed pages etc ..

**Comment by nathalie-lammelin** [comment]
Functionality implemented. 
To be enriched according to needs.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12778-develop-8.0.0-beta)**

- Tested all 'hint' components according to ion_objects.json file
