### ISSUE TITLE
Read file Steps (XML, JSON & CSV) should append result without the 'step' element

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#572]
Read file Steps result is in a 'step' element and this is not kind if you want to do **output=true** for the step.

We expect that the file content is directly inserted into the Sequence.

For compatibility, migrated beans should have a 'step' element but new created Step shouldn't, so a new Expert property **replace 'step' element'** should be added.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12273-develop-8.0.0-beta)**
