### ISSUE TITLE
Using ModalPage & PopPage action  causes incorrect declaration in app.module.ts

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#573]
If We use a ModalPage action a module declaration is generated in the app.module.ts. 
- We should not generate this declaration in the app (We should do it only if the Modal page is called within a menu)
- Anyway, the declaration uses an incorrect import (../pageName/PageName.module) 

So Bug fix should be to not generate anything in this app.module.ts for regular page.

**Comment by nathalie-lammelin** [comment]
Uses latest tpl v**8.0.0.13**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12669-develop-8.0.0-beta)**

- TPL v8.0.0.16
- Modal and PopOver Actions (+ closeModal, ClosePopover)
- Modal and PopOver Containers (+ closeModal, ClosePopover)
- PushPage / PopPage
