### ISSUE TITLE
Generating [(ngModel)] for forms in the Bindings property should not use the safe operator syntax

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#574]
If we bind data to a form control using the 'Binding' property, this will generate an [(ngModel)] attribute and this is normal. But if we bind this to a global object for example this will result to this generated code .

```
<ion-select class="class1627398166052"
	placeholder="Select a working database for your datamodels and collections"
	name="" multiple="false" cancel-text="Cancel"
	[(ngModel)]="router.sharedObject?.currentDatabase" ok-text="Ok"
	disabled="false" interface="popover"
	(ionChange)="ETS1627400570983({root: {scope:{}, in:{}, out:$event}})">

```
The 	[(ngModel)]="router.sharedObject?.currentDatabase"  is illegal as this cases the following error message when compiling.

`Error: Uncaught (in promise): Error: Errors during JIT compilation of template for databaseSelector: Parser Error: The '?.' operator cannot be used in the assignment at column 38 in [router.sharedObject?.currentDatabase=$event]
`

**Comment by nathalie-lammelin** [comment]
Closed (since build **12246**)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 13238-develop-8.0.0-beta)**
