### ISSUE TITLE
List of certificates in alphabetical order

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#576]
In console admin, into certificate page, there is no alphabetical order for certificate list and no alphabetical order for Certificate / Store column. 
It's complicated to find your certificate with large quantities (BNPP case)

**Comment by gregory-vorbe** [comment]
KO in **Convertigo EMS Studio 8.0.0_beta (build 12409-develop-8.0.0-beta)**

It doesn't seem to sort correctly because it seems to be case sensitive.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12498-develop-8.0.0-beta)**
