### ISSUE TITLE
[Studio] Drag & Drop in treeview or NGX viewer at the desired position

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#579]
Item from TreeView or from Palette can be inserted between items.
Item from NGX viewer (should be hightlighted before drag) or from Palette can be inserted before/inside/after an item.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12669-develop-8.0.0-beta)**
