### ISSUE TITLE
Fix Flashupdate for NGX application

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#581]
NGX uses ES6 module and files from flashupdate cannot be loaded by browser because modules should be served with the "application/javascript" content-type. But loaded from **file:///data/user/0/com.convertigo.mobile.Mb6/files/www/flashupdate/runtime.js** it is "".

Console error from Chrome remote debug:
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

The ionic-webview cordova plugin is mandatory. Some update must be done in flashupdate.js to support it.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12940-develop-8.0.0-beta)**
