### ISSUE TITLE
Slider bean's property "dual-knobs" is now dualKnobs (range)

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#582]
Problem: Slider bean's property "dual-knobs" is now dualKnobs (range)

Behaviour: project won't build if we use Slider

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12841-develop-8.0.0-beta)**

- To set min and max value for the knobs use Attr [ngModel] : https://forum.ionicframework.com/t/how-to-add-default-values-to-ion-range-with-dual-knobs/185009/2
- To dynamically update position values : https://github.com/ionic-team/ionic-framework/issues/17475#issuecomment-466033755
