### ISSUE TITLE
RootPage and PushPage Action are not working properly

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#584]
RootPage and PushPage Action are not working properly

Step to reproduce:
* declare some parameters into a page segment: such as editor/:formId
* Root or Push a page without provinding page data
* page won't push or root

Cause:
* Into RootPageAction.ts/PushPageAction.ts we compute url and if we find a key in url we expect to have an associated parameter
* But it's not necessary the case the following code must check that data is defined as follow
``` typescript
// existing code
if (props.data[key]) {
  segval = props.data[key]
  delete queryParams[key]
}
//fix
if (props.data != undefined && props.data[key]) {
  segval = props.data[key]
  delete queryParams[key]
}
```

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12841-develop-8.0.0-beta)**
