### ISSUE TITLE
Property slot is missing on severals beans

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#585]
Property slot is missing on severals beans:

* Checkbox
* RadioButton
* ToggleButton

**Comment by gregory-vorbe** [comment]
in **Convertigo EMS Studio 8.0.0_beta (build 12841-develop-8.0.0-beta)**

Missing on **ion-label** too (for use with **ion-range** for example)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14096-develop-8.1.0-beta)**
