### ISSUE TITLE
When starting a project that contains errors, it won't display anything into mobile builder view 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#587]
When starting a project that contains errors, it won't display anything into mobile builder view 

  

* In this case we must open the following URL: ws://localhost:41357/ws 

* From it we can read errors and display it into the mobile builder  

* We could optionally propose to highlight beans in error

**Comment by nicolas-albert** [comment]
Not same as https://github.com/convertigo/convertigo/issues/586 ?
Do you have a sample project ?

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 8.1.0_beta (build 14121-develop-8.1.0-beta)**
Error display correctly in Mobile Viewer:

![image](https://user-images.githubusercontent.com/1685373/189902963-41e8815f-0d33-401f-a77b-584c22571cfd.png)
