### ISSUE TITLE
Drop a bean that needs an install of dependencies is not triggering a reinstall of dependencies

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#59]
Drop a bean that needs an install of dependencies is not triggering a reinstall of dependencies
(Only in 7.6)

**Comment by nathalie-lammelin** [comment]
Any case of reproduction ?

**Comment by nathalie-lammelin** [comment]
#42 related : fixed

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03000-develop-7.6.0-beta)**
