### ISSUE TITLE
Cordova Android build failed to retrieve the JDK8

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#593]
For local build and for CI, the Cordova Android build need a JDK8.
Convertigo automatically download the latest JDK8 if not already in the workspace.
Since some days, the zip extract failed (empty JDK dir).

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 12940-develop-8.0.0-beta)**

- If it does not work, you have to check in workspace that the jdk/<jdk-x-folder> is not empty. In the case of an empty folder, delete the <jdk-x-folder> folder and relaunch local build
