### ISSUE TITLE
WS_ERROR tag is created twice in Source Picker of a Call_Transaction Step when importing a SOAP wsdl

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#597]
**Convertigo EMS Studio 8.0.0_beta (build 12958-develop-8.0.0-beta)**

![08_soap_call_step_source_picker](https://user-images.githubusercontent.com/1685373/159746959-5d9337b2-4f2e-45f3-9a91-cf61ced9af4f.png)

**Comment by nicolas-albert** [comment]
New version of **globalCompany_HR_WS** deployed, can you check it's good for you ?

**Comment by gregory-vorbe** [comment]
👍
