### ISSUE TITLE
Add support of Ionic Infinite Scroll

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#60]

**Comment by nathalie-lammelin** [comment]
Need the `c8oPage.call()` to handle `append` mode

**Comment by nicolas-albert** [comment]
To desactivate and postpone.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03786-release-7.6.0-7.6.0)**
