### ISSUE TITLE
ReadJSON failed to read UTF-8+BOM json file and ReadCSV read it as char

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#602]
In case of file encoded with UTF-8+BOM, the ReadJSON step switch to RhinoJS to parse the JSON instead of Jettison.

The BOM must be ignored and allow the Jettison parse.

**Comment by nicolas-albert** [comment]
need to also fix ReadCSV

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 13130-develop-8.0.0-beta)**

- Tested on JSON w/ BOM, JSON w/o BOM, CSV w/ BOM and CSV w/o BOM
