### ISSUE TITLE
[NGX] The Chart no longer compiles due to the removal of the 'colors' property

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#603]
colors are now part of the `datasets` property

Before:
```
[datasets]="[{'label': 'My first dataset','data': [0, 10, 5, 2, 20, 30, 45]},{'label': 'My second dataset','data': [15, 45, 10, 20, 65, 38, 88]}]"
[colors]="[{'backgroundColor': 'rgb(0, 127, 255)','borderColor': 'rgb(0, 0, 255)'},{'backgroundColor': 'rgb(136, 77, 167)','borderColor': 'rgb(102,0, 153)'}]"
```
After:
```
[datasets]="[{'label': 'My first dataset','data': [0, 10, 5, 2, 20, 30, 45], 'backgroundColor': 'rgb(0, 127, 255)','borderColor': 'rgb(0, 0, 255)'},{'label': 'My second dataset','data': [15, 45, 10, 20, 65, 38, 88], 'backgroundColor': 'rgb(136, 77, 167)','borderColor': 'rgb(102,0, 153)'}]"
```

**Comment by gregory-vorbe** [comment]
Is it normal that when I added the Chart component to my already built NgxApp it removed all node modules and reinstalled all packages, as if I clicked the "Re-install packages and execute" menu ?

**Comment by nathalie-lammelin** [comment]
> Is it normal that when I added the Chart component to my already built NgxApp it removed all node modules and reinstalled all packages, as if I clicked the "Re-install packages and execute" menu ?

Yes it is

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.0.0_beta (build 13130-develop-8.0.0-beta)**
