### ISSUE TITLE
Need automatic generation of project MD files

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#610]
Auto generation with beans/variables comments (sequences, shared components, ...).
May be customized (fully or not) by user.

**Comment by gregory-vorbe** [comment]
In Github renderer:
![image](https://user-images.githubusercontent.com/1685373/181292801-4fb1d2db-c6c6-463c-a05d-9117cc495e0d.png)

**Comment by nathalie-lammelin** [comment]
For last fix commited, if you already have a **readme.ftl** in your project :

1. Or, you may fixed it adding a line break in the macro table as following (`</table>${lineBreak}`)
```
<#-- table: generates a table with given headers and rows -->
<#macro table title headers rows>
<#if (rows?size > 0)>
${title}${lineBreak}
<table
<tr>
<#list headers as header><th>${header}</th></#list>
</tr>
<#list rows as i>
<tr>
<#list headers as header><td>${i[header]}</td></#list>
</tr>
</#list>
</table>${lineBreak}
</#if>
</#macro>

```
2. Or, you may delete your **readme.ftl** and get the new one (from webapp) through `Project -> Generate readme`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14176-develop-8.1.0-beta)**
