### ISSUE TITLE
When using a segment into a single page application, routes are not generated correctly 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#611]
Within a NGX app, When using a segment into a single page application, routes are not generated correctly 

Step to reproduce:
* Create a new NGX app
* Make sure you have only one page
* Define a segment with parameters such as `login/:singup`
* Generated code miss a coma

**Comment by nathalie-lammelin** [comment]
**A workaround**: create a second useless page.

**Comment by nicolas-albert** [comment]
Ok for **convertigo-13647-hotfix-8.0.1-8.0.1-beta**.
