### ISSUE TITLE
Manage conflicts of components with the same name from different libraries and used in the same project

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#620]
E.g: a project having a page with a use of `lib_A.CustomComp` and a use of `lib_B.CustomComp`
- **lib_A** with a sharedComponent named **CustomComp**
- **lib_B** with a sharedComponent named **CustomComp**

proposal

- source files of a component are generated using the project name as the identification prefix
```
_private/src/app/components/
    lib_a.customcomp/
       lib_a-customcomp.html
       lib_a-customcomp.ts     (class name is : Lib_A_CustomComp)
       lib_a-customcomp.scss
       lib_a-customcomp.module.ts    (module class name is : Lib_A_CustomCompModule)

```
- in a page, the selector and the identifier of the component are unique and consist of the names (lowercase) of the project and the component separated by a '-' for the selector and '_' for the identifier
`
<lib_a-customcomp #lib_a_customcomp  [owner]="this"   ></lib_a-customcomp>
`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14311-develop-8.1.0-beta)**
#634 Not reproduced too:
![image](https://user-images.githubusercontent.com/1685373/193032124-0ba497f0-8794-4671-87aa-7357b88da798.png)
