### ISSUE TITLE
ReadCSV step : Add some improvements to Step

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#621]
**Convertigo EMS Studio 8.0.1_beta (build 13512-hotfix-8.0.1-8.0.1-beta)**

Source property is set to a local CSV file, hardcoded.
When you switch **Title line** property to true, source picker is empty and you can not source element in the treeview:

![image](https://user-images.githubusercontent.com/1685373/173354553-64ef3609-97ff-4343-ab56-174c9a951fd9.png)

**Comment by nicolas-albert** [comment]
Not reproduced here, I have to see your project.

![readvsc_picker](https://user-images.githubusercontent.com/225279/173529462-9ddc52fe-3144-4435-ac20-3308c7d4af43.png)

**Comment by gregory-vorbe** [comment]
- Add originalKeyName for Title column name
 - Add dynamic character separator
 - Add dynamic encoding property

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14085-develop-8.1.0-beta)**

_ New originalKeyName attribute for title line
_ Separator auto detection
_ Encoding auto detection
