### ISSUE TITLE
Ngx Builder : need a Font and FontStyle beans

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#622]
See [https://fontsource.org/](https://fontsource.org/)

- **Font**: same as **Style** but will install necessary font(s) through npm
can be added under **Application** or **Shared Component**
- **FontStyle**: same as **Style** but specific for font CSS rules
can be added under any **Text container** component

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 8.1.0_beta (build 14176-develop-8.1.0-beta)**

- Configuring a **fontStyle** component does not update display (still have the ?). Must reload project to see details next to the component:
    ![image](https://user-images.githubusercontent.com/1685373/191217480-a248e65c-b4d2-4111-8a8e-6aa709071082.png)

- If you change *Definition* of the **Font** component, the new font is not proposed in the list box of the FontStyle component:
    ![image](https://user-images.githubusercontent.com/1685373/191218276-0e87d48b-d77a-4793-b679-3fff167b79cf.png)

In this example, I changed the existing **Zen Tokyo Zoo** font to **Beth Ellen**. It is not proposed in the Font family list box.

**Comment by nathalie-lammelin** [comment]
Closed (see commit comment).
For fontStyle directly under a main component (Page, sharedComponent), you need to specify the CSS rule selector/class.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14338-develop-8.1.0-beta)**

- The @Rule Selectors/Classes listbox used to be empty in the FontSTyle component, now there is some selectors proposed (ion-item, ion-content,...). It is not obvious you can type in a custom one here.
- 
![image](https://user-images.githubusercontent.com/1685373/193095714-ee0a0671-3dd1-4f1e-aea2-f7f5dc2ebe9d.png)
