### ISSUE TITLE
Review admin console Connection page

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#625]
We should : 
- Change the lower level panel name from 'Connections' to 'Contexts'
- Explain what FS means
- Explain what Roles means
- Explain what 'Connexion state of the contexte associated with the connexion' means
- Explain what Max HTTP session activity means

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14096-develop-8.1.0-beta)**

**Comment by gregory-vorbe** [comment]
Maybe items in the "**Legend**" section could be formated in a table to be aligned and be more attractive.
The Max HTTP session inactivity is too long and values are shifted to the right.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14176-develop-8.1.0-beta)**
