### ISSUE TITLE
[FS/CouhDB Connector] PutDocumentAttachment on PouchDB replace space with + for docid

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#627]
To reproduce, create a `PutDocumentAttachment` transaction with `Param docid` = `my doc 1+2` then execute. The attachment is inserted inside a new document `my+doc+1+2`: spaces are replaced with `+`.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14121-develop-8.1.0-beta)**
