### ISSUE TITLE
Object selection in Convertigo Project View reveal corresponding file in Project Explorer View

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#628]
We often have to manage project files and switch between the Convertigo Project View and the Project Explorer View.
Both have their own focus and selection.
It could be nice if the Project Explorer View sync it's focus with the current selected object in the Convertigo Project View.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14121-develop-8.1.0-beta)**
