### ISSUE TITLE
Add an Assets section in Ngx Source picker

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#629]
We can have a new section in the Ngx Source picker for picking and D&Dropping  assets in Ngx components properties. This is very useful for example for IMG , LazyImage on the src property.

The picker represents the assets folder with all the sub folders and files in a tree view. The user can Drag & Drop a file directly on a component and bind it to the full file path  in TS mode.

Also we can add in this section a Browse / import button to import a external assets by its URL or by browsing files in the File System.  If a file is selected it will be copied in the assets folder and be able to be picked as all the others..

**Comment by nicolas-albert** [comment]
**Tested ok for convertigo-14508-develop-8.1.0-beta**
