### ISSUE TITLE
Admin web / Bad parameters in projets

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#63]
With build 01979-develop-7.6.0-beta server, when viewing parameters of project in projects list, some of them are set with a bad value "admin".
![image](https://user-images.githubusercontent.com/39701177/53476708-4bddfc00-3a73-11e9-8f8c-2291c4cb71e5.png)
Only with chrome (version used Version 72.0.3626.119).
No problem with firefox or edge:
![image](https://user-images.githubusercontent.com/39701177/53476907-cc046180-3a73-11e9-9c3c-81179103c2da.png)

**Comment by nicolas-albert** [comment]
I think it's come from the Chrome FORM filler and I don't know why, I have to look for input attributes.
I think this is due to a new Chrome version, not the 7.6.0.

**Comment by nicolas-albert** [comment]
Related to https://stackoverflow.com/questions/15738259/disabling-chrome-autofill and https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off : trying suggested workarounds …

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)** and **Google Chrome Version 74.0.3729.131 (Build officiel) (64 bits)**
