### ISSUE TITLE
Update Studio and Windows installer splashscreen

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#631]
Convertigo have the "wave" splashcreen for years.
The new Eclipse "facet" splashscreen is nice : https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=288580

It can be an inspiration for a new Convertigo splash with blue in mind.

**Comment by nicolas-albert** [comment]
[convertigo_background.zip](https://github.com/convertigo/convertigo/files/9084933/convertigo_background.zip)
Added Gimp sources.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14058-develop-8.1.0-beta)**

- New splash image for w64 installer and Studio startup.
- Text is not blurred anymore.
