### ISSUE TITLE
UrlMapper is slower than executing the sequence directly

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#632]
**Convertigo EMS Studio 8.0.1 (build 13709-8.0.1)**

See attached project : test_urlmapper.car

Execute : http://localhost:18080/convertigo/projects/test_urlmapper/.json?__sequence=GetNorme&frequency=toto
This will respond in 2-3s

Execute : http://localhost:18080/convertigo/openapi/norme?QueryParameter=toto
This will response 25-30s

In urlmapper it seems gzip is not activated, no **Content-Encoding: gzip** in response header but present in sequence call.

**Comment by gregory-vorbe** [comment]
[test_urlmapper.car.zip](https://github.com/convertigo/convertigo/files/9102555/test_urlmapper.car.zip)

**Comment by nathalie-lammelin** [comment]
**Proposal**:
We have two paths `/api` and `/openapi`.
As the **swagger/oas2** (`/api`) is no longer maintained, one could use:

- /api
For standard REST requests that do not require any compliance with schemas.
Returned responses are identical to those of json/xml requesters

- /openapi
For REST resquests that require compliance with schemas.
Returned responses are transformed for compliance with (**openapi/oas3**) schemas

**Comment by nicolas-albert** [comment]
Ok with that !
Also we must add /openapi for gzip compression: https://github.com/convertigo/convertigo/blob/develop/engine/src/com/twinsoft/convertigo/engine/servlets/CompressionFilter.java#L51

**Comment by nicolas-albert** [comment]
Tested OK with Studio win64 convertigo-13917-hotfix-8.0.2-8.0.2-beta

**Comment by nicolas-albert** [comment]
[convertigo-7.9.8-patch-urlmappe-json.zip](https://github.com/convertigo/convertigo/files/9352600/convertigo-7.9.8-patch-urlmappe-json.zip)
Backported patch for 7.9.8
