### ISSUE TITLE
[HTTP] POST request with followRedirect set to true on transaction, redirects using POST instead of GET

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#638]
See [CONV-580](https://convertigo.atlassian.net/browse/CONV-580)

![http-2xx-3xx-status-codes](https://user-images.githubusercontent.com/27724039/184308304-014265c4-1fc8-45ad-b606-4443a06e74c3.png)

**Comment by nicolas-albert** [comment]
[Issue638.zip](https://github.com/convertigo/convertigo/files/10332633/Issue638.zip)

Use the HTTP transaction POST_redirect to reproduce.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 14863-develop-8.2.0-beta)**
