### ISSUE TITLE
Add multiline support for requestable variable default value (single and multi valued)

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#639]
See [CONV-582](https://convertigo.atlassian.net/jira/servicedesk/projects/CONV/queues/custom/1/CONV-582)

**Comment by nathalie-lammelin** [comment]
Not working : some commits missing ?
- ReadJSONStep is broken (still has reference on deleted GenericTextEditor)
- Multi valued variable default value edition is broken

**Comment by nicolas-albert** [comment]
All is fine localy, no uncomited file and CI build is also ok : https://app.circleci.com/pipelines/github/convertigo/convertigo/870/workflows/b0c2cfec-29ed-4d47-81ac-8c09cf4d00de

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14121-develop-8.1.0-beta)**
