### ISSUE TITLE
Mobile Builder: Dragging a folder make crash the studio

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#64]
If you drag a folder in the mobile builder app tree view, (like style folder) when we dragover another page  the studio open a dialog saying that we cannot drag and freeze totaly.

We must prevent from dragging this object or resolve the bug...

NB: Not tested in 7.5

![conbug2](https://user-images.githubusercontent.com/11558728/53477539-3b2e8580-3a75-11e9-85d9-6ea6e6d0af29.PNG)
![conbug4](https://user-images.githubusercontent.com/11558728/53477538-3b2e8580-3a75-11e9-9ffb-b8a48fce3d69.PNG)
![conbug3](https://user-images.githubusercontent.com/11558728/53477540-3b2e8580-3a75-11e9-88e4-aa8d82db9073.PNG)

**Comment by nicolas-albert** [comment]
Reproduced in 7.5.x, will be fixed in and merged after.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
