### ISSUE TITLE
Update the default GitHub Actions file with cache configuration

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#640]
See https://github.com/convertigo/c8oprj-lib-exchange and add `version.json` has cache key.

**Comment by gregory-vorbe** [comment]
Need some minor modification:

- workflow fails because of 'deploy' on C8O Server (remove or add condition?)
- Default branch is set to 'ci' (add other branches?)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14185-develop-8.1.0-beta)**
