### ISSUE TITLE
[SQL] Missing error element in case of failure

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#641]
When an error occurs with a XML transaction (security, constraint error, bad request ...) the message is displayed inside the sql_output element and not flagged as an error.
An error tag must exists next to sql_output with the standard syntax and the error details.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14040-develop-8.1.0-beta)** and **Convertigo version 8.1.0_beta (build 14058-develop-8.1.0-beta)**
