### ISSUE TITLE
NavParams are not updated after a root/push/navigate page

### ISSUE THREAD

**Issue by mathieu-francois** [convertigo/convertigo#642]
To reproduce:

1. load a page with some navParams and a setLocal object with the navParams value on pageWillEnter event
2. make a push page with these navParams
3. on the new page, make a push page with updated navParams to previous page

The updated navParams are not loaded 

Adding the following code inside the page constructor seems to fix the issue : 

`/*Begin_c8o_PageConstructor*/
		this.route.queryParams.subscribe(params => {
			this.navParams = new NavParams(params)
        });
		/*End_c8o_PageConstructor*/
`

**See project attached with multiple test cases**: [issue642.zip](https://github.com/convertigo/convertigo/files/9527515/issue642.zip)

**Comment by nathalie-lammelin** [comment]
The above fix:
- breaks `Popover` and `Modal` pages
- `path params` are not updated, only `query params` are

**Comment by nathalie-lammelin** [comment]
Fixed since NGX tpl v **8.0.0.38** : modified page.tpl for navParams

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14121-develop-8.1.0-beta)** with NGX tpl **v8.0.0.38**

[test_navparams.zip](https://github.com/convertigo/convertigo/files/9556032/test_navparams.zip)
