### ISSUE TITLE
[Docker] Easy configuration to enable HTTPS

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#644]
Automatically configure Tomcat to enable HTTPS connector using certificate from Docker parameter.
Don't forget documentation.

**Comment by gregory-vorbe** [comment]
Some typos in documentation:
- reverse proxy that handle HTTPS / SSL => **handles**
- Here the variables to configure: => Here **are** the...
- Generated files can be retrieve if => **retrieved**
- Convertigo use a *cookie* => **uses**
- but we advice to use an *HTTPS* => **advise**
- In this case, you can secure yours cookies => **your**
- if you have configured the **SSL** configuration => if you have **set** the...
- The image include *sudo* command line => **includes**
- some *root* action inside => **actions**
- This variable allow to disable => **allows**

Documentation says:
If the SSL configuration is correct, the Convertigo Server will listen **HTTP** on port `28080` and **HTTPS** on port `28443`.
...
docker run -d --name C8O -v <my SSL folder>:/ssl -p 28443:28443 convertigo

Shouldn't it also mention **-p 28080:28080** ?

**Comment by gregory-vorbe** [comment]
Documentation reviewed OK
