### ISSUE TITLE
Ngx Palette: Variable icon is too thick

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#648]
**Convertigo EMS Studio 8.1.0_beta (build 14230-develop-8.1.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/192222551-85b3714b-7164-4358-8881-3726e6a1733a.png)

**Comment by gregory-vorbe** [comment]
In Ngx paletten there are two "ACtions sheet" components, and now one icon is missing:
![image](https://user-images.githubusercontent.com/1685373/193027110-42ed6973-2797-46d6-b9e4-4e2944a7cf32.png)

**Comment by Soushi77** [comment]
C’est bon c’est réglé normalement, j’avais oublié qu’il y en avait 2 du coup j’ai mis la bonne nomenclature pour les 2 à l’instant Le 29 sept. 2022 à 14:07, Grégory VORBE ***@***.***> a écrit :﻿
In Ngx paletten there are two "ACtions sheet" components, and now one icon is missing:

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14320-develop-8.1.0-beta)**
