### ISSUE TITLE
File from DisplayObjects/mobile/assets/i18n are deleted 'randomly"

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#65]
Frequently, the file of i18n are deleted.

Also sample-en.json is always copied into this folder .... We must not any more copy this file on the folder if there is other files present...

Most of the time deletion append when we have a crash of studio ...

**Comment by nicolas-albert** [comment]
Ok, I think this is the workflow :

* `assets` folder of the TPL is copied into `_private/ionic`
  * https://github.com/convertigo/convertigo/blob/4ec7a36751a89dda9793b7b84b169793dd56611d/engine/src/com/twinsoft/convertigo/engine/mobile/MobileBuilder.java#L661
* `npm build` copy the `_private/ionic/assets` to the `DisplayObjects/mobile` folder
  * https://github.com/convertigo/convertigo/blob/4ec7a36751a89dda9793b7b84b169793dd56611d/eclipse-plugin-studio/src/com/twinsoft/convertigo/eclipse/editors/mobile/ApplicationComponentEditor.java#L1198

So the `sample-en.json` is overwritten.

Maybe, if the `DisplayObjects/mobile/assets` folder exists before the `npm build`, it should be copied to `_private/ionic/assets` before the build.

Do you agree ?

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03000-develop-7.6.0-beta)**
