### ISSUE TITLE
Missing slot=start attribute in menuAutoItems

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#650]
When we setup an icon in page this icons is used in the Menu in the MenuAutoItems.  2  issues there : 

- When no icon is defined, we generate a icon compoent with a blank icon name causing a 404 error on '-sharp.svg'
- When ison is defined it is generated but there is a mssing slot=start attribute causing a ths icon to be displayed to neear the label.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14311-develop-8.1.0-beta)**
