### ISSUE TITLE
Remove CTF references from documentation

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#653]
https://doc.convertigo.com/documentation/latest/reference-manual/convertigo-mbaas-server/convertigo-full-sync-architecture/
https://doc.convertigo.com/documentation/latest/reference-manual/convertigo-mbaas-server/convertigo-client-sdk/

Maybe also at other place.

The up-to-date SDK documentation is here: https://github.com/convertigo/c8osdk-angular

**Comment by gregory-vorbe** [comment]
Modified concerned pages:

- https://github.com/convertigo/convertigo-doc/commit/0baaadf16e3d89eec82df51854b05420dc5baec9
- https://github.com/convertigo/convertigo-doc/commit/ee6193cf22a327b58f69f046a083e5536fdd3227
