### ISSUE TITLE
Built Studio configuration should set the default file encoding to UTF-8 by default

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#654]
In the `ConvertigoStudio.ini` file : add `-Dfile.encoding=UTF-8`

related with #652

**Comment by nicolas-albert** [comment]
fixed in #652

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14356-develop-8.1.0-beta)**
