### ISSUE TITLE
Project schema cache should be cleared on successful project delete / import / deploy / reload

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#656]
The `SchemaManager:clearCache(Sting projectName)` is only called by some eclipse views/actions.

In server mode, if we have an already loaded project with v1
- if we `delete` it, the schema cache is not cleared
- if we `reload` it, the schema cache is not cleared
- if we `deploy/import` it with v2, the schema cache is not cleared and is still the v1 cache

thus, we have to **restart** the server to free the schema cache (for just one project) so that we can regenerate the project schema cache when needed (e.g. on Soap/Rest requests)

**Comment by nathalie-lammelin** [comment]
For test (after `deploy|reload|import`) : request the project `WSDL`
In the `catalina.out` file, should find trace like `Schema for project PPPP | Times >> total : NNN ms`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14400-develop-8.1.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/194525081-244a1b1b-77ad-4272-8779-7638f8aeec13.png)

**Comment by gregory-vorbe** [comment]
Tested on deploy, reload, delete/import
