### ISSUE TITLE
[NGX Builder] UIComponent reorder can failed

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#657]
In NGX Builder (and probably also Mobile Builder), UiComponents (ShareComponent, Button, ...) can mix other UiComponents + Variable + Event, separated in virtual folder in the treeview.
When you increase/decrease or drag & drop a child, sometimes it can not move where you want.
This is because UiComponents children's order is stored in the a unique vector and the selected element move in this vector that not reflect its place in its virtual folder.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14400-develop-8.1.0-beta)**
