### ISSUE TITLE
Importing Swagger OAS3 API creates Transactions with the 'Include data type in XML response node' to False 

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#658]
When we import a OAS3 Swagger, the Transactions are created with the 'Include data type in XML response nodes' to false.. We have to set this to true. If not, JSON object translation is not done properly in applications.

**Comment by nathalie-lammelin** [comment]
For testing purposes (proper translation) you should include a test url or project

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14445-develop-8.1.0-beta)**

 - Tested with **petstore3.swagger.io**
