### ISSUE TITLE
[NGX builder] Icon picker with preview for all "Icon" properties

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#660]
The idea is to remove the 1332 text entries for properties using icon name and add a icon picker with icon preview to be more user friendly.
Ionic provides a local page to preview all icons and we want to click to select an icon for the current property.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14445-develop-8.1.0-beta)**
