### ISSUE TITLE
PouchDB does not start if another Studio supporting PouchDB is already started

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#662]
**Convertigo EMS Studio 8.1.0_beta (build 14445-develop-8.1.0-beta)**

Steps to reproduce:

- Start a Studio 8.0.1 with PouchDB enabled. PouchDB is started correctly on port 5980
- Start a Studio 8.1.0 with PouchDB enabled. Studio loops on starting PouchDB on port 5980 too

![pouchdb_start_loop](https://user-images.githubusercontent.com/1685373/195361692-39946e31-21da-4c86-8590-2128c9f5a10c.gif)

The start of the PouchDB is looping endlessly

**Comment by gregory-vorbe** [comment]
It works if you open 8.1.0 after another Studio (>8.0.1) but if you first start the 8.1.0 (pouchDB starts correctly) and then a 8.0.1, both Studio have their PouchDB looping.

**Comment by nicolas-albert** [comment]
Use the port 5981 to prevent be killed by a 8.0.x Studio.
Should be ok for **convertigo-14617-develop-8.1.0-beta**
