### ISSUE TITLE
Client-side errors should not contain sensitive information

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#666]

**Comment by nathalie-lammelin** [comment]
Depending on engine preferences properties you've set for errors (see main/advanced)
errors at client-side (Test platform, Url Mapper, Json servlet,..) should reflect your choices.
Errors remains unchanged when at server-side using internal requester (Studio sequence/transaction execution,...).

Note: context informations, exception & stacktrace should not be allowed

For tests you can use attached projects
[issue666_BE.zip](https://github.com/convertigo/convertigo/files/9860916/issue666_BE.zip)
[issue666.zip](https://github.com/convertigo/convertigo/files/9860908/issue666.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14608-develop-8.1.0-beta)**
