### ISSUE TITLE
Sometimes, builders are released while project is being loaded

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#667]
Sometimes, builders are released while project is being loaded because of:
* sequence autostart execution ??
* cross references ??

**Comment by nicolas-albert** [comment]
Too complex and too hard to reproduce for the 8.1.0 release.
Just adding some logs to help futur debug.

**Comment by nathalie-lammelin** [comment]
Reopen if it happens again (with use cases for reproduction)

**Comment by nicolas-albert** [comment]
**No issues for weeks**
