### ISSUE TITLE
[SequenceStep] Source Picker of a SequenceStep must not show "output false" elements

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#668]
Show picker of a SequenceStep on the same project is too verbose, it shows also **output=false** steps node that cannot be used at runtime.
The **public schema** of the target sequence must be used instead of the **internal schema**.

![pickerfalse](https://user-images.githubusercontent.com/225279/198236748-e1223e87-9baf-499f-adb4-9940950af418.png)

**Comment by nicolas-albert** [comment]
Sample project, use show in picker on the Call_PrjA_SeqA step or show the picker from the "source" property of the "copy" element:
[PrjA.zip](https://github.com/convertigo/convertigo/files/9877688/PrjA.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14599-develop-8.1.0-beta)**
