### ISSUE TITLE
[Admin] Logviewer can be long to initialize

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#670]
Convertigo write many log files with rotate: **engine.1.log, engine.2.log, etc …**
Until the **logviewer** is called.
The **logviewer** starts, if needed, to rename files with first/last date in order to allow a fast "search by date".
This rename phase can be long if there is many files to rename.
It could be done time by time in a vulture thread and let the **logviewer** do a fast init.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14599-develop-8.1.0-beta)**
