### ISSUE TITLE
[Studio] Slow scroll or too tiny scrollbar for Engine Preferences

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#671]
Engine Preferences page is composed with accordions. The scrollbar can be too small and cannot show the bottom of the preferences. Also the mouse wheel scroll is too slow.

**Comment by gregory-vorbe** [comment]
Not reproduced in **Convertigo EMS Studio 8.1.0_beta (build 14599-develop-8.1.0-beta)**
