### ISSUE TITLE
right clicking on an app element (into JxBrowser) won't highlight this element in the treeview if any component of the treeview is recursive

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#674]
right clicking on an app element (into JxBrowser) won't highlight this element in the treeview if any component of the treeview is recursive
=> it's causes an infinite loop 

=> see example:
![Capture](https://user-images.githubusercontent.com/11558728/200016980-12c22924-2071-4bf2-9384-cdc9d32662a0.PNG)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14599-develop-8.1.0-beta)**
