### ISSUE TITLE
[Studio] Project creation failed if the registration isn't done

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#675]
Registration is mandatory to get a working Studio.
The wizard can be canceled and let use the Eclipse part of the Studio.
The new project wizard is accessible and try to create a Convertigo project failed with an exception.
Instead a message must invite the user to perform the registration.

**Comment by gregory-vorbe** [comment]
"Please 'Finish' to register." => "Please, click 'Finish' to register." or "Press 'Finish' to register."

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14617-develop-8.1.0-beta)**
