### ISSUE TITLE
[Step] JsonSource fails with single a string element

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#676]
At runtime, a JsonSource step will do an exception (parse error)  if its source is a single element of string, like:
```
<elt type="string">hello</elt>
```
It must not fail and the JsonSource step output variable must contains the string `hello`.

Caution with strings containing double-quotes `"` and return lines.

**Comment by nicolas-albert** [comment]
[Ticket676.zip](https://github.com/convertigo/convertigo/files/9972614/Ticket676.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.0_beta (build 14644-develop-8.1.0-beta)**
