### ISSUE TITLE
Editing an i18n file such as default en.json having build watch activated causes an infinite build loop

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#677]
**Behaviour:** 
- Editing an i18n file such as default en.json having build watch activated causes an infinite build loop

**Steps to reproduce:**
- Create a new Low Code Front end project ([or use reproInfiteRefresh.zip](https://github.com/convertigo/convertigo/files/9972471/reproInfiteRefresh.zip))
- Start building your app
- Also start the build "watch"
- When the initial build is done,  edit an i18n file
- The infinite loop will occur

**Version**
- Reproduced into branch develop at commit hash 5dd3e3990a578d5b14c783ace304034455e25684 (latest)

**Comment by nicolas-albert** [comment]
Removing this part of angular.json assets part (copying the directory on itself):
```{
  "glob": "**/*",
  "input": "../../DisplayObjects/mobile/assets",
  "output": "assets"
},```
Please update with the latest 8.1.0 NGX TPL to test.

**Comment by nicolas-albert** [comment]
Last commit issue : ionic serve doesn't have resources (like i18n)
