### ISSUE TITLE
Cordova plugin dependecies not installed because of regression in NGX template/configs files 

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#680]
angular.json from tpl 8.x is missing this key:
`{
                  "glob": "plugins.txt",
                  "input": "src",
                  "output": "/"
}`

In config.xml, (displayobjects/platforms/android/config.xml), of project template the following comment is missing
`<!-- Application mandatory plugins -->`

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.1_beta (build 14744-hotfix-8.1.1-8.1.1-beta)**
