### ISSUE TITLE
[Studio] Closing a Sequence or a Connector editor also close all editors of the project

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#682]
Open some sequence or connector editors of a project (with or without execute).
Close one of them and all other will close as well.
It can also close SequenceJS of the project (not all the time).

Close an editor must only close itself.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.1.1_beta (build 14744-hotfix-8.1.1-8.1.1-beta)**
