### ISSUE TITLE
JSON_HTTP_transaction's Content-Type dynamic property must override default HTTP headers defined in properties sheet

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#684]
When creating a new JSON_HTTP_transaction, by default it contains in properties sheet, a Content-type HTTP header; but users are not aware of that.

In a other hand, while creating a new JSON_HTTP_transaction, a modal shows up and gives you some options for dynamic properties, such as content-type. 

It can be very confusing that the value set into this property is not used.

In my opinion this dynamic variable must override any property defined in property sheet.

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64-15853-develop**
