### ISSUE TITLE
SQL Connector: Incorrect JSON parsing for NULL integers

### ISSUE THREAD

**Issue by dams666** [convertigo/convertigo#686]
SQL Connector produces wrong results when parsing NULL integer values. See **structure_num** field

**XML Input**

<?xml version="1.0" encoding="UTF-8"?><document connector="" context="studio_energisme_ddeom_be:S:Get_site" contextId="studio_energisme_ddeom_be:S:Get_site" fromStub="false" fromcache="false" generated="Thu Dec 08 15:05:46 CET 2022" project="energisme_ddeom_be" sequence="Get_site" signature="1670508346794" transaction="" version="8.1.0 (build 14680-8.1.0)">
    <transaction>
        <document connector="SQL_connector" context="studio_energisme_ddeom_be:C:SQL_connector" contextId="studio_energisme_ddeom_be:C:SQL_connector" fromStub="false" fromcache="false" generated="Thu Dec 08 15:05:42 CET 2022" project="energisme_ddeom_be" sequence="" signature="1670508342601" transaction="Get_site" version="8.1.0 (build 14680-8.1.0)">
            <sql_output type="array">
                <row type="object">
                    <id type="integer">11312</id>
                    <nom type="string">Espagne</nom>
                    <adr_num type="string"/>
                    <adr_voie type="string"/>
                    <com_cp type="integer">99060</com_cp>
                    <com_nom type="string">Madrid</com_nom>
                    <structure_rais type="string">MINISTERE DES SOLIDARITES ET DE LA SANTE</structure_rais>
                    <structure_num type="integer"/>
                    <structure_voie type="string"/>
                    <structure_cp type="integer"/>
                    <structure_insee type="integer"/>
                    <structure_com type="string"/>
                    <position type="string">0101000020E610000000000000000000000000000000000000</position>
                    <latitude type="string">0</latitude>
                    <longitude type="string">0</longitude>
                </row>
        
**JSON Output:**

{
  "transaction": {
    "document": {
      "sql_output": [
        {
          "id": 11312,
          "nom": "Espagne",
          "adr_num": "",
          "adr_voie": "",
          "com_cp": 99060,
          "com_nom": "Madrid",
          "structure_rais": "MINISTERE DES SOLIDARITES ET DE LA SANTE",
          "structure_num": {
            "text": "",
            "attr": {
              "type": "integer"
            }
          },

**Comment by gregory-vorbe** [comment]
Hello,

Here is the code you can use if you double-click your SQL transaction:

```
// Handles the XML generated event.
function onXmlGenerated() {
	xpath = context.getXpathApi();
    root = dom.getDocumentElement();
	els = xpath.selectNodeIterator(root, "//*[@type='integer' and .='']");
	while((el=els.nextNode()) != null){
		el.setAttribute("type", "null");
	}
}
```
This will produce the following JSON output:

```
{
  "sql_output": [
    {
      "a": 1
    },
    {
      "a": 2
    },
    {
      "a": 3
    },
    {
      "a": null
    }
  ]
}
```
Instead of:

```
{
  "sql_output": [
    {
      "a": 1
    },
    {
      "a": 2
    },
    {
      "a": 3
    },
    {
      "a": {
        "text": "",
        "attr": {
          "type": "integer"
        }
      }
    }
  ]
}
```

**Comment by nicolas-albert** [comment]
[SqlToJson.zip](https://github.com/convertigo/convertigo/files/10332639/SqlToJson.zip)

Call CreateTable, InsertData and then the SelectAll SQL transactions to reproduce.
