### ISSUE TITLE
shared components are not "synchronized" properly with the project

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#687]
**Behavior:**
* Shared components are not deleted from generated sources when deleting them 
* If you had an error in this shared component, errors will persists until you reload your project
* This annoying because it oblige you to reload your project and recompile it to make it functional again

**Step to reproduce:**
* Import [this project testBugComp.zip](https://github.com/convertigo/convertigo/files/10186466/testBugComp.zip)
* Compile the project in hmr mode
* An error will appear in the JX Browser: `TS2339: Property 'notExist' does not exist on type 'TestBugComp_SharedComponent'.`
* Delete the shared Component from the tree view
* Project will recompile but error will persists

**Version** 
* Dev studio
* Branch: `develop`
* Commit hash: `eebcae2fa00294927d90f0e886870fbb2db960d4`

**Comment by nathalie-lammelin** [comment]
More complex than it seems.
This should be part of a review for proper handling of enabled/disabled/removed beans.

**Comment by nathalie-lammelin** [comment]
This is fixed in the `ngxnew` branch. Will be closed after merge into `develop` branch.

**Comment by nathalie-lammelin** [comment]
Fixed by #724

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64-15853-develop**
