### ISSUE TITLE
Angular.json's assets properties are not generated for serve (hmr) configuration

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#691]
**Behavior**
Angular.json 's assets properties are not generated for serve configuration.

In the TPLs, a specific asset configuration from the general asset one, is defined for serve.

We should either generate Custom Actions, assets properties there or change the [angular.json](https://github.com/convertigo/convertigo/files/10287768/angular.json.txt) file

**Step to reproduce**

- try to use tinymce shared component from lib_ExtendedComponents_ui_ngx
- you wont see the component appears in HMR mode, since needed assets can't be fined
- Change to localhost:18080 (fast build mode) and the Tinymce will appear.

- **_Alternatively you can change your template's [angular.json](https://github.com/convertigo/convertigo/files/10287768/angular.json.txt) to this one to make it work_**

**Comment by nathalie-lammelin** [comment]
Tested OK with tpl_`8.0.0` and tpl_`8.1.0`
