### ISSUE TITLE
[Studio] Synchronize some beans Name property with an another property value

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#700]
Link with #698

The idea is to reduce user interaction to set a correct bean Name AND a the property that reflect the bean usage.
This is often the case for Sequence Steps tagname properties ("person", "email", "type" ...).

A user will drop something from the palette, automatically set an appropriate name and voilà: bean name and main property set!

If the property value and the bean name are equal, the property is synced when the bean is renamed.

Change the property value will not change the bean name (unsynced).

**Comment by nathalie-lammelin** [comment]
Found a regression about dnd from palette to app viewer.
Steps to reproduce:
- create a new ngx project
- launch its app viewer
- when ready, drag a `button` from the palette to the app viewer (inside page content)
The new `button` isn't visible in tree under its parent (the `content` parent tree-object isn't reloaded)

Seems it came with first commit
 before : `ClipboardAction.dnd.paste(xmlData, ConvertigoPlugin.getMainShell(), view, treeObject, true);`
 after    : `TreeDropAdapter.paste(source, fTarget, true);`
