### ISSUE TITLE
[Studio] : Modify text in New project wizard to explicitly explain that you can create Web / desktop & Mobile projects

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#702]
Change "Create a Front-end low code project " to "Create a Low Code FullStack Web/Desktop or Mobile app Project"

**Comment by opicciotto** [comment]
Also Change viewport control:
- Set Arrow down icon to White (In dark mode, leave it as is in light mode)
- Change text to "Desktop/Web" instead of "No Canvas"

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64-15853-develop**
