### ISSUE TITLE
Creating a symbol from a sequence variable using text editor causes stackoverflow error

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#705]
Behavior:
* Creating a symbol from a sequence variable using text editor causes stackoverflow error

Steps to reproduce:
* When editing a sequence variable default value, click on the 3 dots to open variableName-value.txt editor
* Define a new symbol such as ${myProject.myValue}
* Save the file
* A stackOverflow error pops  

Version:
* develop, commit hash: 7a95a82cc0b9b7fe7a70ce1d3214b7acb8e1593a

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 15693-develop-8.2.0-beta)**
