### ISSUE TITLE
[studio] Warn user with a dialog box and ask if wants to build its app now  now before deploying a project on a server 

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#708]
We already have a warning (In red)  to ask the user to build  its app un production mode before deploying it on a server. unfortunately many users just bypass this warning message and deploys (about 90% cases)  unbuilt applications .. This is should be fixed using the following workflow :

- User right clicks-> Deploy project
- Version dialog box appears for version change and user can select what he wants to deploy (tests cases, assets etc...) NO RED MESSAGE IS SHOWN HERE
- User Press Continue
- If the app is unbuild a new page appears in the wizard with this text "Your application is not yet built for deployment, would you like to build it now ?"  If user presses Yes button, the build process is launched and the continue button is disabled util the build finished with no error. If there is an error the user can only cancel. The use can also press no and the wizard switches to the next page without building. A "Remember my decision" check box can also be added here.
- If the app is already built for production, this page is skipped.
- Anyway the wizard finishes on the "Convertigo Environment"  page to let the user select the env he wants to deploy on.

**Comment by gregory-vorbe** [comment]
Convertigo EMS Studio 8.2.0_beta (build 15423-develop-8.2.0-beta)

In 1280*1024 resolution, the window is out of the Windows desktop frame and can not be moved, the height seems to big too:

![image](https://user-images.githubusercontent.com/1685373/223984006-6c00a67b-841b-4cf3-94e2-afadb346b80b.png)

**Comment by nathalie-lammelin** [comment]
Should be fixed by #728

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 15653-develop-8.2.0-beta)**
