### ISSUE TITLE
Display setGlobal action using 'Property' and 'value' properties

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#71]
For example, if 'Property' is set to myGlobalVariable and 'value' set to myGlobalValue, object should be displayed in tree as: 
myGlobalVariable <= myGlobalValue

**Comment by gregory-vorbe** [comment]
In **Convertigo EMS Studio 7.6.0_beta (build 03079-develop-7.6.0-beta)**:

 - OK for TX value
 - OK for TS value
 - Too complex for SC value, maybe should be the same syntax as seen in 'value' property of the SetGlobalAction.

**Comment by nathalie-lammelin** [comment]
Need clarification

**Comment by opicciotto** [comment]
What we really need is that Pseudo beans Display in the tree view should be controlled by a toString() method implemented in the ion_objets.json object in javascript. In this way, the display of the bean in the tree view can be modified only by some code in the ion_objects.json without modifying the java code. This is mandatory to have other beans developed by the community.

We can leave this as is for now  (in 7.6) just fix the case for SC.

**Comment by nathalie-lammelin** [comment]
Sample project for test:
[issue71.zip](https://github.com/convertigo/convertigo/files/3265138/issue71.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
