### ISSUE TITLE
MacOS: global symbol imports are not effective

### ISSUE THREAD

**Issue by mathieu-francois** [convertigo/convertigo#713]
Convertigo Studio 8.2.0 beta build 15052

When importing a project, the dialog window for global symbols shows up. If I check the checkbox to import all project's symbols or if I click create symbol one by one, symbols are not created in the admin Console.

Some symbols are detected twice or more : 

<img width="821" alt="Screenshot 2023-02-10 at 14 15 58" src="https://user-images.githubusercontent.com/42969589/218109515-e5e70277-355f-4242-991f-75bcd446962d.png">

**Comment by nicolas-albert** [comment]
Regression from #705 since https://github.com/convertigo/convertigo/commit/539264c0326d587023c191f85c4a876ffd302104
No only for MacOs.

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64**
