### ISSUE TITLE
[MB] Add a ClearDataSource action bean

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#72]
When using a call sequence bean or a FS view bean (with or without a Marker) in a PageEvent event to display data, these data a stored by CAF. If you leave the page an then re-enter it, before you get the new reponse of the requester the old data are still displayed beacause of the stored data in the Listen. To prevent this behaviour you can add a customAction bean to use a CAF method called deleteListen:
```
CTS1550677588433(page: C8oPageBase, props, vars, event: any) : Promise<any> {
	return new Promise((resolve, reject) => {
	/*Begin_c8o_function:CTS1550677588433*/
	    this.deleteListen(['fs://boitalire.view#BOOKSBOX']);
	    resolve();
	/*End_c8o_function:CTS1550677588433*/
	});
}
```

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03079-develop-7.6.0-beta)**
