### ISSUE TITLE
Multiple stubs for one sequence

### ISSUE THREAD

**Issue by mathieu-francois** [convertigo/convertigo#721]
Today we can make only one stub for a sequence, but a sequence can have different output regarding its parameters it would be nice to be able to make multiple stubs for one sequence

**Comment by nathalie-lammelin** [comment]
I was not able to place the dynamic menu in the same place as before (after 'Execute' seq/tr)
Close ticket as done.

**Comment by gregory-vorbe** [comment]
The file save window should not be used here as stub files are only "read" from the "**stubs**" folder within the project.
This should be only a dialog asking for the file name without the possibility to choose or create a folder.
What is the need of a default stub file as you have to select it to execute it? There is no context menu "Execute default stub"

**Comment by nicolas-albert** [comment]
Some errors in the console if no stub yet:
```
java.nio.file.NoSuchFileException: /***/Issue778/stubs
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
	at java.base/java.nio.file.Files.list(Files.java:3792)
	at com.twinsoft.convertigo.eclipse.menus.StubDynamicMenu.listStubFiles(StubDynamicMenu.java:191)
```

**Comment by nathalie-lammelin** [comment]
Pushed in branch `hotfix/8.2.4` => has to be merged into `develop` branch
For test use build from [convertigo-17104-hotfix-8.2.4-8.2.4-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-17104-hotfix-8.2.4-8.2.4-beta/)

**Comment by nathalie-lammelin** [comment]
Reopen for missing commit

**Comment by nathalie-lammelin** [comment]
Pushed in branch `hotfix/8.2.4` => has to be merged into `develop` branch
For test use build from [convertigo-17114-hotfix-8.2.4-8.2.4-beta](https://convertigo-ci.s3-eu-west-3.amazonaws.com/index.html?prefix=convertigo-17114-hotfix-8.2.4-8.2.4-beta/)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.4_beta (build 17114-hotfix-8.2.4-8.2.4-beta)**

- No error in Studio Console
