### ISSUE TITLE
Add screenshoots to the 'readme' file for project import

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#726]

**Comment by nathalie-lammelin** [comment]
Works for new new projects.
For old projects, you can delete your local `readme.`**`ftl`** file (if not customized) and right-click your project -> `Generate readme.md`.

**Comment by gregory-vorbe** [comment]
Here is the correct screen capture for the remote project URL from a git project:

![image](https://user-images.githubusercontent.com/1685373/223183303-8eeffa7d-853a-4a1a-b68b-4de8a53b1e08.png)
