### ISSUE TITLE
Add an 'event' entry in picker for Action sources.

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#731]
In an action source there is always an event variable that can be used in all the action chain below. We should add it at the root of the picker before the 'in' entry.

This event is structure changes according to the event type. we could describe in ion_objects.json the structure of each well known event such as ionChanged, ionBlur etc ... so that the structure appears below the event entry.

**Comment by nathalie-lammelin** [comment]
![action-control-event](https://user-images.githubusercontent.com/27724039/229528634-97188cac-b935-4a55-a079-be0c794999b6.png)

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64**
