### ISSUE TITLE
[studio] NXG Toggle component is missing the enableOnOffLabels property

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#735]
**Convertigo EMS Studio 8.2.0_beta (build 15563-develop-8.2.0-beta)**
Add the **enableOnOffLabels** property (true | false) in Studio.
According to Ionic 6 framework documentation:
https://ionicframework.com/docs/api/toggle#on--off-labels

![image](https://user-images.githubusercontent.com/1685373/225375176-4df33d77-d1ec-4492-8f05-ddb26374a930.png)
![image](https://user-images.githubusercontent.com/1685373/225375241-01b70972-e0a2-4427-bd66-bceb1971986c.png)

**Comment by nathalie-lammelin** [comment]
Done
