### ISSUE TITLE
Add IfAction Hint for AlertAction

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#736]
We need to add an "IfAction" Action under an AlertAction box to handle Cancel  role status. with the contidion

`parent.out.role != 'cancel'`

This will help user to know how to handle their cancel role

**Comment by nathalie-lammelin** [comment]
> We need to add an "IfAction" Action under an AlertAction box to handle Cancel role status. with the contidion
> 
> `parent.out.role != 'cancel'`
> 
> This will help user to know how to handle their cancel role

To handle the cancel role, condition should be `parent.out.role == 'cancel'` ??
What about the `backdrop` role ?

**Comment by nathalie-lammelin** [comment]
> We need to add an "IfAction" Action under an AlertAction box to handle Cancel role status. with the contidion
> 
> `parent.out.role != 'cancel'`
> 
> This will help user to know how to handle their cancel role

To handle the cancel role, condition should be `parent.out.role == 'cancel'` ??
What about the `backdrop` role ?

**Comment by nathalie-lammelin** [comment]
`SwitchAction` added instead of `IfAction`

**Comment by gregory-vorbe** [comment]
IMHO, to fully understand how it works, the Alert component should:

 - Have the Options buttons properties set to CANCEL and OK (text and role)
 - The switch could have Toast component to show the selected role
 - FRom Ionic documentation there is a 'confirm' role, but I was not able to mame it work.

![image](https://user-images.githubusercontent.com/1685373/228264885-fc76faf3-1616-45a3-9520-21a2a0888914.png)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 15783-develop-8.2.0-beta)**
