### ISSUE TITLE
Add FabContainer Hint

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#737]
We need to add a FabButton with a '+' icon in a fabContainer as an Hint.
Also default properties for FabContainer should be :

* Horizontal => End
* Vertical => Bottom
* Edge => False
* Slot => Fixed

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 15673-develop-8.2.0-beta)**

Maybe a FabList could be added too and an event on the FabButton:

![image](https://user-images.githubusercontent.com/1685373/228254834-0bb31817-0fab-493c-b34b-ed967eef59bb.png)

If too heavy for the FabContainer, just add hint to the FabList (side=start and the fabButton icon set to 'chevron-back' for example)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.0_beta (build 15783-develop-8.2.0-beta)**
