### ISSUE TITLE
Add support of application shared actions

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#74]
A shared action is an actions stack declared for the application.
It may be used in any page through an invoke action.

**Comment by nathalie-lammelin** [comment]
Waiting for tests reports...

**Comment by gregory-vorbe** [comment]
How do you map a SharedAction variable to a CallSequence variable, for example?
MobileComponent Source picker is empty for all types or sources:
![image](https://user-images.githubusercontent.com/1685373/57470539-5db8f800-7289-11e9-8f5c-783261767336.png)

**Comment by nathalie-lammelin** [comment]
Picker for actions has been postponed.
In your case, for the `playerTag`variable set its value in TS mode to `params.tag`.
If you have parent actions, you can also use stack['name-of-action'].xxx as usual.

**Comment by gregory-vorbe** [comment]
Thank you.
It works with **params.tag**
This could be added to the Bean documentation. (params.<variable name>)
In my sample test, I used : stack["PlayerInfo"]["in"]["vars"]["tag"]

**Comment by nathalie-lammelin** [comment]
Reopen issue for missing documentation

**Comment by nathalie-lammelin** [comment]
Modified documentation for `SharedAction`, `Invoke SharedAction`, `Variable` and `SharedVariable`.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03693-develop-7.6.0-beta)**
