### ISSUE TITLE
[security] HTTP 404 on Convertigo Studio/Server should not display Default Tomcat page with its version

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#744]
![image](https://user-images.githubusercontent.com/1685373/229734213-062aafa1-53bd-4ab9-9d63-0632ce4ff353.png)

What about having a Convertigo style custom HTTP page?

**Comment by nicolas-albert** [comment]
**Ok for convertigo-studio-8.2.0-beta-win64**
