### ISSUE TITLE
Ngx: Have in Application or NgxApp properties to change manifest.json to set icon name and color theme

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#749]
PWA -> Build prod -> manifest.json
Icon name and color theme should be set dynamically in project properties.

**Comment by gregory-vorbe** [comment]
When changing theme color, there is an issue with the title bar in the PWA : 

![PWA_titlebar_color](https://github.com/convertigo/convertigo/assets/1685373/01b39c63-44d7-481b-9dea-ab8056c9a7d6)

This is because the index.html file in TPL has the following line : 
`<meta name="theme-color" content="#4e8ef7">`

The color value should be changed too **OR** this line should be removed and the title bar has the correct color and does not change after

**Comment by nathalie-lammelin** [comment]
The `<meta name="theme-color" content="#4e8ef7">` has been removed from TPL_8_3_0 index.html file.
See [commit](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/dce0ce9f86148232c1a046470532c8f325d7aa58)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19097-develop-8.3.0-beta)** and new TPL 8.3.0
