### ISSUE TITLE
Update bases (Eclipse / Tomcat / JVM / Node ...)

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#750]
Have to update components to latest versions.

**Comment by nicolas-albert** [comment]
Code editors are broken (like custom action).
Text collapse at each key, popup show and takes focus ...

**Comment by gregory-vorbe** [comment]
✅  NodeJS - 20.14.0 (LTS)
✅  Java - 21.0.3+9 (LTS)
✅ Tomcat - 9.0.89
✅ Eclipse - 2023-12 (crazy editors on Windows with 2024-03)
✅ JxBrower - 7.39.1 (Chromium 125.0.6422.113)
❓ Gradle - 8.6 (Product build)
❓ Tycho - 4.0.7 (Eclipse build)
