### ISSUE TITLE
[Studio] Prevents errors in the console view at first Studio launch

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#755]
The tutorial view tries to use loggers even if the Engine isn't started. This is the case before the registration and psc configuration.
The tutorial view should start only if the Engine is started.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.1_beta (build 16197-hotfix-8.2.1-8.2.1-beta)**
