### ISSUE TITLE
Introduce use, server.set/get and project.set/get to JS scope

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#76]
The idea is to share memory between multiple request, cross sessions.
This can be useful in some case, to keep global object or function.

```
var myfun = project.get("myfun");
if (myfun == null) {
  myfun = function (a, b) {
    return a + b;
  }
  project.set("myfun", myfun);
}

myfun(1, 2);
```

The `server` object works like `project` but global to the server.

The `use` can be used to load a native Java function and speedup the loading of this function for next calls.

```
var md5 = use("org.apache.commons.codec.digest.DigestUtils.md5hex");
log.message("md5: " + md5("hello world"));
```

**Comment by gregory-vorbe** [comment]
A variable (transaction, sequence) can not be named **'server'** or **'project'** because there will be an issue using a step CallSequence/CallTransaction with these variables names (not evaluated correctly).

**Comment by nicolas-albert** [comment]
I'll move them to the `context` object !

**Comment by nicolas-albert** [comment]
Also update the doc : https://www.convertigo.com/documentation/release-7.6.0/reference-manual/convertigo-mbaas-server/javascript-objects-apis/
Ok with convertigo-03826-release-7.6.0-7.6.0 !

**Comment by nicolas-albert** [comment]
Doc move here https://doc.convertigo.com/documentation/latest/reference-manual/convertigo-mbaas-server/javascript-objects-apis/#methods-detailed-list-1
