### ISSUE TITLE
Ngx: SearchBar should be bindable

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#773]

**Comment by gregory-vorbe** [comment]
The **Binding** property default value is set to "not set" in TS mode : 
![image](https://github.com/convertigo/convertigo/assets/1685373/6172ea5d-1e9d-4ac0-84fe-06649951b160)
If you change value, you can not back to "not set", only if you switch to TXT mode.

**Comment by nathalie-lammelin** [comment]
Fixed, see [commit ](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/bb6e663b8ddff143d1da4b883e160514893c4f67) in TPL_8_3_0

**Comment by nicolas-albert** [comment]
Ok with **convertigo-19206-develop-8.3.0-beta**
