### ISSUE TITLE
Testplatform should use json and xml formatters and colors for results

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#775]
Enhance XML / JSON result frame with colors and a way to collapse structures.

**Comment by gregory-vorbe** [comment]
OK in Convertigo EMS Studio 8.2.4_beta (build 16981-hotfix-8.2.4-8.2.4-beta)

![image](https://github.com/convertigo/convertigo/assets/1685373/177c0489-b5fb-4037-afe5-e202d82e1af3)
![image](https://github.com/convertigo/convertigo/assets/1685373/a4ebb19d-a416-4d14-9beb-fbe8bf024df5)
![image](https://github.com/convertigo/convertigo/assets/1685373/b8cc18ae-98fc-4a73-87a0-444b54c74cc6)
