### ISSUE TITLE
Adding __testcase variable to CallTransaction or CallSequence failed at Runtime

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#778]
The testcase only accept **String[]** parameter and it only can be done using SequenceJS.
Cause a ClassCast exception if using a simple String or a mutlivaluated **__testcase** or a source picker.

[see actual method](https://github.com/convertigo/convertigo/blob/cf6b37307a2b238aeb2041b112750af6aa61e3d1/engine/src/com/twinsoft/convertigo/beans/core/TestCase.java#L327)

**Comment by nicolas-albert** [comment]
Sample project with many cases: [Issue778.zip](https://github.com/convertigo/convertigo/files/13299629/Issue778.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 8.2.4_beta (build 17114-hotfix-8.2.4-8.2.4-beta)**
OK in **Convertigo EMS Studio 8.2.4_beta (build 17114-hotfix-8.2.4-8.2.4-beta)**
