### ISSUE TITLE
[Server] Angular router failed because index.html isn't served for path with dot

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#781]
`pwas/published_1700155087722/viewer/published_1700155087722/toto.com/:i` → failed (404)
`pwas/published_1700155087722/viewer/published_1700155087722/totocom/:i` → ok

**Comment by gregory-vorbe** [comment]
OK in Convertigo EMS Studio 8.2.4_beta (build 17301-hotfix-8.2.4-8.2.4-beta)**
