### ISSUE TITLE
[Cache] Add MariaDB + PostgreSQL driver for the Cache Database

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#787]
The Cache Database support MySQL but the MySQL Connector jar is needed. We should propose to use the MariaDB Connector already included in Convertigo.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 8.2.5_beta (build 17459-hotfix-8.2.5-8.2.5-beta)**

-> Tested with PostgreSQL in Convertigo Server
-> Tested with PostgreSQL and MariaDB in Convertigo Studio
