### ISSUE TITLE
[NGX] Bypass Close actions error like 'overlay does not exist'

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#798]
`CloseLoadingAction, ClosePopoverAction, CloseModalAction`
With `Ionic3`, these actions did not generate an error if the control was already dismissed.
With `NGX`, if the control is already dismissed, an error is thrown. We need to ignore it for the action stack to continue.

**Comment by nicolas-albert** [comment]
Tested with a client project.
