### ISSUE TITLE
[NGX] TPL 8.3.0 with Ionic 7

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#800]
Create a new TPL that use Ionic 7.

**Comment by nathalie-lammelin** [comment]
A test project to show `'use'` of shared component with `'child'` components assigned to `'slots'`
(Angular content projection with `ng-content` ): 
[sharedContentProjection.zip](https://github.com/convertigo/convertigo/files/15387602/sharedContentProjection.zip)

**Comment by nathalie-lammelin** [comment]
An internal project to test some pseudo-beans with packages dependencies and/or cordova plugins:
[internalTestPeusdoBeansWithDep.zip](https://github.com/convertigo/convertigo/files/15387661/internalTestPeusdoBeansWithDep.zip)
