### ISSUE TITLE
[Improvement] Create sequences with call transaction when importing REST API yaml

### ISSUE THREAD

**Issue by mathieufrancois0** [convertigo/convertigo#804]
Hello,

a good feature would be to create automatically sequences with at least a call transaction step when importing a REST API yaml for each transactions imported.

The sequence could have the same name than the transaction imported

This could be an option in the following wizard :

![Screenshot 2024-02-20 at 16 46 52](https://github.com/convertigo/convertigo/assets/18006833/ab1400a2-c625-42c9-b97e-08a4f85fa1a7)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.7_beta (build 18208-hotfix-8.2.7-beta)**
