### ISSUE TITLE
Automatically replace whitespace in XML generated response from API

### ISSUE THREAD

**Issue by mathieufrancois0** [convertigo/convertigo#805]
Hello,

some REST API return keys in JSON with whitespaces that causes errors onXMLgenerated. it would be nice to automatically replace the whitespace with an _ 

For now the workaround is to make the call with a HTTP transaction instead of a HTTP JSON transaction and make the treatment in a sequence with a JSON.parse() etc

**Comment by nicolas-albert** [comment]
Ok, reproduced with a simple case:
```
{"":1}
```

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.7_beta (build 18198-hotfix-8.2.7-beta)**
