### ISSUE TITLE
[Studio] BaseRow stub Create or Update should handle upload file via url

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#806]
The CRUD stub creator handle file upload variables but doesn't support upload file via URL.

It should handle it.

**Comment by nicolas-albert** [comment]
![B68FA3FE-FB0F-4649-8100-B5B4809186CE](https://github.com/convertigo/convertigo/assets/225279/b8f39ba8-9069-4fa3-99dd-4ce6b5b13320)

**Comment by nicolas-albert** [comment]
Should also handle multivalued files and delete if empty name.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.2.7_beta (build 18198-hotfix-8.2.7-beta)**
