### ISSUE TITLE
Tooltips component can not use ng-template

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#813]
**Convertigo EMS Studio 8.2.6 (build 17803-8.2.6)**

**Tooltips** component : 
According to documentation https://www.npmjs.com/package/ng2-tooltip-directive you can use an ng-template tag to put your HTML inside, but it does not work. It displays **[object Bbject]**

![image](https://github.com/convertigo/convertigo/assets/1685373/ee0d5e41-b650-4e8b-adc2-d8361846106f)
![image](https://github.com/convertigo/convertigo/assets/1685373/fc7d4b9e-a2ca-4c3a-88e9-737b0a02e898)

Sample project : 
[cd31_popover_leave.zip](https://github.com/convertigo/convertigo/files/14669707/cd31_popover_leave.zip)

Does the Convertigo component Tooltips can perform this? 
Is this a configuration issue?

**Comment by nathalie-lammelin** [comment]
The **8.2.x** uses the ng2-tooltip-directive v**2.9.20** for which the template mode is buggy.
The plugin current version, v**2.10.3**, works according to the documentation. It will be comitted with the **8.3.0**.

**Comment by gregory-vorbe** [comment]
- Add **display** (boolean, default true) and **displayTouchscreen** (boolean, default true) attributes.
 - Make all attributes bound, for example: [shadow]="true"

**Comment by nathalie-lammelin** [comment]
Done in [mobilebuilder_tpl_8_3_0_ngx](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/8338db177baac0cb837fabc6e2da08f7d2fe4ae9)

**Comment by gregory-vorbe** [comment]
default max width propoerties has to be set to **'200px'** in TXT mode and not **200**

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19117-develop-8.3.0-beta)**
