### ISSUE TITLE
segment /:param fails if value is 0 (zero)

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#815]
**Convertigo EMS Studio 8.2.7 (build 18258-8.2.7)**
Have a look at the demo project:
[gutilab_page_data.zip](https://github.com/convertigo/convertigo/files/14853537/gutilab_page_data.zip)

**StartPage** has a form with an input set to number.
When submitting form, it uses a **pushPage** to **endPage** with **Segment** property set to `end-page/:id`
**Page data** property is set to `{id: this.local.idTicket}`
If you set value to 0 the the input and submit form, the url is broken: `http://localhost:48384/end-page/:id?id=`
It is also the case if you leave the input blank (empty string).
It seems to be caused by the condition `if (props.data != undefined && props.data[key])` in PushPageAction function in actionbeans.service.ts file.

https://github.com/convertigo/convertigo/blob/c87b6095763101cf380cc225a6312b89fcd8d4b7/engine/src/com/twinsoft/convertigo/beans/ngx/components/dynamic/actionbeans/PushPageAction.ts#L59

**Comment by nathalie-lammelin** [comment]
Fixed in **mobilebuilder_tpl_8_3_0_ngx**. See [commit](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/fe3d09c3a12bfc71e8479c7286fb688b163b2020)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19097-develop-8.3.0-beta)**
