### ISSUE TITLE
It would be nice to have an angular virtual scroll bean

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#816]
Example of usage : 
![image](https://github.com/convertigo/convertigo/assets/11558728/ed9e7abf-dcc8-4552-aee5-602225e1c759)

doc : https://material.angular.io/cdk/scrolling/overview

**Comment by nathalie-lammelin** [comment]
Works with lastest TPL_8_3_0 [see](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/213461abd6d27e899b85bde5c0538c330484755c)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19117-develop-8.3.0-beta)**

![image](https://github.com/convertigo/convertigo/assets/1685373/4eb6689a-7f70-4888-9b3b-6f99fe0292f8)
