### ISSUE TITLE
DnD Sequence on a Form component does not change 'Control name' property anymore

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#817]
**Convertigo EMS Studio 8.2.7 (build 18258-8.2.7)**

![Studio_Form_From_Sequence](https://github.com/convertigo/convertigo/assets/1685373/964e825c-42b1-4c8b-b490-b0871cadc6b5)

**Comment by nathalie-lammelin** [comment]
Done

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19097-develop-8.3.0-beta)**
