### ISSUE TITLE
Copying and pasting when you have values generated by source picker results in loosing binds

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#819]
Copying and pasting when you have values generated by source picker results in loosing binds

Example : 
When copying and pasting this iterator(*1), priority will change, but binded(*2) values will not.
Its also the case for shared components entry vars such as params12345678 and many others.
![capture_bug2](https://github.com/convertigo/convertigo/assets/11558728/eb3a0b88-6b1e-402f-8286-ecf239c8c141)

**Comment by nicolas-albert** [comment]
in progress: https://github.com/convertigo/convertigo/commit/27a6b03349e520b5604db11e45b29760e7f20df6

**Comment by nathalie-lammelin** [comment]
**Not reproduced since last commit**:
- copy/paste as sibling of a forEach in a shared comp
- copy/paste as sibling of a shared comp in its app

**Note**: since NGX,
- there's no more params12345678 in SC mode
- replacement in TS mode are not done if exists
