### ISSUE TITLE
[NGX] TreeviewComponent does not work anymore since Angular16

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#822]
See [https://github.com/CirclonGroup/angular-tree-component/issues/956](https://github.com/CirclonGroup/angular-tree-component/issues/956)

**Comment by nathalie-lammelin** [comment]
ref #800, #822 - Fixed Treeview component thanks to [@ali-hm/angular-tree-component](https://www.npmjs.com/package/@ali-hm/angular-tree-component)
see **mobilebuilder_tpl_8_3_0_ngx** commit at [50f9d23](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/50f9d234361aa19e422612cf9d99f03a3b85ba78)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19097-develop-8.3.0-beta)**
