### ISSUE TITLE
[NGX] UseShared is missing class attribute and its Style content is added in the HTML instead of the scss file

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#825]

**Comment by nathalie-lammelin** [comment]
A test project with styles which overwrites used components styles: [issue825.zip](https://github.com/convertigo/convertigo/files/15387477/issue825.zip)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19117-develop-8.3.0-beta)**
