### ISSUE TITLE
Variable __header_ log visibility not respected for the input document log (like other variables)

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#827]
The variable value should not appear in logs of the input document.

**Comment by gregory-vorbe** [comment]
**Convertigo EMS Studio 8.3.0_beta (build 19037-develop-8.3.0-beta)**
It seems a Context log still shows the value in logs : 
![image](https://github.com/convertigo/convertigo/assets/1685373/a1bede06-c60a-49b0-b7a0-bc4741a4b308)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19057-develop-8.3.0-beta)**
