### ISSUE TITLE
[NGX] Agm core components not supported anymore since Angular16

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#828]
- GoogleMap (agm-map)
- MapMarker (agm-marker)
- MapInfoWindow (agm-info-window)
- MapCircle (agm-circle)

We should mark them as deprecated in the TPL_8_3_0 ("deprecatedTplVersion": "8.3.0.0") and add new alternative components.

**Comment by nicolas-albert** [comment]
Deprecated is maybe the good option.
A fork with NG 16 support exists but I don't know if API is compatible with our existing components : https://www.npmjs.com/package/@druk/agm-core

**Comment by nathalie-lammelin** [comment]
Agm components marked them as deprecated in the TPL_8_3_0
See [commit](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/906e0c56d465d2cc75b7895025bb19acc78906da)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19097-develop-8.3.0-beta)**
