### ISSUE TITLE
Generate Documentation for NGX Components

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#829]
Handle NGX Components from the current default TPL to complete the generation of the NGX Components references.

**Comment by nicolas-albert** [comment]
Generated doc seems ok:

http://c8o-documentation.s3-website.eu-west-3.amazonaws.com/documentation/develop/reference-manual/convertigo-objects/mobile-application/ngx-components/

**Comment by gregory-vorbe** [comment]
All NGX components seem to be present.
