### ISSUE TITLE
Default Mobile builder template for the 7.6.0

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#83]
Add the `mobilebuilder_tpl_7_6_0` for the new version.

**Comment by nathalie-lammelin** [comment]
Reopen: until release

**Comment by nathalie-lammelin** [comment]
Updated tpl version to **7.6.0.3** since [6d1cadc](https://github.com/convertigo/convertigo/commit/43d00a265f2e89942009a57f427057dd07b8bb45)

**Comment by CharlesGrimont** [comment]
Ok for release ...
