### ISSUE TITLE
Choose for package APK or bundle AAB for Android release build

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#831]
Cordova Android have a `--packageType=[apk|bundle]` parameter that cannot be configured.
A new parameter for Android platform `Release package type` must be added in order to set this setting.

See the Cordova documentation: https://cordova.apache.org/docs/en/dev/guide/platforms/android/index.html

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19146-develop-8.3.0-beta)**
