### ISSUE TITLE
[Studio] Adding and use a sharedComponent does not appear in page if Mobile Builder tab is already opened

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#834]
Steps to reproduce:

1. Launch an NGX Application. Mobile Builder Tab is opened with your application in the Studio.
2. Create a new SharedComponent component.
3. CTRL + Drag and Drop the SharedComponent to the content of your page to create the use SharedComponent.
4. The Mobile Builder Application seems to rebuild (progress circle shows up).
5. Your SharedComponent does not display.

You have to close the Mobile Builder Tab and relaunch Application to build properly and see the SharedComponent.

**Comment by nathalie-lammelin** [comment]
Every time it doesn't work, there is the following trace in the console
```
[HMR] Update failed: ChunkLoadError: Loading hot update chunk runtime failed.
(missing: http://localhost:49466/runtime.f284d6d62e96885d.hot-update.js)
    at http://localhost:49466/runtime.js:851:26
    at new ZoneAwarePromise (http://localhost:49466/polyfills.js:11131:21)
    at loadUpdateChunk (http://localhost:49466/runtime.js:846:20)
    at http://localhost:49466/runtime.js:1306:29
    at Array.forEach (<anonymous>)
    at __webpack_require__.hmrC.jsonp (http://localhost:49466/runtime.js:1301:22)
    at http://localhost:49466/runtime.js:559:47
    at Array.reduce (<anonymous>)
    at http://localhost:49466/runtime.js:555:55
    at _ZoneDelegate.invoke (http://localhost:49466/polyfills.js:10119:158)
```

**Comment by nathalie-lammelin** [comment]
Was able to reproduce also in Studio 8.1.0.

**Comment by nathalie-lammelin** [comment]
When the component is created (therefore not yet used in the app), even if its source files are generated, they are not available at the webpack level (seems to be an optimisation). If the component is used subsequently (via a 'use' in a page) the update generates the HMR error above.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19286-develop-8.3.0-beta)**
