### ISSUE TITLE
[Studio] Baserow view stub generator should generate table_id in quotes

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#837]
Sometime, JS numeric cast number with ".0" and this is the case for table_id.

If you generate a Sequence for `table_id = 123;`, I don't know why but for some runtimes, the API url is generated with `table_id/123.0/` and failed.

To prevent this, the generate Sequence should be `table_id = "123";`.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19286-develop-8.3.0-beta)**

![image](https://github.com/convertigo/convertigo/assets/1685373/dfa926ea-ca07-4eef-a8ab-d8c17e07842d)
