### ISSUE TITLE
[NGX] PageComponent should have a hint

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#838]

**Comment by nathalie-lammelin** [comment]
Works with [latest](https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/66298a873036873fdaff1eaa210378536283e596) TPL 8.3.0.

**Comment by nathalie-lammelin** [comment]
Page's hint should be modified to add Toolbar, etc...

**Comment by gregory-vorbe** [comment]
Added complete Page hint in https://github.com/convertigo/c8oprj-mobilebuilder-tpl/commit/477324086d73079d980480d805709caa61d34b35

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.0_beta (build 19286-develop-8.3.0-beta)** with latest 8.3.0 TPL
