### ISSUE TITLE
As new array safe operators are now available we should use them when generating binding sources on Array

### ISSUE THREAD

**Issue by eragont06** [convertigo/convertigo#841]
For example if we have a 

`listen(['QuestHunter.GetAdventuresForCurrentUser']).results[0].Aventures
`
Binding source , we currently generate

`listen(['QuestHunter.GetAdventuresForCurrentUser'])?.results[0]?.Aventures
`
but we should now generate

`listen(['QuestHunter.GetAdventuresForCurrentUser'])?.results?.[0]?.Aventures
`
The news array safe operator is  Array.?[index]

(Improvement asked by opic )

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.1_beta (build 19578-hotfix-8.3.1-beta)**

![image](https://github.com/convertigo/convertigo/assets/1685373/06493732-9503-488f-b093-34fb7dd26080)
