### ISSUE TITLE
shared components files not copied to main project when using multiple nested shared components from another project

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#844]

**Comment by gregory-vorbe** [comment]
Here are projects to reproduce the problem (projectA does not build correctly):

[conv974_projectA.zip](https://github.com/user-attachments/files/16287078/conv974_projectA.zip)
[conv974_projectB.zip](https://github.com/user-attachments/files/16287080/conv974_projectB.zip)

**Comment by nathalie-lammelin** [comment]
to be back ported as needed

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.4.0_beta (build 19755-develop-8.4.0-beta)**

Maybe it could be back port to 8.3.1_beta
