### ISSUE TITLE
"Include in auto menu" Page property does not hide Page title un

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#848]
**Convertigo EMS Studio 8.3.0 (build 19367-8.3.0)**

![c8oStudio_issue_automenu-0](https://github.com/user-attachments/assets/30acd08c-94e9-490d-b3d1-8b0e85b53c3b)

**Comment by nicolas-albert** [comment]
This is due to a missing style declaration in the blank projet NGX. Fix have to be reported to existing projects.
See the patch here: 
https://github.com/convertigo/c8oprj-template-ngx-builder/commit/7562a855519d9539659de7b4586289b26955c5e0

Patch content to add in the global style of the app:
```
[hidden] {
  display: none !important;
}
```

**Comment by gregory-vorbe** [comment]
OK **Convertigo EMS Studio 8.3.1_beta (build 19957-hotfix-8.3.1-beta)**

_ Workaround confirmed!
