### ISSUE TITLE
[NGX] Toast color property has no effect

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#856]
**Convertigo EMS Studio 8.3.1 (build 20049-8.3.1)**

![image](https://github.com/user-attachments/assets/86e5716b-9fbe-4b44-857c-e68348ebe827)
![image](https://github.com/user-attachments/assets/0ba0655b-4c44-45f8-a147-f29df584b4e0)

Editing the actionbeans.service.ts file to force the color property : 
![image](https://github.com/user-attachments/assets/9e5cdf9d-d012-499e-82ed-81288b8e7e81)
![image](https://github.com/user-attachments/assets/ab674684-c021-4382-abe2-7de283a4e45b)

**Comment by nicolas-albert** [comment]
Fixed directly in `mobilebuilder_tpl_8_3_0_ngx`, check it by renew your tpl.
