### ISSUE TITLE
[Admin] Allows to kill session with roles

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#858]
You cannot kill session with roles, even if it's not your session.
Some session (internal) cannot die from timeout or with a very long timeout.
We should do a terminate session with force.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 8.3.2_beta (build 20180-hotfix-8.3.2-beta)**

![image](https://github.com/user-attachments/assets/9dd0e247-dac3-477a-af47-88a25fe55c07)

Works with the "Delete the session" button only.
Inoperative on the "Delete all sessions and contexts" button (by design)
