### ISSUE TITLE
Dynamically Change the Build BUILD_UPDATE_DEBOUNCE_MS value in watch.js in ionicappscipt

### ISSUE THREAD

**Issue by opicciotto** [convertigo/convertigo#86]
When the mobile builder changes files of a project, ionic triggers the build immediately. Even if we try trigger again the build process to be sure all the files are taken into account, we sill have issues about missing code in apps as the build process started too soon.

Another solution could be to change dynamically the BUILD_UPDATE_DEBOUNCE_MS value in _private\ionic\node_modules\@ionic\app-scripts\dist\watch.js so that ionic waits for this value to trigger the build process.  This will let us all the time need to be sure all the modified files are correctly committed on disk before the build starts.

**Comment by nathalie-lammelin** [comment]
Waiting for tests reports...

**Comment by nicolas-albert** [comment]
Ok now ?
Can we close for test ?

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
![image](https://user-images.githubusercontent.com/1685373/57775138-a6a2fd80-771c-11e9-9b85-be54f7914f86.png)
