### ISSUE TITLE
Zoneless support

### ISSUE THREAD

**Issue by CharlesGrimont** [convertigo/convertigo#860]
**Studio:** 

Provide zoneless support by calling in a finally at the end of each generated ETS the "markForCheck" function which explicitly marks the view as changed so that it can be checked and refreshed again.
The code must be generated for any TPL greater than or equal to version 8.4.0.0.

**Template side:** 

Enable zoneless support by upgrading to angular 18.X, adding "provideExperimentalZonelessChangeDetection" provider to app.module.ts and removing zone.js imports from polyfills.ts

**Comment by gregory-vorbe** [comment]
OK in **Convertigo version 8.3.2_beta (build 20180-hotfix-8.3.2-beta)**

![image](https://github.com/user-attachments/assets/8b503d58-0588-4c51-bf30-e576ea56af95)
