### ISSUE TITLE
[Studio] Add template for GitLab CI/CD

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#861]
We have `GitHub Actions` and `CircleCI`, we should handle `GitLab`.
The entry should be added on the right-clic project menu.

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.2_beta (build 20180-hotfix-8.3.2-beta)**

![image](https://github.com/user-attachments/assets/fe852225-d495-40f8-909c-e260a02273f8)

![image](https://github.com/user-attachments/assets/fb7bc54f-87c6-4c33-a1b4-ed212ca04baa)

![image](https://github.com/user-attachments/assets/8a9e10ac-6125-4fec-b761-fddc3de6e5fa)
