### ISSUE TITLE
From TPL 8.1.0 to TPL 8.3.0 property Accept of the Text Input component has disappeard

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#866]
Template project	mobilebuilder_tpl_8_1_0_ngx : 

![image](https://github.com/user-attachments/assets/33751818-7e90-4d53-9640-1956419209ad)

Template project	mobilebuilder_tpl_8_3_0_ngx : 

![image](https://github.com/user-attachments/assets/06fc5cfd-1ff6-4b0e-9a5a-16783d166c26)

**Comment by gregory-vorbe** [comment]
Ok, thank you for the information!

**Comment by nathalie-lammelin** [comment]
**TPL 8.3.0 has been updated**: added back Accept property for TextInput (even if deprecated)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 8.3.2_beta (build 20120-hotfix-8.3.2-beta)**
