### ISSUE TITLE
[MB] Add option to call sequence from MB to change the Content-Type header

### ISSUE THREAD

**Issue by mathieufrancois0** [convertigo/convertigo#872]
### Use case : 

I read a csv file and display it in my UI. The user can do some operation (remove lines, update cells etc) on data and then store it in a Postgres db. 
Basically I have to read the file twice (first for the preview and then for the insert), I want to send to my insert sequence the data updated by the user.

### Behaviour

The default behaviour of a call sequence from Mobile Builder is to set the Content-Type header as "application/x-www-form-urlencoded"

But sometimes we want to add a too large stringified JSON. There is a limit added by web browsers to the url for the number of characters. 

The idea is to add a new property to the Call Sequence bean to be able to set the Content-Type at least to "application/json" and send the variables as a body.

With a too large JSON the sequence is not even called : 

![Screenshot 2024-12-08 at 12 29 51](https://github.com/user-attachments/assets/c443a090-1a3f-4209-9fbb-7790868a7af0)

### Current workaround

Sending a file is automatically setting the Content-Type request header to "multipart/form-data" and so we can pass through the browser limitation and the JSON is well interpreted by the sequence.

**Comment by nicolas-albert** [comment]
I don't know about a browser limitation about sending POST payload for a specific content-type, do you have any error in your devtool for the request.
What is the size of your JSON ?
A reproduction project is welcomed.

**Comment by nicolas-albert** [comment]
Thank you, I can reproduce.

With the SDK, if Call's variables are all strings (not file) they are sent as `application/x-www-form-urlencoded`. Tomcat will decode this as `parameter` for us and it seems to have a 2 Mo buffer limit: https://tomcat.apache.org/tomcat-9.0-doc/config/http.html

> maxPostSize:
> The maximum size in bytes of the POST which will be handled by the container FORM URL parameter parsing. The limit can be disabled by setting this attribute to a value less than zero. If not specified, this attribute is set to 2097152 (2 MiB). Note that the [FailedRequestFilter](https://tomcat.apache.org/tomcat-9.0-doc/config/filter.html#Failed_Request_Filter) can be used to reject requests that exceed this limit.

If one parameter is a file, we send them as `multipart/form-data` and Convertigo decode `parameters` and `files` and the previous limit isn't reached.

I'll search if we can force the `multipart/form-data` without File in SDK.

**Comment by nicolas-albert** [comment]
We have a way to force this mode, just add a parameter with a Blob type :
<img width="429" alt="image" src="https://github.com/user-attachments/assets/c291692a-26f9-423b-ad22-7275f158e16f" />

Is this enough for your case ?

**Comment by nicolas-albert** [comment]
Very specific case with a simple workaround, closing it ...
