### ISSUE TITLE
Add a CouchDB/FullSync AllDocs and Purge transactions

### ISSUE THREAD

**Issue by nicolas-albert** [convertigo/convertigo#88]
Just add 2 transactions:
- allDocs : returns list of docs (like view) filtered by startkey/endkey
- purgeDatabase : really remove documents from the DB and change the base version (see #22).

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**.

- Warning in XML response if couchDB <2.3.0

- OK in Convertigo 7.6.0-beta docker and couchDB 2.3.0
