### ISSUE TITLE
OAuthLogin with OpenID: please make response_type customizable

### ISSUE THREAD

**Issue by AlexisBezverkhyy** [convertigo/convertigo#91]
Hello,

Out company uses OpenID for external authentication, but response_type must be set to "code" and in OAuthLoginAction.ts it is hard-coded to "token+id_token". `response_type=code` is already used for LinkedIn authentication so it would be nice to have a customizable response_type property on the OAuthLogin component that could default to "token+id_token" for backward compatibility.

Also the lib_OAuth project provides redirect pages getToken.html and getTokenLinkedIn.html. Both of them are very short and simple javascript, the first sends a message and closes when it finds a token in the URL and the second one does the same with code. I think both pages could be merged into one javascript that handles both flows and it could react seamlessly to either value of response_type.

Thank you in advance,

**Comment by opicciotto** [comment]
Will be merged from 7.5.7

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03720-develop-7.6.0-beta)**
