### ISSUE TITLE
Mobile Picker Sources must be reviewed

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#93]
```
{
  "filter":"Database",
  "project":"IonicConferenceApp",
  "input":"listen(['fs:\/\/conferenceapp.view#all, {ddoc='speaker', view='all'}'])?.rows"
}
```
The object that holds the information from the source is not suitable.
It should be able to regenerate the actual 'input' string by itself, for:
- better refactoring in case of source rename, copy / paste ...
- better management of the dnd
- ...

!! Sources MIGRATION is disabled. New sources format is available at next project save !!

**Comment by opicciotto** [comment]
Ok for me .
