### ISSUE TITLE
Add support of App events

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#95]

**Comment by nathalie-lammelin** [comment]
Documentation needs to be updated to add supported app events.
To be done in `src/com/twinsoft/convertigo/beans/mobile/components/res/UIAppEvent.properties`

**Comment by nathalie-lammelin** [comment]
Documentation modified by opicciotto from 6d734ff to 465c7a6.

**Comment by gregory-vorbe** [comment]
Fixed documentation typos at f29a825fdc6bf7e199ce46c2566c44d3a29f1527

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03720-develop-7.6.0-beta)**

 *  Tested all events in a device, except for onNetworkReachable that was tested on desktop mode.
