### ISSUE TITLE
Update "Welcome" page in Convertigo Studio

### ISSUE THREAD

**Issue by lexinor** [convertigo/convertigo#97]
* This page needs to be updated to match the current version of the studio
* Needs to be converted to dark theme

![c8ostudio_26](https://user-images.githubusercontent.com/28725795/55469179-35dcd180-5605-11e9-99ae-d7e152f799a1.PNG)

**Comment by gregory-vorbe** [comment]
Link **Want to know what’s new in Osmium (7.6)   ? click here** redirects to empty page : http://www.convertigo.com/introducing-convertigo-7-6/

![image](https://user-images.githubusercontent.com/1685373/60270033-d9c9d680-98ef-11e9-8dc7-59dda2d67766.png)

![image](https://user-images.githubusercontent.com/1685373/60270068-ed753d00-98ef-11e9-83b8-7fa38d71f646.png)
