### ISSUE TITLE
Copyright has to be updated on the admin console login page

### ISSUE THREAD

**Issue by lexinor** [convertigo/convertigo#98]
- This needs to be updated to 2019

![c8ostudio_default3](https://user-images.githubusercontent.com/28725795/55493026-8883b100-5638-11e9-8b3c-28229e24b32c.JPG)

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 02909-develop-7.6.0-beta)**
