### ISSUE TITLE
Create missing Icons

### ISSUE THREAD

**Issue by nathalie-lammelin** [convertigo/convertigo#99]
See mobile picker palette

**Comment by nathalie-lammelin** [comment]
Missing `Close popover` icons

**Comment by nathalie-lammelin** [comment]
All is done

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0_beta (build 03672-develop-7.6.0-beta)**

Note : SharedComponent and UseSharedComponent icons could be improved (remove arrows white border)

**Comment by nathalie-lammelin** [comment]
Need new icons for the `IfElseAction` and `ElseHandler` (see #137).

**Comment by gregory-vorbe** [comment]
OK in **Convertigo EMS Studio 7.6.0 (build 03826-release-7.6.0-7.6.0)**

 * New icons OK for '**IfElseAction**' and '**Else handler**' components.
 * OK for modified icons of '**SharedComponent**' and '**UseSharedComponent**'.
